### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#10]

**Comment by toqueteos** [comment]
Might be interesting: https://github.com/cyderize/rust-iocp

**Comment by Noxivs** [comment]
I saw it few days ago but i think it will be harder to implement IOCP on a epoll based io library (than vice versa).
We can "simulate" it with a loop but we need at least a direct access to the file descriptor.

**Comment by carllerche** [comment]
Ok, this is a "won't fix". I think the best strategy is to dedicate mio to readiness based platforms and punt windows support to a higher level IO library (I am working on one, but it is still in the early stages).

**Comment by SirVer** [comment]
The readme still mentions windows support as 'eventually'. Should that be removed then?

**Comment by carllerche** [comment]
Ah, sorry, Windows support came back w/ #155 and is in progress: https://github.com/carllerche/mio/tree/windows-wip

**Comment by SirVer** [comment]
:fireworks: Hooray!!!!
