### ISSUE TITLE
Timers and EventLoop::timeout

### ISSUE THREAD

**Issue by vhbit** [carllerche/mio#116]
`kqueue` definitely supports timers as an event via `EVFILT_TIMER`, haven't checked `epoll`.
Which are pros/cons for using `EventLoop::timeout` over "native" timer events?

**Comment by carllerche** [comment]
The `EventLoop::timeout` makes different assumptions than the kernel timers, which IMO are more appropriate for scalable IO. First, the mio timer is very coarse. Tick size is configurable, but the default is 100ms. This means that all timeout requests will be rounded up to the closest 100ms. This is acceptable for the vast majority of IO related use cases.

The win of doing this means that timeouts can be implemented using a [hashed timing wheel](http://www.cs.columbia.edu/~nahum/w6998/papers/ton97-timing-wheels.pdf). This strategy allows in many cases timeouts to be O(1) on setting, expiring, and canceling. In fact, assume a use case w/ an HTTP server that has timeouts of at most 60 seconds. Allocating a hashed timing wheel of only 600 slots would completely remove all collision and make timeouts virtually zero cost. This matters a lot when setting huge numbers of timeouts.

**Comment by carllerche** [comment]
I should also add that the `EventLoop::timeout` implementation does not prevent using OS timeouts as well since they are just FDs and can be registered with the event loop.

**Comment by vhbit** [comment]
Thanks for explanation!
