### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#13]
__Document MIO for use by others__

* [ ] Readme
* [ ] Guides
* [ ] Rustdoc
* [ ] Examples

**Comment by tadman** [comment]
The client/server example provided in the documentation won't compile in the current version of Rust.

I've made [a variation that compiles without warnings](https://gist.github.com/tadman/6af2ae8b523d58af604c) that is probably far from idiomatic, but at least runs.

**Comment by carllerche** [comment]
Closing in favor of #222
