### ISSUE TITLE
Consider renaming the methods of `Try*`

### ISSUE THREAD

**Issue by tbu-** [carllerche/mio#135]
Currently it seems impossible to e.g. call `send_to` from the `TrySendTo` trait, becuase the inherent member function of `UdpSocket` shadows the definition. I could only call it via UFCS: `TrySendTo::send_to(self, ...)`.

**Comment by carllerche** [comment]
This should be fixed once #131 lands.

**Comment by carllerche** [comment]
This is fixed here: 29c5e32fe96e70b762e65fe7d59a605d367d9597

Now, `send_to` is implemented directly on `NonBlock<UdpSocket>` so there should be no more ambiguity.
