### ISSUE TITLE
`as_nonblock` should be `into_nonblock`

### ISSUE THREAD

**Issue by tbu-** [carllerche/mio#136]
I think the convention was to only give the name `as` to functions that do absolutely nothing in terms of the generated code (after inlining), so the function should probably be named `into_nonblock`.

**Comment by carllerche** [comment]
You are correct that `as_*` is probably not the right name. I'm thinking of just `::non_block()` or `::non_blocking()`. Thoughts?

**Comment by tbu-** [comment]
Although that would be possible too, I'd prefer the `into` prefix because that makes it clear that it consumes `self`.
