### ISSUE TITLE
Calling `TryRead::read(..)` on a closed `NonBlock<TcpStream>` succeeds ?

### ISSUE THREAD

**Issue by vberger** [carllerche/mio#147]
As a minimal example:
```rust
use mio::TryRead;

extern crate mio;

fn main() {
    let listener = ::mio::tcp::listen(&"127.0.0.1:8000".parse().unwrap()).unwrap();
    
    let mut socket;

    loop {
        match listener.accept() {
            Ok(Some(s)) => { socket = s; break; }
            Ok(None) => {},
            Err(e) => panic!("{}", e)
        }
    }

    let mut buffer = ::mio::buf::RingBuf::new(1024);

    loop {
        match socket.read(&mut buffer) {
            Ok(Some(n)) => println!("Read {} bytes.", n),
            Ok(None) => {},
            Err(e) => panic!("{}", e)
        }
    }
}

```

Connection to the server described above works (I'm doing it with `nc` from command line), writing text to it works (I get several `Read n bytes.` lines), but once the client closes the connexion, it keeps looping on `Read 0 bytes.` forever.

Shouldn't `socket.read(..)` return something like `Err(EndOfFile)`, or something like that ?
if not, how do you check if the connexion has been closed by client ?

**Comment by carllerche** [comment]
This is expected behavior. Posix signals a closed socket by returning 0 from a read. I just maintained the posix api for now. std::io does the same. I would think keeping the same behavior across all these systems would be the least confusing?

**Comment by vberger** [comment]
Ok, I see, should have searched a little more before asking. 
That's why it also keeps triggering the readable event I guess.
That makes sense, given the "nothing to read yet" is handled by the WouldBlock mecanism.
So the read returning 0 *always* means that the socket is closed ? (assuming there is space left in the target buffer).

**Comment by carllerche** [comment]
[zero indicates of file](http://man7.org/linux/man-pages/man2/read.2.html)

I'll close this for now :smile:
