### ISSUE TITLE
`Nonblock<TcpListener>` is not properly closed when going out of scope

### ISSUE THREAD

**Issue by vberger** [carllerche/mio#149]
Starting from this code, running on Linux-3.18.9:
```rust
extern crate mio;

fn main() {
    let listener = ::mio::tcp::listen(&"127.0.0.1:8000".parse().unwrap()).unwrap();

    loop {
        match listener.accept() {
            Ok(Some(_)) => break,
            Ok(None) => continue,
            Err(e) => panic!("{:?}", e)
        }
    }
}
```
At first execution, once a client is connected, the program quits. The client properly sees the connection being closed.
However, if you try to re-run the program right after, you get this error:
```
thread '<main>' panicked at
    'called `Result::unwrap()` on an `Err` value: Error { repr: Os(98) }'
```
And you have to wait for around 1 or 2 minutes before being able to run int again successfully.

On Linux error `98` is for `Address already in use`, so my guess is that for some reason the file descriptor is not properly closed.

Also, it seems to be properly closed if the program is killed with `^C` before any client connects.

As neither `TcpListener` nor `NonBlock<TcpListener>` provides a `close()` method, I guess this is not expected behavior ?

**Comment by carllerche** [comment]
Hi there. 

This is normal behavior. What you probably want to do is set the reuse address socket option. More info about it [here](http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t). I think the echo server tests show how to set it. 

It may be worth setting it by default though.
