### ISSUE TITLE
Filesystem events

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#15]

**Comment by hauleth** [comment]
https://github.com/go-fsnotify/fsnotify here is list of FS watchers across OSes.

**Comment by carllerche** [comment]
Good reference. Implementations welcome :) It would probably require work in nix first though.

**Comment by carllerche** [comment]
I'm going to close this for now. I'm unsure if mio is the best place for FS events right now....

**Comment by hauleth** [comment]
For me - it is not. It's better to have separate crate like https://github.com/passcod/rsnotify that will handle that in portable way.
