### ISSUE TITLE
README in trunk doesn match the example in the api documentation *edited*

### ISSUE THREAD

**Issue by posix4e** [carllerche/mio#151]
So I can't find the EventLoop in 0.3.0. Perhaps we should instruct users to use the github version?

**Comment by carllerche** [comment]
Which example do you mean?

**Comment by posix4e** [comment]
Sorry http://carllerche.github.io/mio/mio/index.html

**Comment by carllerche** [comment]
I now build docs for the version on crates.io (0.3) and master (0.4). Both are linked to from the README. So, hopefully this issue is resolved :smile: If not, feel free to reopen the issue.
