### ISSUE TITLE
NonBlock::new is a bit of a foot-gun

### ISSUE THREAD

**Issue by fhartwig** [carllerche/mio#154]
Should `NonBlock::new` be accessible to mio users? One could imagine someone accidentally using that instead of `into_non_block` and then being very confused when his program blocks (you know, some hypothetical incompetent user. Definitely not me :wink: )

**Comment by carllerche** [comment]
Yeah. I can see this. I think that `NonBlock` may go away in the future. It was somewhat of an experiment.

**Comment by carllerche** [comment]
I'm going to close this since `NonBlock` has been removed from master (7e95dfd5e9dc436ed608524d44b439d0171c72b6)
