### ISSUE TITLE
Add Standard I/O

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#165]
I recommend to add `stdin`, `stdout` and `stderr` into the library, currently I have to pass the fd to `Io::new` before register into the event loop, and `mem::forget` it after it is done, because `Io` has implemented `Drop` trait, which will close the fd.

```rust
fn stdout() -> &'static Io;
fn stdin() -> &'static Io;
fn stderr() -> &'static Io;
```

**Comment by rrichardson** [comment]
This seems like a very reasonable set of fd's to include by default.  Maybe we can wrap them in some intermediate object which will shield them from the close() on Drop.

**Comment by zonyitoo** [comment]
Or we could just make another struct, maybe name it as `Stdio`, which works similar as `Io`, but do not have `Drop` implemented.

**Comment by rrichardson** [comment]
I guess as long as it has Evented implemented it should be fine.

**Comment by zonyitoo** [comment]
May be it could be implemented like this, 

```rust
struct Stdio(RawFd);

impl Stdio {
    fn new(fd: RawFd) -> Stdio {
        unsafe {
            // FIXME: Need to make stdio non-block???
            let mut opts = libc::fcntl(fd, libc::F_GETFL);
            if opts & libc::O_NONBLOCK == 0 {
                opts |= libc::O_NONBLOCK;
                assert!(libc::fcntl(fd, libc::F_SETFL, opts) == 0);
            }
        }

        Stdio(fd)
    }
}

impl AsRawFd for Stdio {
    fn as_raw_fd(&self) -> RawFd {
        self.0
    }
}

impl Evented for Stdio {}

impl TryRead for Stdio { ... }
impl TryWrite for Stdio { ... }

fn stdout() -> Stdio {
    Stdio::new(libc::STDOUT_FILENO)
}

fn stdin() -> Stdio {
    Stdio::new(libc::STDIN_FILENO)
}

fn stderr() -> Stdio {
    Stdio::new(libc::STDERR_FILENO)
}
```

But ... Is that necessary to set `O_NONBLOCK` on stdio? Will that affect the `std::io`?

**Comment by carllerche** [comment]
Yeah, that's a good question. I have not personally tested, but I read that changing `O_NONBLOCK` is global to the process (even if the fd has been duped).

Could you test this?

**Comment by zonyitoo** [comment]
I have tested it, for calling `println` in multiple threads, some of them will report

```
failed printing to stdout: Resource temporarily unavailable (os error 35)
```

not surprise.

**Comment by carllerche** [comment]
So, I'm not sure what the best strategy is here. It's definitely useful to be able to use `EventLoop` or `Poll` with stdio, but we definitely don't want to set `O_NONBLOCK`.

I think @zonyitoo's original idea (with the `Stdio` wrapper) would be ok as long as the documentation is clear that the handles are blocking and thus should probably not be mixed with (high throughput) non-blocking IO unless care is taken.

@zonyitoo If you want to take your snippet, add it to `unix.rs` (since I am not 100% sure how stdio will work on windows), add some docs, and submit a PR, I will accept it :+1:

**Comment by zonyitoo** [comment]
I suggest this for my [coroutine-rs](https://github.com/rustcc/coroutine-rs) project, which could yield a coroutine automatically when printing to stdio.

According to [this document](http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/dont-set-shared-file-descriptors-to-non-blocking-mode.html), I think I shouldn't adopt the snippet into `unix.rs`, the stdio should not be set with `O_NONBLOCK`.

So I have an idea... make pipes for stdio fds, so that we can control them without interfere `std::io`.

**Comment by zonyitoo** [comment]
I should do some experiments before submitting a PR. ;)

**Comment by carllerche** [comment]
Cool, let me know. coroutine-rs looks nice btw.

**Comment by carllerche** [comment]
Ping. Is there anything left to do for this issue? I'm unsure if there is an action to take or it is a "wont' fix"

**Comment by zonyitoo** [comment]
@carllerche I think this should be marked as won't fix.

But I sincerely wants a data structure for cloning the handle of `Io`, which can be sent between threads and won't close the fd when it goes out of the scope.

But I think it is another issue. So this one should be closed.

**Comment by carllerche** [comment]
I will close this as won't fix.

@zonyitoo Instead of adding a structure that doesn't close the FD, why don't you clone the FD before passing it in?

**Comment by zonyitoo** [comment]
@carllerche How to? If you mean to use `.as_raw_fd()` and then reconstruct the `Io` again, that is what I am doing currently. But how about windows?

If I reconstruct the `Io`, I have to use `mem::forget` to forbid deconstruct, which is not elegant.

**Comment by carllerche** [comment]
Right, if you dup the raw FD before passing it to `Io`, then you can safely let `Io` go out of scope since the FD was duped and the original one won't be closed.

**Comment by zonyitoo** [comment]
I don't think duplicate it is a good idea. What I want to do is to store the fd in the Slab, but also have another copy of it for reading/writing (when the waiting coroutine is waked up).

If using another design, a copy of `Io` has to be sent into a channel for the coroutine that running the EventLoop to register and deregister.
