### ISSUE TITLE
mio::TcpStream::shutdown is missing

### ISSUE THREAD

**Issue by hoxnox** [carllerche/mio#175]
Is there any valuable reason why TcpStream::shutdown was not released (watching current master branch)?

**Comment by carllerche** [comment]
Nope, just not implemented yet. I would happily take a PR for it :smile:

**Comment by hoxnox** [comment]
See #177 PR in mio and #112 PR in nix-rust.

**Comment by zonyitoo** [comment]
@carllerche Please merge. ;)

**Comment by dpc** [comment]
Isn't this fixed already?

**Comment by zonyitoo** [comment]
Yes, indeed.

**Comment by carllerche** [comment]
Closing!
