### ISSUE TITLE
Unintuitive behaviour when sending notifications to a dropped EventLoop

### ISSUE THREAD

**Issue by Vaelden** [carllerche/mio#178]
Right now, when a notification is sent to an EventLoop that has been dropped (explicitly or its thread panicked), no error is returned and the notification stays "stuck" in the queue, and is dropped only when the last associated Sender is dropped.
I find that a little bit unintuitive (completely different from channels in the standard library) it and makes difficult to recover from a panic in an EventLoop.

So I would suggest two ideas to improve that:

* Introduce a new special state in Notify (e.g. `DROPPED`) that would be atomically set when the EventLoop is dropped. When sending a message, Senders would check the state (as usual) but return an error containing the message if the event loop was dropped (like standard channels).
* For the drop strategy, I would suggest one of the following strategies:
  * When panicking / dropping and after setting the `DROPPED` state, the event loop would grab all remaining messages and drop them. This would ensure that they don't stay in an "unreachable" state without being dropped for too long (e.g. if a Sender is still in scope somewhere)
  * Keep the current plan of the last Sender is responsible for dropping everything, but allow a Sender to retrieve the queued messages if the EventLoop has panicked (might allows to recover without losing too many messages)
  *  Keep it as is

Do you have any views on the feasibility of this?

**Comment by carllerche** [comment]
Thanks for opening this issue. What you are describing is something that had slipped my mind. Your description of the proposed fix is spot on. For the drop strategy, I would opt for the first option. So, to summarize, the plan would be:

> Introduce a new special state in Notify (e.g. `DROPPED`) that would be atomically set when the EventLoop is dropped. When sending a message, Senders would check the state (as usual) but return an error containing the message if the event loop was dropped (like standard channels).

> When panicking / dropping and after setting the DROPPED state, the event loop would grab all remaining messages and drop them. This would ensure that they don't stay in an "unreachable" state without being dropped for too long (e.g. if a Sender is still in scope somewhere)

I would happily accept a PR that implements this :smile: (hopefully with tests!)

**Comment by carllerche** [comment]
This is resolved by #189
