### ISSUE TITLE
Add scatter/gather operations

### ISSUE THREAD

**Issue by sdroege** [carllerche/mio#185]
It would be great if there were scatter/gather operations available on the sockets, i.e. wrappers around recvmsg() and recvmmsg(), sendmsg() and sendmmsg().

There are two parts to this:
- the first of both functions can send/receive one datagram, but use multiple buffers transparently
- the second of both functions can send/receive multiple datagrams with one syscall (plus ↑)

**Comment by rrichardson** [comment]
+1, these can probably slot in next to writev/readv in nix-rust, and then be exposed via mio::udp::UdpSocket

**Comment by carllerche** [comment]
:+1:

Similar to #187, we don't know how Rust will implement this feature, so in general, we need to figure out how we want to handle introducing new apis.

* Introduce the new api on `UdpSocket` and change it to what Rust stabilizes.
* Introduce the new api on `UdpSocket` and diverge from `std::net::UdpSocket`.
* Introduce a `UdpSocketExt` trait that contains "unstable" apis and move the apis to `UdpSocket` when `std::net::UdpSocket` stabilizes on an API.

**Comment by rrichardson** [comment]
I think C sounds good if we want to follow Rust library conventions.  

Why do we have separate socket APIs again?

**Comment by carllerche** [comment]
@rrichardson Windows support (#155)

**Comment by carllerche** [comment]
Thanks for submitting the issue.

I'm going to close this due to inactivity. The state / direction of Mio has changed significantly. Mio has a goal of providing Tcp / Udp APIs equivalent to Rust's STD. Mio also has made it possible to implement custom `Evented` types, so it should be possible to implement extra features in third party libraries.
