### ISSUE TITLE
Expose API to set SO_REUSEADDR / SO_REUSEPORT

### ISSUE THREAD

**Issue by sdroege** [carllerche/mio#186]
Maybe as part of bind()/bound(), a boolean allow_reuse parameter. See this note for some things to keep in mind when using these sockopts: https://git.gnome.org/browse/glib/tree/gio/gsocket.c#n1898

I could prepare a patch if such an API would make sense to you

**Comment by carllerche** [comment]
Currently, `SO_REUSEADDR` (as defined by *nix) is exposed via `TcpSocket` (See [here](https://github.com/carllerche/mio/blob/master/src/net/tcp.rs#L60-L62)). `SO_REUSEADDR` is also set by default when calling `TcpListener::bind()`

I would say that `SO_REUSEPORT` could be exposed via `set_reuseport(val: bool)`. Thoughts?

Also, which types are you referring to?

**Comment by sdroege** [comment]
See the link I provided for some comments about the two different sockopts :) What they actually mean is not platform independent, so GLib does different things on different platforms to try to get the closest behaviour to what you usually want and only provides an "allow_reuse" boolean.

**Comment by sdroege** [comment]
I'm referring mostly to UDP sockets btw. It might also make sense for datagram Unix domain sockets, but not sure if it makes sure for stream sockets (TCP / stream Unix domain sockets)

**Comment by rrichardson** [comment]
Also Reliable UDP and DTLS!  ;)  (a boy can dream)

**Comment by sdroege** [comment]
Not sure it makes sense of R-UDP or DTLS, probably only for connection-less sockets :) Otherwise you have different sockets confusing each others connection state machinery

**Comment by pythonesque** [comment]
> I would say that SO_REUSEPORT could be exposed via set_reuseport(val: bool). Thoughts?

This would be very useful.

**Comment by bluejekyll** [comment]
I'll jump on the request for SO_REUSEPORT. This option will allow for process oriented zero-downtime restarts. Simplifies deployments and configuration reloads.

**Comment by tailhook** [comment]
> See the link I provided for some comments about the two different sockopts :) What they actually mean is not platform independent, so GLib does different things on different platforms to try to get the closest behaviour to what you usually want and only provides an "allow_reuse" boolean.

It's strange. I believe Glib is wrong, at least on linux. SO_REUSEPORT changes semantics of the socket in a way that many (I believe most) application don't want.

> I'll jump on the request for SO_REUSEPORT. This option will allow for process oriented zero-downtime restarts.

Well, in fact its not, at least in linux. The option creates a separate in-kernel queue per socket open. When process shuts down linux drops all outstanding connections on queue for this socket, and clients get "connection refused" or "connection reset" (I don't remember exactly).

On normal socket there is only one queue, and any process can accept next socket.

What helps zero-downtime restarts is opening socket by a supervisor, which passes it down to multiple processes.

----

This is not to say that options shouldn't be exposed. But it should not be applied silently like SO_REUSEADDR is.

**Comment by bluejekyll** [comment]
I didn't know that Linux actually uses multiple queues SO_REUSEPORT. Do you know if the BSD's do that? That does make what I want to do a little more complex. Thank you for sharing. I was hoping to avoid the need of a supervisor, oh well. 

On a side note, I completely agree with you about not hiding or defaulting these in strange ways. They all seem to have their nuances depending on the platform your targeting.

**Comment by diegooliveira** [comment]
@bluejekyll I did a [C test program](https://gist.github.com/diegooliveira/adf07fa1f358fa5085df) and the result was exactly what you expected and [what is in the SO_REUSEPORT doc](https://lwn.net/Articles/542629/). You may launch any number of instance you wish in the same port.

> So long as the first server sets this option before binding its socket, then any number of other servers can also bind to the same port if they also set the option beforehand

**Comment by tailhook** [comment]
@diegooliveira yes. That is expected. But performance characteristics are different. And behavior when one of the processes die is unexpected too.

**Comment by carllerche** [comment]
Thanks for submitting the issue.

I'm going to close this due to inactivity. The state / direction of Mio has changed significantly. Mio has a goal of providing Tcp / Udp APIs equivalent to Rust's STD. Mio also has made it possible to implement custom `Evented` types, so it should be possible to implement extra features in third party libraries.
