### ISSUE TITLE
Introducing coroutine-based mio connection handlers.

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#191]
Hi,

Just to let you know, I got the basics of `mioco` working: https://github.com/dpc/mioco/

It narrows down to being able to handle each connection with a function running in per-connection coroutines, that block and unblock automatically and are scheduled quickly in userspace.

Example function:

https://github.com/dpc/mioco/blob/master/examples/echo.rs#L70

What's nice is that the performance of the simple tcp echo seem roughly the same as [non-coroutine example that I played with before](https://github.com/dpc/mioecho), and similar to libev-based tcpecho server.

**Comment by carllerche** [comment]
nice! As it gets further along, we could probably reference it from the README.

**Comment by dpc** [comment]
It seems that more comprehensive solution is being worked on already: https://github.com/rustcc/coroutine-rs/issues/40

**Comment by dpc** [comment]
I'm working on a new design, that will allow arbitrary coroutines, using any number of Evented streams withing each coroutine. With previous design one coroutine could only read and write back to one socket. Now it's possible to write a coroutine that reads from one socket/pipe, writes to different one etc.

**Comment by dpc** [comment]
@carllerche : I've pushed a newest `mioco` revision, that is already quite usable.

It comes with a test-bed project: https://github.com/dpc/colerr - stderr colorizer, which nicely illustrates how mioco works: https://github.com/dpc/colerr/blob/master/src/iomuxer.rs#L104 .

I'm kind of blocked on #204, and I'm using some initial hand-made approach: https://github.com/dpc/mioco/blob/master/src/lib.rs#L87 , that I'd like to remove and use `mio`'s own trait. If you want I can start working on it myself, given some directions.

I'd appreciate feedback. I'm thinking about adding a layer that would completely hide mio-based internals, using some standard `Handler`, that keep tracks of streams, allocates tokens etc.

**Comment by carllerche** [comment]
Ok, I'll look at it now!

**Comment by dpc** [comment]
I think I finally nailed what I was looking for. I'm still fixing bugs and it's all just alpha prototype but an new mioco design echo server example should show what I am targeting:

https://github.com/dpc/mioco/blob/new-design/examples/echo.rs
