### ISSUE TITLE
UnixListener: creates a new file, doesn't work when already existing and does not drop the file

### ISSUE THREAD

**Issue by james-darkfox** [carllerche/mio#195]
`UnixListener::bind` creates a new file should it not already exist, and fails in the case it does. It might be worth having either `impl Drop for UnixListener` to remove the file or extend the code to bind to an existing, but not already bound socket file.

**Comment by carllerche** [comment]
This is how UDS works. I'm not 100% sure why the file is kept around. It would be worth doing some investigation before removing it by default.

**Comment by carllerche** [comment]
I have a goal of deprecating Mio's UDS implementation in favor of a third party crate. I'm going to close this issue now.

**Comment by Timmmm** [comment]
What's the behaviour of `UnixListener` now? Does it delete it on `Drop`? Could do with documenting.

**Comment by Thomasdezeeuw** [comment]
@Timmmm Mio's `UnixListener` has the same behaviour as `std::os::unix::net::UnixListener` on drop.

**Comment by Timmmm** [comment]
Thanks for the info! Seems like std's `UnixListener` doesn't `impl Drop` at all so it will leave files behind by default.

I'll submit a PR to Rust to document that if I get time. Maybe worth saying that mio's `UnixListener` uses std's.

**Comment by Thomasdezeeuw** [comment]
> Thanks for the info! Seems like std's `UnixListener` doesn't `impl Drop` at all so it will leave files behind by default.
> 
> I'll submit a PR to Rust to document that if I get time. Maybe worth saying that mio's `UnixListener` uses std's.

Currently most Mio's types use the std's equivalent, but I don't we want to guarantee this will always be true. Because that would prevents us from changing it in the future (without it being considered a breaking change).

**Comment by Timmmm** [comment]
Wouldn't it be a breaking change to switch the behaviour from what `std` is now even if you never documented that the behaviour was the same as `std`?

E.g. if you add a new `impl Drop` that does delete the socket file that's definitely a breaking change.

**Comment by Thomasdezeeuw** [comment]
> Wouldn't it be a breaking change to switch the behaviour from what `std` is now even if you never documented that the behaviour was the same as `std`?

That depends on the behaviour I suppose, but for the most part yes.

> E.g. if you add a new `impl Drop` that does delete the socket file that's definitely a breaking change.
