### ISSUE TITLE
Support recv_msg for UDP

### ISSUE THREAD

**Issue by SirVer** [carllerche/mio#200]
I have a sensor here that send data via UDP. I am building an experimental reader with MIO/rust for it and so far I really like what I see. Good job on a clean API!!

However I ran into the issue that I cannot ask for one UDP packet, I always have to know how many bytes I want to read beforhand. This is problematic, since I do not know how large the packets are the sensor sends, but they are guaranteed to fit in one UDP packet.

The c code i use in my production client looks a bit like this - this is paraphrased, but contains all the important points.

~~~c++
// recvmsg() is guaranteed to read exactly one full UDP packet, so it is used
// here instead of recv().
struct iovec iov;
iov.iov_base = nullptr;
iov.iov_len = 0;
struct msghdr message = {0};
message.msg_iov = &iov;
message.msg_iovlen = 1;
auto message_size = recvmsg(socket_fd, &message, MSG_PEEK | MSG_TRUNC);
if (message_size < 0 && (errno == EWOULDBLOCK || errno == EAGAIN)) return;

// Now we know the exact message size in the next UDP block. Allocate a buffer
// that fits and use that.
vector<char> message_bytes(message_size);
iov.iov_base = message_bytes.data();
iov.iov_len = message_bytes.size();
auto bytes_read = recvmsg(socket_fd, &message, 0);
assert(bytes_read == message_size);
~~~~

Can I get something along these lines in mio, pretty please?

**Comment by buschtoens** [comment]
Having the same problem.

**Comment by carllerche** [comment]
Sure, I would be ok w/ adding something like this. Is someone up for a PR? I personally don't write udp related code much. Maybe @rrichardson would have an opinion regarding the API.

**Comment by rrichardson** [comment]
I'll take a look at this one, should be trivial to add to nix and mio/sys

**Comment by dns2utf8** [comment]
would you mind creating a simple echo server example? I am working on it but I am unable to create one.

**Comment by carllerche** [comment]
Thanks for submitting the issue.

I'm going to close this due to inactivity. The state / direction of Mio has changed significantly. This issue may or may not be resolved.

For context, Mio has a goal of providing Tcp / Udp APIs equivalent to Rust's STD. Mio also has made it possible to implement custom `Evented` types, so it should be possible to implement extra features in third party libraries.
