### ISSUE TITLE
Some additional traits inheriting from Evented for outside libraries to use.

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#204]
Could `mio` define some additional traits inheriting from `Evented` trait?

In mioco I'm planing to use dynamic dispatch, so the coroutine needs to do everything through trait functions.

It seems to me that mio defined the following clases of `Evented` structs:

* Readers
 * try_read
 * close (inbound)
* Writers
 * try_write
 * close (outbound)
* Listeners
 * accept
 * close (stop listening)
* Connectors
 * connect
* anything else? timers, signals etc?

Could this traits be added to mio? Is this a good idea?

**Comment by carllerche** [comment]
Probably a good idea :smile: I will keep this issue open and come back around to it soon.

**Comment by carllerche** [comment]
Could you say more about why you need to separate close for both read and write. I am assuming that it is to expose socket shutdown, in which case could it make sense to have a `Shutdown` trait that has `shutdown_read()` and `shutdown_write()` functions?

For Listeners, is there a reason to separate out `close()` from dropping the listener?

**Comment by dpc** [comment]
The only case that I'm aware of where inbound and outbound close makes a difference is TCP. For everything else it could be aliased or something similiar. In `mioco` I pass to coroutine uniform array of trait objects, so all the possible trait methods needs to be in that trait and it's up to coroutine to use them properly, but `mio` could group the Evented into any set of distinct traits, and `mioco` could provide default implementation for them just fine. So I'm open to any design of such traits. All I want to avoid is to implement such common trait one-by-one for every `Evented` struct supported by `mio`.

**Comment by dpc** [comment]
Now when I think about it, if `mio` could group `Evented`, then maybe I could use static dispatch and array of enums.

**Comment by carllerche** [comment]
What do you mean by group `Evented`?

**Comment by carllerche** [comment]
I guess, I'm wondering why your lib `mioco` couldn't define it's own trait that extends the set of mio traits that it cares about.

**Comment by dpc** [comment]
"group `Evented`" - define types of `Evented`-implementing structs, that behave the same way. 

mioco does already implement a trait that it uses for everything:

https://github.com/dpc/mioco/blob/master/src/lib.rs#L87

But then I have to implement it for every `struct` from `mio`: https://github.com/dpc/mioco/blob/master/src/lib.rs#L111

If `mio` had a common traits that behave the same than I could do:

```
impl<T> Evented for T where T : mio::Stream {

}
```

```
impl<T> Evented for T where T : mio::Listener {

}
```

and `mio` could add new types, without `mioco` having to add them too. Or event users could add types, if it's possible.

**Comment by dpc** [comment]
What operations are actually asynchronous in `mio` (meaning, they should be attempted after corresponding event for a given token was delivered)? `try_read`, `try_write`, `accept`, anything else?

**Comment by carllerche** [comment]
Those are the ones for TCP. UDP gets more complicated I believe.

**Comment by dpc** [comment]
How does `connect` work asynchronously?

**Comment by carllerche** [comment]
You can tell if a socket is connected by waiting for "writable" on the socket.

**Comment by carllerche** [comment]
`TryAccept` has been added. I would recommend creating a new issue for any additional traits.
