### ISSUE TITLE
mio 0.3.6 doesn't compile

### ISSUE THREAD

**Issue by dimbleby** [carllerche/mio#205]
Lots of errors, of which the first is:

    /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.3.6/src/net/mod.rs:22:27: 22:106 error: this function takes 2 parameters but 3 parameters were supplied [E0061]
    /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.3.6/src/net/mod.rs:22         let linger = try!(nix::getsockopt(self.as_raw_fd(), nix::SockLevel::Socket, nix::sockopt::Linger)
                                                                                                                        ^~~~~~~~~~~~~~

I guess the problem is that your Cargo.toml confidently goes and gets the latest nix from github:

    [dependencies.nix]
    git = "https://github.com/carllerche/nix-rust"

whereas I suppose it ought to get whatever version it actually relies on.

**Comment by carllerche** [comment]
Thanks for the report. I fixed this on v0.3.x. I'll try to push a build shortly.

**Comment by mattcifelli** [comment]
Was this resolved? What could I do to fix this issue locally?

**Comment by carllerche** [comment]
Sorry for the delay. I pushed 0.3.7 to fix this: https://crates.io/crates/mio
