### ISSUE TITLE
Could `Evented` be clonable?

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#209]
Is it technically feasible for all `Evented` to be implement `Clone`? I'm in dire need for sharing them, and it seems to me that they are all just file descriptors and instead of sharing, I could just copy them.

**Comment by carllerche** [comment]
`Evented` can't be `Clone`. It's not ideal to "share" FD handles. A better strategy would be to `dup()` the FD. The issue w/ having `clone()` call `dup()` internally is that `dup()` can fail. Could you say more about your use case that requires `Clone`?

**Comment by dpc** [comment]
It's rather complicated, and I'm just exploring my options. Also, couldn't I just clone manually using `AsRawFd` and `FromRawFd`?

**Comment by carllerche** [comment]
The issue would be knowing when to close the fd which usually happens on drop

**Comment by dpc** [comment]
Ah, right. So how about `Evented` could be explicitly cloned with `dup` underneath, that would return a `Result`? Would that be OK?

**Comment by carllerche** [comment]
Sure, but I would expose that as a separate trait probably.

**Comment by dpc** [comment]
Sure. Are there any `Evented` types (or could they be in the future) that will not implement cloning?

**Comment by carllerche** [comment]
It would be possible... `Evented` is fairly open.

I think that I would be ok w/ Adding a `Dup` trait though.

Related to #204

**Comment by carllerche** [comment]
I'm going to close this for now. I don't think that `Evented` will ever extend `Clone`, but like I said, I would be open to adding a `Dup` trait.
