### ISSUE TITLE
Implement ToSocketAddrs for TcpStream just like in std::new::TcpStream

### ISSUE THREAD

**Issue by talevy** [carllerche/mio#220]
ref in mio: https://github.com/carllerche/mio/blob/master/src/net/tcp.rs#L119

ref in std: https://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.connect

I understand that there is some logic that is private to `std` that cannot be re-used and 
must be duplicated... bit this would be really useful when dealing with urls and domains.

**Comment by dwrensha** [comment]
One thing to keep in mind here is that the [`ToSocketAddrs` impl for `str`](https://github.com/rust-lang/rust/blob/7e9e3896dfcef4852ca8ad90f91baf5187b0248e/src/libstd/net/addr.rs#L423-L449) does DNS lookup by calling [`gettaddrinfo()`](https://github.com/rust-lang/rust/blob/7e9e3896dfcef4852ca8ad90f91baf5187b0248e/src/libstd/sys/common/net.rs#L119-L129), which blocks the calling thread, possibly waiting on network I/O. So you would need to be careful when using this in eventloop-style code.

**Comment by jwilm** [comment]
There's [Rust bindings for c-ares](https://github.com/dimbleby/rust-c-ares) which could solve the blocking part of this issue.

Whether this feature belongs in mio is another discussion. So far, mio has exclusively been a provider of the event loop and utilities for managing loop state (eg, Slab). At the point mio starts doing DNS resolution, it's going to be a consumer of the event loop as well.

I'm generally against it. On one hand, nearly everything I use mio for needs name lookup. However, incorporating this into mio has some drawbacks. Mio would either need to perform some allocations internally, or it could expose additional API surface in the handler and make the application deal with state for DNS lookup. I personally don't want either of those things. It's also outside the scope of what mio aims to be which is a low level event loop abstraction.

It's not too difficult for applications to do async lookup.There's an [example in c-ares](https://github.com/dimbleby/rust-c-ares/blob/master/examples/unix/cares_epoll.rs#L71-L159)  for doing lookups using epoll directly; this example is pretty short, and using mio instead would shorten it further. A reusable lookup component based on c-ares could even be added for applications using rotor (allegedly rotor makes it easy to compose state machines, but I haven't tried it myself).

**Comment by talevy** [comment]
@jwilm awesome, thanks for the info! I agree with you

I can go ahead and close this if @carllerche agrees. Since it seems to have been added to the v1.0 milestone, I don't want to rush to close this without more feedback

**Comment by carllerche** [comment]
On `dev`.

**Comment by talevy** [comment]
awesome! although I have kind of put a hold on my rust work recently, I am stoked this made it in. thanks for the follow-up @carllerche!

**Comment by carllerche** [comment]
So, I should have paid more attention.. but @dwrensha  is right. `ToSocketAddrs` implies blocking DNS resolution. As such, it probably shouldn't be something that Mio encourages.

I reverted the patch. 7b4a7ce9a691895f146d3bb14be1ba5a7cf631ba

Sorry about that.
