### ISSUE TITLE
Composable event loop handlers

### ISSUE THREAD

**Issue by tailhook** [carllerche/mio#223]
Hi,

This issue is to start some discussion on how to build composable libraries with mio.

By being "composable" I mean the following. I have a library that implements protocol A and a library that implements a protocol B, and I can put both libraries on the same loop without writing tons of boilerplate code.

AFAIU, it's a job of another library on top of mio, not mio itself. Have anybody seen such library? Do you know how to actually implement one? Thoughts?

**Comment by carllerche** [comment]
I believe that in most cases, libraries sharing an event loop is a bad idea. I think that generally, libraries should encapsulate their own event loop and expose thread-safe APIs that can be used wherever.

The main issue w/ sharing an EventLoop is that, now, library A is at the mercy of library B being a good citizen (and vice versa). Aka, each library using Mio would need to take into consideration the possibility that  it will be sharing resources with N other libraries (possibly completely unrelated).

I would be open to hearing a counter argument explaining why having libraries share an event loop is preferable.

**Comment by tailhook** [comment]
Well, I didn't look at the question from this point of view :)

> The main issue w/ sharing an EventLoop is that, now, library A is at the mercy of library B being a good citizen (and vice versa)

What do you mean? Do you mean that some library may use blocking calls?

The main use cases I think of:
1. Have an async DNS library, that I might use for whatever I want (e.g. a HTTP client)
2. I may want to build a HTTP proxy, that's basically a combination of HTTP client and HTTP server
3. Even just writing a hander for HTTP server library is kinda composition of state machines which is not trivial to write with mio too (for example http handler should probably have shared mutable state, which is stored inside of `mio::Handler` implementation, but to have HTTP work we must use handler from HTTP server library)

Currently I can only put each library in its own thread and send messages between. I find this approach too wasteful. Especially for (3). Is it what you propose as:

> I think that generally, libraries should encapsulate their own event loop and expose thread-safe APIs that can be used wherever.

**Comment by carllerche** [comment]
Closing for now. Feel free to reopen if there are new things to discuss.
