### ISSUE TITLE
Yet another MIO + coroutine asynchronous I/O library

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#228]
Hi, charllerche,

I just release my first MIO + coroutine asynchronous I/O library `simplesched`:

https://github.com/zonyitoo/simplesched

Just implement it with the most simple techniques, I may release another library with improved scheduling algorithm in the future.

The performance test looks good. :)

**Comment by tailhook** [comment]
Out of curiosity compared it with my implementation (https://github.com/tailhook/rotor-http/blob/master/examples/hello_world_server.rs):
```
> wrk -c 400 -t 2 http://localhost:8888
Running 10s test @ http://localhost:8888
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.22ms    1.13ms  23.08ms   90.99%
    Req/Sec    21.75k     1.60k   24.06k    86.00%
  432820 requests in 10.01s, 36.32MB read
Requests/sec:  43219.72
Transfer/sec:      3.63MB
```
And your implementation looks like this on my laptop:
```
> wrk -c 400 -t 2 http://localhost:8889
Running 10s test @ http://localhost:8889
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.71ms    1.33ms  28.99ms   90.34%
    Req/Sec    14.64k     0.95k   15.91k    83.50%
  291449 requests in 10.01s, 25.02MB read
Requests/sec:  29103.17
Transfer/sec:      2.50MB
```
(both run single threaded, because I don't have too much cores, and my example doesn't support threads)

Unfortunately my implementation is much more incomplete, so comparison is unfair.

**Comment by zonyitoo** [comment]
@tailhook Your implementation have better performance! Let me see what can I do...

**Comment by tailhook** [comment]
@zonyitoo it's to early to compare, because I don't read any headers for determining request length, expect header, whatever... so it may be slower in the final implementation.

**Comment by carllerche** [comment]
Looks cool. I'm going to close this issue for now. You can open a PR if you want to add a link to the project in the Readme.

Cheers.
