### ISSUE TITLE
Could version 0.5.0alpha-1 be published on crates.io?

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#229]
I'd like soon to publish mioco 0.1 on crates.io and until all dependencies are available on it, I'm unable to do it.

**Comment by carllerche** [comment]
I would recommend depending on 0.4. Is there a reason that you want to depend on master? The only changes are some "minor" API changes that I forgot to do on 0.4, so I wanted to get done before I forgot. I don't have any plans to diverge any time soon.

**Comment by carllerche** [comment]
I'm going to close this for now, but if you have a strong reason to need 0.5 alpha to be published, I can reconsider.

**Comment by tailhook** [comment]
What about `TryAccept` trait? I need it for my project too.

**Comment by carllerche** [comment]
There is a `TryAccept` trait in 0.4: https://github.com/carllerche/mio/blob/v0.4.x/src/io.rs#L72

**Comment by tailhook** [comment]
Hm, right, just not in released version. Do you have any plans on releasing 0.4.2?

**Comment by carllerche** [comment]
Done

**Comment by tailhook** [comment]
Thanks!

**Comment by dpc** [comment]
What about newly added `tick()` ? 0.4.3 ?

**Comment by carllerche** [comment]
Yeah. I think I failed at merging it (merged on master vs. 0.4.x). I'll try backporting & release.

**Comment by dpc** [comment]
:)

**Comment by carllerche** [comment]
I released 0.4.3 finally
