### ISSUE TITLE
Does mio have gitter channel yet?

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#238]
It seems there are more and more project building on mio and I think mio as base-project should take care of organizing child-projects in some form of community.

It would be good to have a place to hang out and discuss ideas, to have some notion of what's going on in other projects building on top of mio. Also following mio development is important for people building on top of mio. Unfortunately IRC, without chat history persistence, is good only for quick discussion. So I think it would be nice if mio could have a gitter channel. I would personally like to direct mioco README there instead of mioco's one, as it's just way to small project ATM.

**Comment by dpc** [comment]
@zonyitoo What do you think?

**Comment by carllerche** [comment]
I did an informal survey and there wasn't a huge amount of interest. I will leave this issue around for a bit to see if there are further thoughts.

Another option would be to figure out how to get #mio logged.

**Comment by zonyitoo** [comment]
Gitter is a good start.

**Comment by dpc** [comment]
I like gitter because it has persistent chat, and a mobile app that behaves sanely and does not draw battery like irc clients. And it seems to be popular enough in Rust community.

**Comment by KodrAus** [comment]
I'm new to mio and wouldn't mind a more informal channel to ask easy questions. +1 for gitter from me

**Comment by carllerche** [comment]
@KodrAus We are on IRC in the #mio channel on the mozilla server.

I'm going to close this for now. I don't know if gitter is right for mio right now. I think more important would be a discourse install or something more async.

**Comment by burdges** [comment]
Appears the mozilla IRC server commonly bans Tor users btw : https://bugzilla.mozilla.org/show_bug.cgi?id=802788
