### ISSUE TITLE
only EventSet::hup() doesn't generate events on OSX

### ISSUE THREAD

**Issue by alexcrichton** [carllerche/mio#240]
I wrote this test recently and it passed on Linux but deadlocked on OSX. It looks like the kqueue implementation doesn't like listening with just `EventSet::hup()`?

```rust
extern crate mio;

use mio::{EventLoop, Handler, Token, EventSet, PollOpt};
use mio::tcp::{TcpListener, TcpStream};

fn main() {
    struct H { listener: TcpListener }

    impl Handler for H {
        type Timeout = ();
        type Message = ();

        fn ready(&mut self, event_loop: &mut EventLoop<Self>, token: Token,
                 _events: EventSet) {
            if token == Token(1) {
                let s = self.listener.accept().unwrap().unwrap();
                event_loop.register_opt(&s, Token(3), EventSet::all(),
                                        PollOpt::edge()).unwrap();
                drop(s);
            } else if token == Token(2) {
                event_loop.shutdown();
            }
        }
    }

    let mut e = EventLoop::new().unwrap();
    let l = TcpListener::bind(&"127.0.0.1:0".parse().unwrap()).unwrap();
    let s = TcpStream::connect(&l.local_addr().unwrap()).unwrap();

    e.register_opt(&l, Token(1), EventSet::readable(), PollOpt::edge()).unwrap();
    e.register_opt(&s, Token(2), EventSet::hup(), PollOpt::edge()).unwrap();

    let mut h = H { listener: l };
    e.run(&mut h).unwrap();
}
```

**Comment by hjr3** [comment]
The issue has to do with the way mio translates registration calls into kqueue filters. Each (re)register call from mio creates two new filters kqueue: one for read (`EVFILT_READ`) and one for write (`EVFILT_WRITE`). Based on the interests from the registration call, the read and write filters are enabled (`EV_ENABLE`) or disabled (`EV_DISABLE`). In the case above, there is no read or write interest and both filters are disabled. Thus, no event will ever make it to the handler.

This really boils down to the fact that epoll treats hup as a separate event and kqueue treats hup as part of read/write.

**Comment by hjr3** [comment]
See https://github.com/carllerche/mio/blob/629141abde2b8bafcd5f89e67a9e426f442983c6/src/sys/unix/kqueue.rs#L41 and https://github.com/carllerche/mio/blob/629141abde2b8bafcd5f89e67a9e426f442983c6/src/sys/unix/kqueue.rs#L63 for relevant source code sections.

**Comment by carllerche** [comment]
I think the right way is to require read or write interest in the cross platform API. So, w/o importing OS specific extensions, it should be impossible to register hup interest w/o read or write.

**Comment by carllerche** [comment]
Fixed on `dev` by adding a check for readable or writable in the interest set.
