### ISSUE TITLE
windows: Use a global completion port by default

### ISSUE THREAD

**Issue by alexcrichton** [carllerche/mio#242]
One part about mio is that you can register an I/O handle with multiple event loops, and event loops can also migrate between threads. On Windows, however, an I/O handle can be associated with at most one completion port and that completion port is tough to move between threads. To emulate the same semantics as other platforms, Windows should have a global event loop.

Whenever the first event loop is spun up it should spawn a global background worker thread which all event loops then communicate with. "Registering with an event loop" is then just making sure the handle is on the global completion port. Communication between event loops and the global event loop would then happen to negotiate events.

There should also be an option to **not** use a global event loop and instead opt-in to using a local completion port. This should probably be a windows-specific extension trait.

**Comment by carllerche** [comment]
It's been decided that we will not use a global event loop on windows in favor of #308
