### ISSUE TITLE
windows: Benchmark performance

### ISSUE THREAD

**Issue by alexcrichton** [carllerche/mio#246]
Right now the Windows implementation is not up to par in terms of performance with Unix, as there are many opportunities for improvement. The implementation should be benchmarked in terms of actual I/O throughput numbers and there should be a better handle on where exactly performance needs to be improved.

**Comment by alexcrichton** [comment]
@carllerche had the excellent idea of benchmarking against libuv, would be good to get at least *some* comparison numbers!

**Comment by carllerche** [comment]
This would still be nice, but I"m going to close this due to inactivity. Maybe we could have a "wish list" wikipage to track these longer term wants?
