### ISSUE TITLE
Make Selector fully private

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#250]
Currently, `Selector` is only public in order to support the `Evented` trait which exposes the type as part of it's API. It should be possible to fix this.

**Comment by reem** [comment]
Just to make sure - do you plan to have outside types able to implement `Evented`? I've implemented `Evented` for a few types in other crates, but I could also work around it if it became impossible.

**Comment by carllerche** [comment]
It should be plausible to make it private and let you implement `Evented` as long as you can proxy the call to some other `Evented` type that you own.

**Comment by reem** [comment]
The implementation (all methods) can be private, but the type itself has to be exposed if it's part of the method signatures on `Evented`.

**Comment by nixpulvis** [comment]
Related see #319.

**Comment by carllerche** [comment]
The strategy here will be to have `Evented` take an `EventLoop` reference vs. a `Selector` reference. Internal to Mio implementations of `Evented` will be able to access the selector via `EventLoop`, implementations external to Mio can proxy to other `Evented` types.

**Comment by carllerche** [comment]
Fixed on master
