### ISSUE TITLE
windows: provide a mechanism for handling RawSockets

### ISSUE THREAD

**Issue by dimbleby** [carllerche/mio#252]
By analogy with #226 and the `EventedFd`, presumably an `EventedSocket` would be the way to go.

If this were very straightforward I'd submit a pull request.  But implementing `Evented` looks to be a lot more complicated on Windows and I don't really grok what's required.

**Comment by alexcrichton** [comment]
This is certainly much more tricky I think as the event loop is going to basically always have to make some sort of assumption about what it can do once it receives a completion notification. For example it currently means that some previously-registered callback should be invoked to generate some notifications to be delivered to `Handler::ready`.

I'm not 100% sure how many use cases there are for custom handles on a completion port (beyond those that should be in mio by default of course), so we may want to wait for the space to play out for a bit before designing around this. It may end up just being one or two extension methods on an event loop, but for now it's certainly more involved enough than Unix that it's not easy to "just implement"

**Comment by dimbleby** [comment]
Maybe it'll be helpful to know about my use case.  I'm writing a Rust wrapper around the c-ares library.  The library tells you what file descriptors / sockets it cares about, and you tell it when something happens. Clearly a good fit for an event loop (though meanwhile I should be able to get by with `select` or `WSAPoll`).

Waiting to see whether anyone else cares, and why, and how the mio code develops, and so on is fine by me.

**Comment by alexcrichton** [comment]
Hm interesting! Could you explain to me a bit how it's supposed to work in c-ares? For example does c-ares submit I/O to the socket for you, and then you let it know when it finished? (does c-ares have internal buffer management?).

e.g., if you were to write with c-ares using IOCP manually, what would it look like?

**Comment by dimbleby** [comment]
Well, I know more about c-ares than about IOCP.

c-ares goes something like this:
- user calls `ares_query()`
- while in this call c-ares opens a socket, and calls `send()` and `recv()` as required
- on getting `EAGAIN` / `EWOULDBLOCK`, c-ares tells the user to watch the socket
- user can be told what's interesting through a callback.  Or instead of using this callback the user can explicitly ask c-ares which sockets should be watched, with either `ares_getsock()` or `ares_fds()`
- user is then expected to call either `ares_process()` or `ares_process_fd()` when it has news about socket readiness, at which point c-ares retries `send()` / `recv()` and we go around the loop again

I believe that the code was originally written with the expectation that the user would `select()` for socket readiness and has since evolved to support more efficient (Unix-style) event loops eg `poll()` / `epoll()` - which probably explains why there are two or three interface choices in each of the the last two steps.

I've never written any IOCP code, so I can't say much about that.  It may even be that it's not possible to integrate an IOCP event loop with requests made by plain old `send()` / `recv()`?!

My impression is that eg libuv does manage to achieve this, but I could be wrong. [Here](https://github.com/saghul/pycares/blob/master/examples/cares-resolver.py) is an integration of the python wrapper of c-ares with the python wrapper of libuv, which is admittedly pretty indirect evidence of integration with IOCP - I may be just wrong in believing that libuv uses IOCP here.

I guess an alternative approach for mio would be to support an event loop backed by either `WSAPoll()` or `select()`.  It's understood that these approaches don't scale to large numbers of sockets, but that's not always a problem.  Eg I'd expect it to be fine for c-ares users; c-ares shouldn't be talking to more than a handful of servers therefore won't need more than a handful of sockets.

**Comment by alexcrichton** [comment]
Hm ok, so I think that basically as-is `c-ares` can't be used with IOCP. This would require c-ares to actually execute the I/O and then ask you to tell it when the I/O completes, rather than the other way around (requesting you tell it when I/O *can* be completed). I believe that Python wrapper is just falling back to polling (e.g. the functions you found), so I don't believe it's using IOCP. That being said I'm not entirely sure how libuv would merge `WSAPool` and IOCP event loops...

I think something like this on Windows could certainly be supported for **only** sockets via the normal `select` and `WSAPoll` APIs, but it'd need some thought to figure out how to merge these event loops (perhaps it's just a worker thread)

**Comment by trlim** [comment]
There is a [list](https://msdn.microsoft.com/ko-kr/library/windows/desktop/aa365198(v=vs.85).aspx) of I/O operations that complete with IOCP.

When communicating with (custom) device driver, `ReadFile`, `WriteFile` and `DeviceIoControl` are used a lot. `WaitCommEvent` can also be used if the device is serial port.

**Comment by carllerche** [comment]
I think that it would be valuable to consider this case when considering a more windows specific API but this will be post 1.0. I will flag it as such.

**Comment by alexcrichton** [comment]
Windows is actually in a relatively good position for handling this at this point. With the `Registration` and `SetReadiness` types it's easy to integrate I/O readiness from any object into the mio event loop. 

The [completion status](http://alexcrichton.com/miow/miow/iocp/struct.CompletionStatus.html) that we get from IOCP gives the event loop two ways to configure it, the token and the overlapped pointer. Unlike Unix we don't know how to translate that to read/write readiness events, so we have to run some form of callback to actually handle the event that finished to figure out what to do. 

Right now we do a "clever trick" where the [overlapped structure used internally](https://github.com/carllerche/mio/blob/4184a9d69be927e58ebf3fcc4ce2635c6ed9583e/src/sys/windows/selector.rs#L346-L358) ubiquitously contains a function pointer just after the `OVERLAPPED` structure. This means that the pointer we get from IOCP we just cast to one of those instances, and then we call the function pointer on the completion status we just got. This is all pretty unsafe, but also a very small API commitment and flexible enough to implement TCP/UDP at least. I could imagine something like:

```
pub struct EventedHandle<'a> {
    inner: &'a HANDLE,
}

impl<'a> EventedHandle<'a> {
    // Unsafe because IOCP is super unsafe in general.
    pub unsafe fn new(handle: &'a HANDLE) -> EventedHandle<'a> {
        // ...
    }
}

impl<'a> Evented for EventedHandle<'a> {
    // ...
}
```

Then after that all I/O would just have to be done with the [custom overlapped structure](https://github.com/carllerche/mio/blob/4184a9d69be927e58ebf3fcc4ce2635c6ed9583e/src/sys/windows/selector.rs#L346-L358) (hence the unsafety of the constructor). We may have to expose one or two other fiddly bits, but overall it *should* be pretty similar to Unix I think!

**Comment by alexcrichton** [comment]
I've got a sample implementation of this (different than what I last mentioned) at https://github.com/carllerche/mio/pull/504, comments would be welcome!

**Comment by dimbleby** [comment]
I've only skimmed over that code - there's quite a lot of it and I suspect it would take me a while to get to grips with it!  But I don't immediately see how it deals with the particular use case that I had in mind when I raised this issue.

Reminder: 

* `c-ares` calls `socket()`, and instructs me "I'd like you to tell me about events on this file descriptor / raw socket".  
* I'd like to be able to fulfil that instruction via `mio`.  

That's easy on unix because file descriptors are `Evented`, but not currently possible on windows.

Does #504 make this possible?  Is it easy?!

**Comment by alexcrichton** [comment]
@dimbleby ah so for integration with `c-ares`, which I imagine is very similar if not the same as libcurl (by the same author), is impossible to do with mio. Fundamentally mio uses IOCP, whereas libcurl (and I assume c-ares) desires notifications of readiness. The mio library will perform I/O on your behalf, whereas libcurl expects to do all I/O itself.

You can see an example of working across Unix/Windows with libcurl at https://github.com/tokio-rs/tokio-curl. It basically boils down to a worker thread for Windows whereas Unix can integrate with the main event loop.

So in that sense, if you want *readiness* of a socket on Windows without performing I/O, I think that mio is very unlikely to ever support.

**Comment by alexcrichton** [comment]
Looks like this wasn't fixed in #504

**Comment by dimbleby** [comment]
@alexcrichton thanks, I have much the same windows / not-windows split in https://github.com/dimbleby/c-ares-resolver (which is basically the `c-ares` wrapper integrated with an event loop).

As we discussed much earlier in this thread, it would be possible for `mio` to fall back to a worker thread for just this case.  While that would be kinda desirable I think, I'm neither planning on contributing this myself nor holding my breath on anyone else doing so.  If and when `mio` maintainers decide this is never going to happen, I expect you should just close this one out.

**Comment by alexcrichton** [comment]
@dimbleby ah ok, if the worker thread approach is the one you'd think of taking, I suspect that probably won't make its way to mio itself. Something like that can definitely be built outside of the mio crate itself (e.g. the tokio-curl crate I linked) and should be easily integrate-able with the `Readiness` and `SetReadiness` structures in mio today.

**Comment by alexcrichton** [comment]
(in that case I'm going to close)
