### ISSUE TITLE
Could notification channels not fail?

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#272]
I find it inconvenient that `Sender::send()` can fail.

I understand the reason of `NotifyError::Closed`, but could other error conditions be eliminated? I would rather have a slower notification, than notifications that can randomly fail. Especially `Notify::Full` seems inconvenient - it's random in nature, and in some applications there's nothing reasonable to do about it (other than spin?). Maybe at least a variant of `Sender::send()` that implements spinning on `Full` queue would be a good idea?

Also, could there be a notification mechanism that does not send any data, and only causes EventLoop to run some method? This way user could implement any queue they want, with performance and behavior that they need.

**Comment by arthurprs** [comment]
This relates to the zero allocation nature of MIO so the notification buffer is fixed and preallocated (the best option in my opinion). Nothing against plug-in implementations though.

**Comment by tailhook** [comment]
> Maybe at least a variant of Sender::send() that implements spinning on Full queue would be a good idea?

The problem with spinning implementation is sending from the same thread may block indefinitely. However, may be okay if it's a variant.

**Comment by carllerche** [comment]
As mentioned, the array queue is required to support Mio's zero allocation at runtime goal.

Two things though, it wouldn't be too hard for the user to handle a full queue as desired (in this case, you want to block). This could be done as a smallish bit of code wrapping Mio's notify queue. Secondly, there have been some superficial discussions w/ @alexcrichton about whether or not the notify queue could be made pluggable, which could allow a linked queue to be used instead (which will only fail when you run out of memory).

I'm going to close this for now, feel free to reopen if I missed something or create a new ticket.
