### ISSUE TITLE
Method to get error when EventSet.is_error

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/mio#279]
With libc, one could call getsockopt with SO_ERROR to look up the actual error. Source: http://stackoverflow.com/questions/13150377/how-to-get-errno-when-epoll-wait-returns-epollerr

It would be convenient to provide a method to get this error easily.

**Comment by housleyjk** [comment]
+1

For `TcpStream` we used to be able to get the error with `take_socket_error()`. Guidance for how to get the underlying error in version 5 would be helpful for reporting.
