### ISSUE TITLE
windows: use readiness API NtDeviceIoControl IOCTL_AFD_POLL instead of scheduling I/O

### ISSUE THREAD

**Issue by luca-barbieri** [carllerche/mio#281]
Windows apparently has a readiness API in the form of NtDeviceIoControl with the IOCTL_AFD_POLL ioctl that should allow to implement a readiness model just like epoll along with nonblocking sockets, with notifications being sent to I/O completion ports.

The API is not documented, but there are several sample implementations that can be found on the Internet based on it, such as the ones on https://github.com/piscisaureus/forigor/blob/master/epoll.c and https://github.com/piscisaureus/epoll_windows/blob/master/src/epoll.c (the latter implementing the Linux epoll API on top of it).

Libuv uses it to implement uv_poll, as can be seen from https://github.com/libuv/libuv/blob/master/src/win/poll.c (this is written by the same author as the above code, @piscisaureus, and seems to be a more advanced implementation).

It seems it only works for sockets implemented by the MSAFD WinSock provider, which seem to be TCP, UDP and NetBios sockets, but it looks like that it is possible for other layers to be on top (perhaps things like antivirus software?) and that in XP/2k3 that makes it impossible to get the MSAFD socket. Libuv seems to fall back to calling select() on a thread if the MSAFD interface is not available.

Assuming it works, it seems it could be a better option than the current implementation.

**Comment by carllerche** [comment]
Thanks for linking this. I have seen this strategy in the past, but haven't had the time to investigate in more detail how plausible it is for MIO. There are a few reasons why it isn't an obviously good strategy.

* It is undocumented, which is a negative.
* It doesn't support named sockets I believe, which Mio should support.
* The IOCP strategy that Mio is currently using is definitely much faster than one built on select
* Mio will in the future offer windows specific extensions that bring the API closer to IOCP
* The actual performance of this strategy vs. ours is not determined.

If we are going to consider this strategy, it would have to be demonstrated that it is a clear performance win. Would you be interested in trying to write some benchmarks comparing the two strategies?

**Comment by carllerche** [comment]
I'm going to stick w/ the current strategy for now because there are plans for expanding the Mio API to bridge the gap further between the IOCP model and epoll. If this turns out to not pan out, we can reopen/recreate this issue.
