### ISSUE TITLE
`UdpSocket` does not implement `TryRead`.

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#282]
I'll submit PR to fix it when I have time unless someone does it first.

**Comment by alexcrichton** [comment]
This is currently because UDP sockets provide more data whenever a read completes (e.g. where the data came from), so it's not a perfect fit for the trait.

**Comment by dpc** [comment]
Should the trait have an associated type for it's result?

**Comment by carllerche** [comment]
I don't think that it makes sense for UDP to implement `TryRead`.
