### ISSUE TITLE
set_keepalive reports EINVAL on Linux

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#287]
Not sure who to be blame, MIO or net2.

Tracking issue: https://github.com/alexcrichton/net2-rs/issues/13

**Comment by alexcrichton** [comment]
I [commented on the net2 issue](https://github.com/alexcrichton/net2-rs/issues/13#issuecomment-144485467) but I believe that the error here is Linux isn't able to set a 300s keepalive timeout, but it should be able to handle a 300ms timeout!
