### ISSUE TITLE
Unnecessary polling

### ISSUE THREAD

**Issue by sp3d** [carllerche/mio#289]
This code which connects to and reads from a unix socket at `/tmp/socket` contains nothing that would require periodic wakeups, but strace shows it passing a timeout of 199ms or so to repeated calls to `epoll_wait`:
```
extern crate mio;

use std::path::Path;
use mio::{EventLoop, Handler, Token, EventSet};

struct E;

impl Handler for E {
	type Timeout = ();
	type Message = ();
}

fn main() {
	let mut e = EventLoop::<E>::new().unwrap();

	let addr = Path::new("/tmp/socket");

	let server = mio::unix::UnixStream::connect(addr).unwrap();
	e.register(&server, Token(2), EventSet::all(), mio::PollOpt::edge()).unwrap();
	e.run(&mut E).unwrap();
}
```
(To test, run `rm -f /tmp/socket; ncat -l -U /tmp/socket` in a terminal first.)

It would be much better for battery life if mio passed the maximum possible timeout to epoll_wait based on registered timers and actual timeouts requested by operations. In general mio should get this right for users because avoiding polling is one of the primary reasons to use an event-loop lib.

**Comment by dwrensha** [comment]
See also #280, which proposes to make the default timeout be "infinity".
