### ISSUE TITLE
Polling does not work on ARM

### ISSUE THREAD

**Issue by operutka** [carllerche/mio#311]
Currently, mio does not work on ARM and possibly also on other architectures because of incorrect packing of the EpollEvent structure in nix. It has been already fixed here:

https://github.com/carllerche/nix-rust/commit/c6cad77d10836f12ecda7bee5fb7a57ee6ea4f89

but mio still uses the old nix 0.3.9. Are there any plans on releasing a new version of mio based on nix >= 0.4.1?

**Comment by operutka** [comment]
I was talking about the latest release on crates.io. Releasing v0.5 this week sounds great! We're about to release our application on GitHub by the end of this month and I don't want a git commit dependency in the stable release.

**Comment by carllerche** [comment]
I'm going to close this for now. You can track what is left here: https://github.com/carllerche/mio/milestones/v0.5.0
