### ISSUE TITLE
`tick()` not being called after update to 0.5

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#316]

**Comment by dpc** [comment]
My current test is wrong, and after fixing it, I'm having troubles reproducing the same situation as in my code. Investigating.

**Comment by dpc** [comment]
Funny enough, the "wrong" test was exactly the problem.

In case of lack of events, `EventLoop::run()` will just run, as no timeout is being used.

**Comment by dpc** [comment]
I've updated the PR according to previous irc chat.

**Comment by lcy03406** [comment]
I don't think it's a problem. If you want to tick the loop periodically, you can register a timer on it.
But the name 'tick()' is somewhat misleading, consider rename it to 'turn()' or something?

**Comment by dpc** [comment]
The workaround (use own loop calling run_once) worked for me.
