### ISSUE TITLE
Evented Trait Docs are Hidden

### ISSUE THREAD

**Issue by nixpulvis** [carllerche/mio#319]
I'm not sure why, but it makes implementing `Evented` require reading the source code. Also makes me feel like I'm doing something "wrong".

**Comment by carllerche** [comment]
Yep, good call. This will be handled as part of the API stabilization pass.

**Comment by carllerche** [comment]
It seems like publishing docs may be broken.

**Comment by carllerche** [comment]
Closing this issue, doc is being tracked by #433
