### ISSUE TITLE
Support pipes on windows

### ISSUE THREAD

**Issue by canndrew** [carllerche/mio#320]
Windows offers functionality almost identical to `unix::pipe()`, `PipeReader`, `PipeWriter`. It would be great if there were cross-platform versions of these.

**Comment by carllerche** [comment]
This is going to require more research into exactly how windows pipes work compared to unix pipes. There are a lot of tricky details, like anonymous pipes on windows can't be used with IOCP, etc... A first pass may be to expose named pipes in a windows specific extension. Either way, I will punt this until after 1.0

**Comment by alexchandel** [comment]
This would be nice, since named pipes work with IOCP. It's worth noting that files work with IOCP too, and with kqueue & epoll. Anonymous pipes and "console handles" will probably require special treatment for windows.

**Comment by mmacedoeu** [comment]
:+1:

**Comment by dpc** [comment]
@Drakulix: Worth following, as it might be better than fakes pipes that we have right now in mioco.

**Comment by alexchandel** [comment]
This may fit with #360's unification.

**Comment by carllerche** [comment]
In general, features that are officially supported on windows via IOCP (like files, named pipes, etc...) can be exposed on windows w/o worrying about a cross platform unification. This would allow third party libs to take a stab at a unified API.

**Comment by alexchandel** [comment]
@carlierche my impression is that third-party libs (e.g. [capnp-rpc-rust](https://github.com/dwrensha/capnp-rpc-rust), [capnp-gj](https://github.com/dwrensha/capnp-gj), [gj](https://github.com/dwrensha/gj)) rely on mio to do their platform unification. This makes sense to me. There's no point using mio to deal with different platforms' differing nonblocking-io APIs if mio doesn't actually do that, and you *still* have to worry about interplatform differences.

**Comment by alexchandel** [comment]
### Update:

While reading the Windows Console (i.e. stdin from a cmd prompt) non-blocking line-based fashion **while still echoing & supporting arrowkeys/backspace** is impossible without a second thread,

reading from **named** pipes should work analogous to reading from sockets.

**Comment by alexcrichton** [comment]
Oh as an update, I've got some WIP support to get named pipes working with mio:

* [Mio support](https://github.com/alexcrichton/mio/commit/cdef4f84e34a8d8f0271d85367686b773be91940)
* [Example bindings](https://github.com/alexcrichton/mio-named-pipes)

It's likely not working currently and currently my goal is to work towards https://github.com/alexcrichton/tokio-process/issues/2

**Comment by alexcrichton** [comment]
Ok I've posted a [PR](https://github.com/carllerche/mio/pull/504) for custom handle registration and the [`mio-named-pipes` crate](https://github.com/alexcrichton/mio-named-pipes) seems to have rudimentary tests passing at least (for bindings to named pipes).

**Comment by alexcrichton** [comment]
For posterity, this support is now available through the [`mio-named-pipes`](https://crates.io/crates/mio-named-pipes) crate.

**Comment by blabaere** [comment]
Great, with the help of AppVeyor, the next version of nanomsg will support the ipc transport on Windows too. Thanks !
