### ISSUE TITLE
Growable notify queue as an option / feature.

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#322]
I know mio by default does not allocate, but I really need grow-able queues. When the queue is full, there's nothing good to do about it. If I spin I get deadlocks (like https://github.com/dpc/mioco/issues/69), if I don't I need to introduce a grow-able queue manually anyway.

How about we make a growable queue a Cargo feature or option in `EventLoopConfig`? I'm thinking about taking one of crossbeam queues:

http://aturon.github.io/crossbeam-doc/crossbeam/sync/index.html

Will such a PR be accepted? Any other ideas?

**Comment by arthurprs** [comment]
May I suggest you to take the MIO queue implementation and benchmark it against crossbeam? Crossbeam itself already has an mpsc benchmark implementation.

It may shed some light into this.

**Comment by dpc** [comment]
I could but I don't care about speed really. Only about making the queue growable.

**Comment by arthurprs** [comment]
Well, I assume any alternatives must be performant in order to be merged upstream.

My current [pet project](https://github.com/arthurprs/floki) is notify heavy, for example.

**Comment by dpc** [comment]
It won't be a total switch because mio does not allocate during runtime. Growing is allocating, thus a total switch to any growable queue is no-no. I'm sure most users are perfectly fine with current queue, so I'm looking for a way to just opt-out to a growable queue, on demand. Other than growing, I have no requirements. Faster implementation can be provided later if the one I've proposed turns out to be not enough.

**Comment by arthurprs** [comment]
I went ahead and modified crossbeam tests to use 24 byte messages, results bellow (in ns, so smaller is better)

```1 Threads
mpsc mpsc: 57.2908633
Seg mpsc: 102.8092363
bounded mpmc: 28.5960358
2 Threads
mpsc mpsc: 70.08888965
Seg mpsc: 83.1784077
bounded mpmc: 97.38312855
3 Threads
mpsc mpsc: 69.12842666666667
Seg mpsc: 57.32806733333334
bounded mpmc: 111.13411283333333
4 Threads
mpsc mpsc: 66.938316525
Seg mpsc: 51.626926525
bounded mpmc: 125.61349105
```

Code is here: https://github.com/arthurprs/crossbeam

I think it's safe to say that 99.9% of MIO notify producers are not busy loops like this benchmark. So the current implementation is indeed the best choice since it's really efficient at low levels of contention.

If you can get it to reallocate safely with little overhead it'd be a nice addition.

**Comment by arthurprs** [comment]
Adding a little bit of work (atomic increment a counter 20 times) between pushes I get 

```
1 Threads
mpsc mpsc: 248.952823
Seg mpsc: 240.2846536
bounded mpsc: 217.0402997
2 Threads
mpsc mpsc: 151.00095085
Seg mpsc: 143.70620145
bounded mpsc: 162.57680625
3 Threads
mpsc mpsc: 147.77742146666668
Seg mpsc: 101.88968686666666
bounded mpsc: 126.13010226666667
4 Threads
mpsc mpsc: 91.335810275
Seg mpsc: 106.21642755
bounded mpsc: 110.363010425
```

The pattern holds, the bounded queue starts ahead and falls behind when there's increased contention but the margin is very small.

**Comment by dpc** [comment]
Interesting and good to know. 

> If you can get it to reallocate safely with little overhead

My impression was that nothing special has to be done for it to grow.

**Comment by arthurprs** [comment]
@dpc I'm afraid it's not that simple

**Comment by dpc** [comment]
The API has only `new`, `pop` and `push`... http://aturon.github.io/crossbeam-doc/crossbeam/sync/struct.SegQueue.html what am I missing?

**Comment by arthurprs** [comment]
Oh, I see. I thought you wanted to make the current queue implementation growable.

**Comment by carllerche** [comment]
I have been discussing a strategy with @aturon and @alexcrichton related to this. We are going to attempt to remove a hard coded queue in favor of some sort of notification gate (similar to thread park / unpark). This will allow the queue to be pluggable.

**Comment by dpc** [comment]
Great. I'll wait then.

**Comment by carllerche** [comment]
This has been fixed by allowing arbitrary queues.
