### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by Tzendos** [carllerche/mio#323]
Please, update example for version 0.5!
https://github.com/carllerche/mio/tree/getting-started/examples/ping_pong

**Comment by carllerche** [comment]
Yep! Definitely will have to do this. Thanks

**Comment by ereichert** [comment]
I've done this.  However, I'm working on updating the getting started guide as well.  I'll submit a pull request when I'm done.

You can see my progress at https://github.com/ereichert/mio/tree/getting-started.

**Comment by carllerche** [comment]
Thanks. Tracking doc issues here now: #323 I'll checkout the PR soon.
