### ISSUE TITLE
Consider renaming `EventLoop` -> `Loop`

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#330]
A more concise name seems nicer. This would also mean renaming `EventLoopBuilder` -> `LoopBuilder`.

**Comment by fhartwig** [comment]
I prefer `EventLoop`. It's a bit longer than just `Loop`, but it's not that long and in my experience it doesn't appear often enough in any program to be worth optimising. I think that `EventLoop` is a bit clearer, and in my opinion that outweighs the benefits of a few saved characters.

**Comment by danburkert** [comment]
> I prefer EventLoop. It's a bit longer than just Loop, but it's not that long and in my experience it doesn't appear often enough in any program to be worth optimising. I think that EventLoop is a bit clearer, and in my opinion that outweighs the benefits of a few saved characters.

I agree with this sentiment.

**Comment by fenduru** [comment]
Seems a little odd given the `loop` language feature

**Comment by hjr3** [comment]
I prefer `EventLoop`.

**Comment by billmurphy5th** [comment]
I prefer EventLoop as well since the loop keyword is already part of the language.

**Comment by carllerche** [comment]
Relates to #360: `EventLoop` may go away.

**Comment by carllerche** [comment]
`EventLoop` will go away, this issue is no longer relevant.
