### ISSUE TITLE
Infrequent bug with rapid write reregistering on Windows

### ISSUE THREAD

**Issue by Furyhunter** [carllerche/mio#342]
Very infrequently, when reregistering a socket with the `writable()` event multiple times in quick succession, mio will silently break, leaving the socket entirely unregistered, even with `hup()`. This is specifically for `edge() | oneshot()` options. In my code, I have the following setup which is triggering this bug:

1. The Mio event loop is used to parse and dispatch messages from each connected client to various actor threads via their `std::sync::mpsc` sender handles. Each actor thread represents a different service which clients are exclusively connected to from the others.
2. When actor threads want to send messages to clients, they use their clone of the Mio Sender and wrap the client message structure in the Mio `Message` associated enum. The loop awakens on this, appending the message to the message write queue for the associated socket, and reregistering the socket for the `writable` event. _I think this may be where it's encountering a problem -- my code always reregisters, regardless of whether or not it actually needs to. It happens when several messages are sent by the server almost instantly._
3. On `writable`, the socket runs a state machine that pops a message off the queue, serializes the message to a byte buffer, then continuously writes the bytes when the socket is available.

A reregister will fail occaisionally, leaving the socket in limbo and failing to dispatch disconnect messages to the actor the client was connected to (no `hup` event).

Upon further inspection, it seems like the entire loop stops polling for events on all registered event sources.

**Comment by alexcrichton** [comment]
Do you have some example code that could perhaps be poked around with a bit?

**Comment by Furyhunter** [comment]
I can share my server code, but in order to test it you'd have to download a game client and play a bit. Bit of a non-trivial setup procedure for it, too.

[Here is the client socket handler that is causing the breakage.](http://git.idolagames.com/furyhunter/idolapsoserv/src/cd753ece49621238d32c30b498e228459d176e87/src/services/client/bb.rs) If you want to run the code, I could give instructions and links, but it's not totally copyright friendly so I'd rather avoid linking it all here if possible.

**Comment by carllerche** [comment]
A bunch of fixes for windows bugs just landed on master. I believe that this should be fixed as well. I'm going to close this for now. If you find that master does not fix the bug, please open a new issue and link to this one for context. Thanks for the report!
