### ISSUE TITLE
the trait `bytes::buf::Buf` is not implemented for the type `bytes::buf::byte::ByteBuf`

### ISSUE THREAD

**Issue by siddontang** [carllerche/mio#344]
Hi

In my project, I use mio 0.5 and the latest bytes like the doc says:
```
[dependencies.bytes]
git = "https://github.com/carllerche/bytes"
```

When I write following code, it can't compile.
```
let mut buf = ByteBuf::mut_with_capacity(100).flip();
sock.try_write_buf(&mut buf);
```

If I use bytes 0.3 directly, it can compile. 

Should I use bytes 0.3 when I use mio at same time? or the bytes doc should annotate this error? it may mislead some users too.

**Comment by carllerche** [comment]
Thanks for the report. I plan to update the docs to remove references to the bytes crate (and instead use [u8] directly). Using Bytes will be "unstable" for now as I don't have time to get it to the point needed to be part of Mio 1.0.

If there are missing implementations in the bytes crate, it would probably be best to submit the issue (and / or PR) to the repo github.com/carllerche/bytes

Thanks.

**Comment by siddontang** [comment]
Thank you, now I use bytes and call mio try_read/write directly, it is ok. 
Hope Mio 1.0 :-)

**Comment by carllerche** [comment]
Don't worry, it will still be useable in Mio 1.0 if you opt-in. I just won't guarantee that the API will remain stable.
