### ISSUE TITLE
Consider implement *Ext traits in net2

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#346]
I noticed that `TcpStream`, `TcpListener` and `UdpSocket` haven't implemented `TcpStreamExt`, `TcpListenerExt` and `UdpSocketExt` in `net2` crate.

**Comment by alexcrichton** [comment]
Note that extension traits in general are intended to not be implement across crates (as they'll likely grow in the future). Instead the raw underlying types should be exposed or the functionality should be reexported.

**Comment by carllerche** [comment]
As per @alexcrichton, there isn't any action to take at this time.

Thanks for the report though!
