### ISSUE TITLE
Add a function to retrieve the maximum number of open connections possible

### ISSUE THREAD

**Issue by jamperry** [carllerche/mio#348]
I'm writing an application framework (built on top of mio to build servers rapidly similar to frameworks like Python's tornado, C++'s wangle, Scala's finagle, etc.) and I have written a function in my framework with the below signature to get the maximum limit of open connections using `getrlimit(2)`:

`fn max_conn_limit() -> usize`

Would you like it in mio? It will work for *nix but not windows. 

I believe this will be really useful for users of mio. They can then preallocate a slab of open connections (preferably using `i32` to represent file descriptors) to the maximum number of open file descriptors that the underlying process can possibly open. This is a good performance optimization as it significantly minimizes the bookkeeping overhead and fragmentation of `malloc`. It's also useful for monitoring purposes; know how many open connections are left available, etc.

**Comment by carllerche** [comment]
Hey James.

It definitely looks like a useful helper fn. I would recommend keeping it in a different crate for two reasons. I am currently trying to slim down Mio somewhat to keep it "minimal" & as portable as possible. I  wonder if this could eventually be in the nix crate... though that crate is in some dire need of cleanup.

PS: do you have your app framework up somewhere yet?

**Comment by jamperry** [comment]
Hey Carl,

I understand so I've put it in a crate [here](https://crates.io/crates/file_limit/). 

The code for the framework is not ready to be published as I need to remove propriety code out of it and clean up several parts. However I will put the code [here](https://github.com/jamperry/valve) and, in the meantime, I've added a brief description of the architecture in the README.
