### ISSUE TITLE
 the trait `std::error::Error` is not implemented for the type `mio::timer::TimerError`

### ISSUE THREAD

**Issue by siddontang** [carllerche/mio#349]
Hi @carllerche 

I notice that TimerError only implements `description` function for Error trait, no `cause` function, which is not convenient to use `try!` with timeout_ms directly. 

Is it any reason to ignore `cause` function here? 

Thank you.

**Comment by carllerche** [comment]
I'm not sure what you mean. `TimerError` isn't triggered by another error, so what would `cause()` return?

**Comment by siddontang** [comment]
`cause` can return None, means no error causes this.

**Comment by carllerche** [comment]
That's what the default implementation does. So, by omitting a specific implementation, I am opting into the default, which just returns `None`.
