### ISSUE TITLE
When is it safe to clear a timeout?

### ISSUE THREAD

**Issue by tailhook** [carllerche/mio#358]
While timeout is just a Token I know that it's memory-safe to clear timeout at any time. But because it looks for the token in the Slab I wonder whether clearing a timeout could remove another timeout. In particular:

1. Is it safe to clear a timeout after timeout is processed?
2. Is it safe to clear a timeout while it's pending but not yet processed?

**Comment by tailhook** [comment]
And the followup question about timers:

Is there a limit on the maximum milliseconds that may be specified in `timeout_ms`? (usually timer wheel implementations have the limit, AFAIK) This is not documented either.

**Comment by carllerche** [comment]
The goal was to make it always safe. However, I believe looking through the code that there may be a potential race condition that should be investigated.

So, to answer the questions.

> Is it safe to clear a timeout after timeout is processed?

In theory it should be, but there may be an issue around this. I need to double check.

> Is it safe to clear a timeout while it's pending but not yet processed?

Yes

> Is there a limit on the maximum milliseconds that may be specified in timeout_ms?

I don't think so, I believe that it is capped to max `u64` though.

The answers to these questions should be documented.

**Comment by tmiasko** [comment]
> Is it safe to clear a timeout after timeout is processed?

Currently Timer::cancel_timeout will cancel a timeout only if both token and a
tick match, so a race condition is possible, although unlikely.

**Comment by carllerche** [comment]
Thanks for the report. I am aggregating doc issues into #358. Closing this one for now.
