### ISSUE TITLE
mio's non-blocking IO types should have methods for converting them to their blocking std::net counterparts

### ISSUE THREAD

**Issue by canndrew** [carllerche/mio#362]
For example, I have a `mio::tcp::TcpStream` which I'd like to convert to a `std::net::TcpStream`. It would be useful if `mio::tcp::TcpStream` had a `into_blocking()` method or something of the sort.

**Comment by carllerche** [comment]
Thanks for the report.

There is no portable way to do this due to windows. On *nix systems, you can go via `RawFd`. Due to the portability issue, there will not be a conversion function on mio's TCP types.
