### ISSUE TITLE
Issues building on ARM platform

### ISSUE THREAD

**Issue by ijohanne** [carllerche/mio#375]
I'm trying to build parity (ethereum client written in rust) on a Raspberry Pi using rustc 1.7.0-a5d1e7a59 (stable). First problem was seeing that mio depends on nix prior to 0.5.0, which has been fixed and now compiles properly on ARM using rustc 1.7.0.

So I attempted to checkout the source for mio from git, and bump the dependency on nix manually to 0.5.0. 

This does fix it, but now the same build error occurs in mio (same as in same errors shown on nix before 0.5.0):
```
   Compiling mio v0.5.0 (file:///usr/src/mio)
src/sys/unix/uds.rs:53:86: 53:87 error: mismatched types:
 expected `nix::sys::socket::consts::os::MsgFlags`,
    found `_`
(expected struct `nix::sys::socket::consts::os::MsgFlags`,
    found integral variable) [E0308]
src/sys/unix/uds.rs:53         let msg = try!(nix::recvmsg(self.io.as_raw_fd(), &iov, Some(&mut cmsgspace), 0)
                                                                                                            ^
src/sys/unix/uds.rs:53:19: 54:60 note: in this expansion of try! (defined in <std macros>)
src/sys/unix/uds.rs:53:86: 53:87 help: run `rustc --explain E0308` to see a detailed explanation
src/sys/unix/uds.rs:72:57: 72:58 error: mismatched types:
 expected `nix::sys::socket::consts::os::MsgFlags`,
    found `_`
(expected struct `nix::sys::socket::consts::os::MsgFlags`,
    found integral variable) [E0308]
src/sys/unix/uds.rs:72         nix::sendmsg(self.io.as_raw_fd(),&iov, &[cmsg], 0, None)
                                                                               ^
src/sys/unix/uds.rs:72:57: 72:58 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
       error Could not compile `mio`.

To learn more, run the command again with --verbose.
```
The description for the error message is as follows.

> This error occurs when the compiler was unable to infer the concrete type of a
> variable. It can occur for several cases, the most common of which is a
> mismatch in the expected type that the compiler inferred for a variable's
> initializing expression, and the actual type explicitly assigned to the
> variable.
> 
> For example:
> 
> ```
> let x: i32 = "I am not a number!";
> //     ~~~   ~~~~~~~~~~~~~~~~~~~~
> //      |             |
> //      |    initializing expression;
> //      |    compiler infers type `&str`
> //      |
> //    type `i32` assigned to variable `x`
> ```
> 
> Another situation in which this occurs is when you attempt to use the `try!`
> macro inside a function that does not return a `Result<T, E>`:
> 
> ```
> use std::fs::File;
> 
> fn main() {
>     let mut f = try!(File::create("foo.txt"));
> }
> ```
> 
> This code gives an error like this:
> 
> ```text
> <std macros>:5:8: 6:42 error: mismatched types:
>  expected `()`,
>      found `core::result::Result<_, _>`
>  (expected (),
>      found enum `core::result::Result`) [E0308]
> ```
> 
> `try!` returns a `Result<T, E>`, and so the function must. But `main()` has
> `()` as its return type, hence the error.

I'm not familiar enough with rust to craft a patch, but hope this is not a too horrible thing to track down (really looking forward to trying this client on my Pi).

Br, Ian J.

**Comment by rrichardson** [comment]
@ijohanne  -  is this still an issue?   Mio 0.5.0 depends on Nix 0.5.0 by default and there doesn't appear to be the type mismatch in uds.rs.

**Comment by selfup** [comment]
Looks like you might to do something like this:

```rust
fn some_func() -> io::Result<()> {
    some_code_here;
    Ok(()).unwrap()
}
```
The `Ok (())` contains a `()` type, so if you unwrap the `Ok(())`, you should get `()` as the return type!

**Comment by selfup** [comment]
```rust
use std::io;
use std::fs::File;
use std::path::Path;
use std::io::prelude::*;

fn main() {
    some_function().unwrap();
}

fn some_function() -> io::Result<(())> {
    let foo_path = Path::new("foo.txt");

    let mut buffer = try!(File::create(foo_path));

    let bar_text = String::from("Hello World!");

    try!(buffer.write_all(bar_text.as_bytes()));

    Ok(())
}
```
This will work because the function returns an `io::Result<(())>` which contains the `()` type.

This result `Ok (())` needs to be unwrapped in order to have the function return the `()` inside of `main`.

Hope this helps!

**Comment by carllerche** [comment]
I think this *should* hopefully be fixed on master, so I am going to close this. However, I do not have an ARM setup on which I can test this. I will need help figuring out the issue as, again, I don't have access to an ARM setup.

If anyone depends on mio + ARM, I would appreciate some help setting up CI for arm environments :)
