### ISSUE TITLE
No way to specify interface in join_multicast for UdpSocket

### ISSUE THREAD

**Issue by misuzu** [carllerche/mio#377]
Something like this: https://doc.rust-lang.org/nightly/std/net/struct.UdpSocket.html#method.join_multicast_v6

Mio have only address argument: http://rustdoc.s3-website-us-east-1.amazonaws.com/mio/master/mio/udp/struct.UdpSocket.html#method.join_multicast

**Comment by rrichardson** [comment]
I think the plan is to ditch the locally defined Tcp/Udp sockets and move to Rust's std lib: 
https://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html   This should fix the problem.

**Comment by carllerche** [comment]
This should be possible on master now. Thanks.
