### ISSUE TITLE
UdpSocket: On Windows, never get notified by Readable event

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#378]
This is found in one of our test: https://github.com/zonyitoo/coio-rs/blob/master/tests/echo.rs#L49

Environment: Windows 10 with Rust nightly, ANY ABI

The `EventLoop` itself runs in its own thread, and the `UdpSocket` is created on the other thread. `UdpSocket` is registered to the `EventLoop` with `Readable | Writable`, `Edge` triggered.

We were able to see writable event in the `Handler::ready` but we never saw readable in it.

All tests are passed in OS X and Linux.

**Comment by zonyitoo** [comment]
Cannot reproduce now. Close.

**Comment by alexcrichton** [comment]
@zonyitoo if there's remaining Windows bugs they're likely to be fixed by https://github.com/carllerche/mio/pull/426, could you try with that PR applied?

**Comment by carllerche** [comment]
A bunch of windows bugs were fixed on master. I'm going to close this for now. If you find that the bug still exists, please open a new issue w/ a repro ideally.

Thanks.
