### ISSUE TITLE
TCP server hangs

### ISSUE THREAD

**Issue by flavius** [carllerche/mio#380]
I've just started using this library and I wanted to benchmark it just to see how much it can handle. So I've written a simple server which just accepts connections and closes them immediately.

Then I've tested it with 300 parallel connections with `iperf`:

`iperf -c localhost -p 10000 -P 300 -n 0 -y C -N`

At the first run it usually handles all connections, though the daemon leaves out the last dozen ticks. But mostly the second run of iperf, third run at best, will hang.

Now, as I'm new to mio - and to rust, I might be doing something wrong in my code, however I thought it could be a good idea to turn this into an issue.

If there is something wrong with my code, what is it?

Regards
Flavius

```
extern crate mio;

use std::collections::HashMap;
use std::net::SocketAddr;
use mio::*;
use mio::tcp::*;


struct WebSocketServer {
    socket: TcpListener,
    clients: HashMap<Token, TcpStream>,
    token_counter: usize,
    ticks: usize,
}

impl WebSocketServer {
    fn new(socket: TcpListener) -> WebSocketServer {
        WebSocketServer {
            socket: socket,
            clients: HashMap::new(),
            token_counter: 1,
            ticks: 0,
        }
    }
}

const SERVER_TOKEN: Token = Token(0);

impl Handler for WebSocketServer {
    type Timeout = usize;
    type Message = ();

    fn ready(&mut self, event_loop: &mut EventLoop<WebSocketServer>, token: Token, events: EventSet) {
        match token {
            SERVER_TOKEN => {
                let client_socket = match self.socket.accept() {
                    Err(e) => {
                        println!("Accept error: {}", e);
                        return;
                    },
                    Ok(None) => unreachable!("Accept has returned 'None'"),
                    Ok(Some((sock, addr))) => sock
                };
                //println!("{:?}", client_socket);
                client_socket.shutdown(Shutdown::Both);
            },
            token => {
            }
        }
    }
    fn notify(&mut self, event_loop: &mut EventLoop<Self>, msg: Self::Message) {
        println!("notify");
    }
    fn timeout(&mut self, event_loop: &mut EventLoop<Self>, timeout: Self::Timeout) {
        println!("timeout");
    }
    fn interrupted(&mut self, event_loop: &mut EventLoop<Self>) {
        println!("interrupted");
    }
    fn tick(&mut self, event_loop: &mut EventLoop<Self>) {
        self.ticks += 1;
        println!("tick {}", self.ticks);
    }
}

fn main() {
    let mut event_loop_config = EventLoopConfig::default();
    //event_loop_config.messages_per_tick(1000)
                     //.timer_tick_ms(1000000)
        //;
    let mut event_loop = EventLoop::configured(event_loop_config).unwrap();
    let address = "0.0.0.0:10000".parse::<SocketAddr>().unwrap();
    let server_socket = TcpListener::bind(&address).unwrap();
    let mut handler = WebSocketServer::new(server_socket);

    event_loop.register(&handler.socket, SERVER_TOKEN, EventSet::readable(), PollOpt::edge()).unwrap();

    event_loop.run(&mut handler).unwrap();
}
```

**Comment by szagi3891** [comment]
I had exactly the same problem :)

My solution : https://github.com/szagi3891/miohttp-rs/blob/master/src/server.rs#L214

I use a loop to handle new connections.
Does it help?

**Comment by hjr3** [comment]
@flavius I believe it because your `ready` function does not handle the case of more than one connection waiting to be accepted. There might be more than one connection waiting to be accepted per event loop tick. As @szagi3891 showed, you can use a loop when accepting new connections.

**Comment by flavius** [comment]
@szagi3891, @hjr3 Thanks guys, it worked. I'd like to keep this issue opened because I'll get back with a PR to show an example, within the next days. Is it fine if I add it to the documentation? As I said, I'm new to the rust ecosystem and I'm not accustomed to the idiomatic way of doing things in rust.

**Comment by hjr3** [comment]
@flavius I think documentation would be great. This is more of an async IO issue instead of a mio issue, but education in general is always good.

**Comment by rrichardson** [comment]
@flavius  Mind if we close this?  We'd be happy to accept a test or docs demonstrating this feature in the future.

**Comment by sateffen** [comment]
Is this still a point? I never read about looping for accepts in any blog or tutorial.

I added this to my project, and collected some stats, but the loop always runs only once.

If this is a thing, a hint in the documentation for the accept method would be great :)

**Comment by carllerche** [comment]
Tracking this in the doc issue #380
