### ISSUE TITLE
shutdown method missing from UDS

### ISSUE THREAD

**Issue by danielrh** [carllerche/mio#384]
My protocol requires a unix domain socket to issue a shutdown event
to half-close the send-side
However this function is missing from the unix domain socket implementation

shutdown(self, how :net::Shutdown)

Would it be possible to add it to uds.rs , in the same way as it's present in the sys/unix/tcp.rs file?

**Comment by rrichardson** [comment]
Should we close this or leave it open until we cut a release?

**Comment by carllerche** [comment]
I'll close it since it was merged... hopefully we can get to a release soon :)
