### ISSUE TITLE
Require 3rd party library to get pipes into mio from std::process::Child

### ISSUE THREAD

**Issue by danielrh** [carllerche/mio#387]
Hey folks-
I'm trying to treat process::Child pipes as a mio PipeReader and PipeWriter

Unfortunately the way I figured out to do it had a lot of rough edges and required me to import nix directly
```

use nix::fcntl::FcntlArg::F_SETFL;
use nix::fcntl::{fcntl, O_NONBLOCK};
extern crate nix;

fn set_nonblock(s: &AsRawFd) -> io::Result<()> {
    fcntl(s.as_raw_fd(), F_SETFL(O_NONBLOCK)).map_err(from_nix_error)
                                             .map(|_| ())
}
    let process =
           Command::new("cat")
           .stdin(Stdio::piped())
           .stdout(Stdio::piped())
           .spawn().unwrap();
    let stdin_fd;
    match process.stdin {
      None => unreachable!(),
      Some(ref item) => {
          let err = set_nonblock(item);
          match err {
             Ok(()) => {},
             Err(e) => panic!(e),
          }
          stdin_fd = PipeWriter::from(Io::from_raw_fd(item.as_raw_fd()));
      },
    }
```

This seems cumbersome and error prone (initially I wasn't aware I needed to call set_nonblock on item, and my process hung unexpectedly)

Could we have an adapter directly from process::ChildStdin and process::ChildStdout and process::ChildStderr ?

**Comment by rrichardson** [comment]
Should we close this or leave it open until we cut a release?
