### ISSUE TITLE
convert::millis can't convert large Durations

### ISSUE THREAD

**Issue by tikue** [carllerche/mio#393]
This test fails in `mod convert`:

```rust
#[test]
fn convert_big_duration() {
    millis(Duration::from_secs(::std::u64::MAX));
}
```

`fn timeout` already returns a `TimerResult`, so probably `convert::millis` should return a result as well, which would then be propagated out, instead of panicking.

**Comment by tbu-** [comment]
It would probably be better to just return `u64::MAX` in that case. `u64::MAX` milliseconds are still many million years, and any longer timeout just doesn't make any difference.

**Comment by carllerche** [comment]
This is fixed by https://github.com/carllerche/mio/commit/7108b3de0ff050202c7340dfef3510bcf81a0539
