### ISSUE TITLE
PollOpt::oneshot may result in data ignored on Windows

### ISSUE THREAD

**Issue by housleyjk** [carllerche/mio#394]
A user of WS-RS (WebSockets based on Mio) noticed that some clients would hang after the WebSocket handshake on Windows: housleyjk/ws-rs#47. It appears that `oneshot` can result in events being ignored on Windows if interest isn't reregistered fast enough to handle the new event. This issue does not occur on Linux, and it is not dependent on anything in WS-RS. 

The following gist replicates the issue using only Mio: https://gist.github.com/housleyjk/5ffb08805d6b098d8712824e1f8d9c75. LIne 48 introduces a call to `std::thread::sleep` in order to introduce a delay in reregistering interest. When the sleep line is included, the program hangs waiting for the server to read the incoming data. The issue also disappears is `oneshot` is not used, but then we miss out on the advantages of `oneshot`. The gist was tested using the master branch on commit #e7ac893ff81a7978add016266c27dc5b5f9ff9bc.

Please advise whether this is a bug or whether there is something wrong with this usage of PollOpt::oneshot on Windows.

Thank you!

**Comment by carllerche** [comment]
Thanks for the report. I'll take a look.

**Comment by tikue** [comment]
I'm also running into this issue. I don't have a minimal test case, unfortunately. Same symptom though: a hanging program, and when I checked the logs it appeared to be an ineffective EventLoop::reregister. My workaround is basically:

```rust
event_loop.reregister(&self.socket,
                      token,
                      EventSet::readable(),
                      if cfg!(wndows) {
                          PollOpt::edge()
                      } else {
                          PollOpt::edge() | PollOpt::oneshot()
                      })
```

**Comment by housleyjk** [comment]
Yep, that's this issue. As I said above, the issue disappears if `oneshot` isn't used, but then we probably miss out on the benefits of `oneshot`.

**Comment by alexcrichton** [comment]
A number of bugs around PollOpt and EventSet may be fixed by https://github.com/carllerche/mio/pull/426, @housleyjk could you try with that PR applied?

**Comment by carllerche** [comment]
I think that this is fixed on master.
