### ISSUE TITLE
Any drawbacks in setting low `EventLoopConfig:: timer_tick_ms`?

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#398]
What's the cost of setting `EventLoopConfig:: timer_tick_ms` to ie. 1ms?

**Comment by rrichardson** [comment]
I am pretty sure the answer is there should be no problem, other than you'll need a ton of slots to set timeouts out into the future. Each timeout slab entry is a min of 256 bytes, so 30 seconds would be 30,000 slots * a min of 256 bytes. 

We should probably make a unit test that tests this idea.  *hint hint*  :)

**Comment by carllerche** [comment]
What rrichardson said... you can set a low timer tick increment, but I can't think of a situation when that is wanted.

**Comment by dpc** [comment]
@carllerche : I don't understand. If it is not ever wanted, should it even be a setting for it?

**Comment by carllerche** [comment]
Tuning the tick size can be useful. I don't personally know of a reason to go as low as 1ms though.

**Comment by dpc** [comment]
Is the tick the lowest possible resolution? I could imagine someone wanting even sub-ms latencies, etc. No?
