### ISSUE TITLE
out of date comment in the example PingPong server

### ISSUE THREAD

**Issue by oconnor663** [carllerche/mio#403]
// A very inefficient implementation. A better implementation could be
    // built using `Vec::drain()`, but the API is currently unstable.

The drain API is stable now, so it might be time to drop it in? I tried to build this example, but I ran into build errors like this one:

```
/tmp/mio/src/handler.rs:18:5: 19:6 error: the trait bound `Self: std::marker::Sized` is not satisfied [E0277]
/tmp/mio/src/handler.rs:18     fn ready(&mut self, event_loop: &mut EventLoop<Self>, token: Token, events: EventSet) {
/tmp/mio/src/handler.rs:19     }
/tmp/mio/src/handler.rs:18:5: 19:6 help: run `rustc --explain E0277` to see a detailed explanation
/tmp/mio/src/handler.rs:18:5: 19:6 help: consider adding a `where Self: std::marker::Sized` bound
/tmp/mio/src/handler.rs:18:5: 19:6 note: required by `event_loop::EventLoop`
```

**Comment by oconnor663** [comment]
Related: Some of the code in https://github.com/carllerche/mio/blob/getting-started/doc/getting-started.md is out of date. `event_loop.register` seems to need 4 arguments instead of 2.

**Comment by carllerche** [comment]
I am unifying doc issues. This issue will now be tracked in #403. Closing this one.

**Comment by oconnor663** [comment]
@carllerche this _is_ #403 :-D
