### ISSUE TITLE
When will there be a new publish to crates

### ISSUE THREAD

**Issue by ustulation** [carllerche/mio#406]
hey @carllerche 

This fix https://github.com/carllerche/mio/issues/402 ([PR](https://github.com/carllerche/mio/pull/401)) was of primary importance for us because there were frequent crashes in the production code. Right now we have pointed to `master` of `mio` since that patch was accepted. We are on the verge of a release and need `Cargo.toml` to have crate-only dependencies.

Also [this issue](https://github.com/carllerche/mio/issues/397) is of importance too. Presently we are either working around it or using Linux/Mac in places where we cant.

How soon do you guys estimate we have next mio version up in crates ? I am asking this question to get a hint; if it is not anytime soon then we will just put it as `mio-tmp` or something and then yank/deprecate it once you do the update to crates.

**Comment by carllerche** [comment]
Master has deviated quite a bit. To get a release out quicker, the appropriate changes would need to be back ported to the 0.5 branch (https://github.com/carllerche/mio/tree/v0.5.x). I can try to do it sometime this week, but if you could look at what bug fixes can be back ported that could help speed it along.

**Comment by ustulation** [comment]
Ok, I've got that one raised against `v0.5.x` - https://github.com/carllerche/mio/pull/407
If i have any bandwidth left i'll see if i can squeeze out some time for others.

Thanks for your response !

**Comment by carllerche** [comment]
Hoping 0.6.0 will be released soon. I see your PR for 0.5.x, but CI isn't passing :( Let's continue the discussion in the PR.
