### ISSUE TITLE
openbsd regression

### ISSUE THREAD

**Issue by ezra1** [carllerche/mio#410]
Looks like openbsd support was added earlier..... (commit 60d54772f19199c8888876df1194b75eb72c6c53)
It's not there anymore, as I tried to build mio on openbsd and failed.... (works on my machine with openbsd current with it added in BTW)

**Comment by alexcrichton** [comment]
Unfortunately OpenBSD isn't a tier 1 or 2 platform of Rust right now, so the platform support here is largely just "best effort". PRs are of course always welcome though!

**Comment by carllerche** [comment]
A big help would be figuring out how to get CI support working for *bsd. Thoughts?

**Comment by carllerche** [comment]
I'm going to close this for now, because unfortunately, I do not have a way to test/fix this. I will merge any PRs though :(

I would like to support *BSD better, but unless it can get integrated into the CI setup, it will be hard to support officially.
