### ISSUE TITLE
Missing openwrt/mipsel support

### ISSUE THREAD

**Issue by tomsiwik** [carllerche/mio#413]
I'm referencing the feature request:

https://github.com/dpc/mioco/issues/143

Are there any plans any time soon? Would love to see work done for these platforms. 
Kind regards

**Comment by alexcrichton** [comment]
Right now I don't believe there are plans to actively seek out and support these platforms, but PRs are of course always welcome!

**Comment by posborne** [comment]
Agreed.  We have done some work on this in nix which should hid the underlying platform differences (with the help of libc) but the tests for these platforms in CI are failing at the moment.  Help very welcome (I am currently doing some work on OpenWRT but on the ARM side of the things):

Probably one of the most beneficial things that can be done to help further mio support on other platforms is increasing the platform coverage in CI.  I have done work on that in [nix using docker](https://github.com/nix-rust/nix/tree/master/ci) and @alexcrichton also recently updated the [test infrastructure for libc](https://github.com/rust-lang/libc/tree/master/ci).  The docker image used for building nix are currently here: https://github.com/rust-embedded/docker-rust-cross (could use some updates).

Some more links:

* [recent nix mips failure](https://travis-ci.org/nix-rust/nix/jobs/140023810)
* [recent nix mipsel failure](https://travis-ci.org/nix-rust/nix/jobs/140023811)

**Comment by tomsiwik** [comment]
That's weird. For me crosscompiling nix succeeded with the latest release.

**Comment by carllerche** [comment]
As mentioned above, there is no current plan to support more platforms but PRs are welcome. I am going to close the issue now.
