### ISSUE TITLE
[Question] What happens on reregistering something registered

### ISSUE THREAD

**Issue by sateffen** [carllerche/mio#416]
Hey,

I'm now trying to make mio work with threads, and so I'm using the channel/senders. It works nearly like a charm, but now I got a question:

After I received some data from a socket, I send the data to a thread, and reregister the socket as event listener, still only interested in *hup* and *readable* events. I'm not yet interested in *writeable* events, because the thread might take it's time, so I'll wait. After some time the thread calls a Sender and sends data to the eventloop. In the eventloop I want to write to the socket, fill up it's buffer, and adding the interest for writeable, but of cause mio doesn't know about this, because I registered some time ago without the interest of writing.

Now, so I need to reregister, but is reregistering realy ok, if no event occured right before?

All tutorials do something like:

```
ready(...) {
    handle_readable_event_for_socket...
    // reregister, because we were registered before the event as well, so reregister makes sense
    reregister_socket...
}
```

But does this work (as expected, and is ok) as well:

```
notify(...) {
    do_something
    reregister_socket(readable_interest & writable_interest)
}
ready(...) {
    handle_readable_event_for_socket...
    thread_spawn(send_something_to_mio_channel)
    reregister_socket(readable_interest)
}
```

The documetation doesn't help at this point. The code works, but I don't know how mio handles this internally (maybe causing unexpected behaviour).

**Comment by bluejekyll** [comment]
So I've had mixed experience with reregister across OSes. Between Linux and OS X, OS X is more forgiving, where you can call reregister regardless of current registry. Linux in my experience wasn't as forgiving. Example, see my note here:

https://github.com/bluejekyll/trust-dns/blob/master/src/tcp/tcp_client_connection.rs#L56

And then reregister will work properly:

https://github.com/bluejekyll/trust-dns/blob/master/src/tcp/tcp_client_connection.rs#L69

But if you see that note, deregister hasn't been working for me on OS X (I haven't had a chance to debug that, but will at some point if someone else doesn't get to it).

This is the line for deregister that I have commented out:

https://github.com/bluejekyll/trust-dns/blob/master/src/tcp/tcp_client_connection.rs#L84

I am concerned that I'm leaking connections here, but this is the best thing I have right now for interop between Linux and Mac OS X. I don't yet have a Windows test env.

**Comment by sateffen** [comment]
Unexpected behavior is uncool.

The logic to first register, and only reregister after a successful registration makes sense, and is no problem. But if deregister doesn't work on osx, this is something important to investigate I guess.

The question is more about reregistering something, that is already reregistered, like doing something like:

```
event_loop.reregister(socket, ...);
event_loop.reregister(socket, ...);
```

directly after each other, without any code between them (this would be stupid, ok, but is basically the question I've got).

**Comment by bluejekyll** [comment]
assuming you already have the socket registered, this is exactly what reregister is for, I believe.

**Comment by carllerche** [comment]
It would be super helpful if you could create a test case illustrating the difference in behavior.

Regarding `reregister`, it *must* only be used after calling `register`.

I would like to be able to catch incorrect usage at runtime, but I also have limited ability to do so w/o introducing a runtime.

I'm toying w/ the idea of creating a "debug" mode that has a runtime that catches incorrect usage when debug is enabled at compile time but goes away at runtime...

**Comment by sateffen** [comment]
Can you specify, what exactly you need?

My question is regarding whether there is a difference in bebaviour or not. My code should:

* Register a readable event for socket
* Get read data for socket, push them to thread, reregister readable
* After some time the thread sends a notification about data to write
* Notification leads to reregister with read+write interest

By the time the last point occurs, the previous registration is still intact for my socket, but with a different set of interests. So simplified, my code would do:

`
..reregister(write)
..reregister(write+read)
`

My question is, whether this is actually bad, and cause 2 events to occur on the next read event, or maybe this is ok, because mio handles the interests internally.

Because if this would actually screw mio, I have to call deregister -> register instead.

This is something, that the documentation doesn't explain to me, and I'm curious about the behaviour. I don't fully understand the sourcecode, so I have to ask :-S

**Comment by carllerche** [comment]
You should be able to call `reregister` as many times as you want *after* calling `register`.

**Comment by sateffen** [comment]
This answers my question perfectly well. Thank you.

Should we close this issue, or do you want anything to be done here as resolution?

**Comment by carllerche** [comment]
I'm going to close it for now. It is tracked in the other meta issues.
