### ISSUE TITLE
Possibility to add TLS support

### ISSUE THREAD

**Issue by tigranbs** [carllerche/mio#421]
I'm building Server to Server communicational service with `mio` and I need to implement `tls support`.
Can you suggest me any Rust library for that, or should I use some `C implementation` for that ?

Thanks

**Comment by nathansizemore** [comment]
[rust-openssl](https://github.com/sfackler/rust-openssl) has all of the bindings you need for OpenSSL. I'm not aware of any other TLS protocol supporting lib in the rust ecosystem besides that one. It's `SslStream` simply wraps any implementer of `io::Read + io::Write`, although it has separate methods for non-blocking calls, in the same fashion as actual OpenSSL.

**Comment by sateffen** [comment]
Actually, there is [rustls](https://github.com/ctz/rustls), an TLS implementation in pure rust, but this is a little limited. Maybe it helps.

**Comment by tigranbs** [comment]
Ok looks great!
Thanks 👍
