### ISSUE TITLE
Windows aborts TcpStreams on close

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/mio#423]
On Windows, dropping the stream results in a `WSACONNABORTED` error on the client side.

I've noticed this when running a hyper server on Windows, that all responses end in an abort: https://github.com/hyperium/hyper/issues/816

That issue also includes an attempt by a downstream user to fix it, I haven't been able to test those 'fixes' myself.

Test case: https://gist.github.com/seanmonstar/8829d325daa386ffe171b17e52d0038b

**Comment by alexcrichton** [comment]
This is probably [due to the `Drop` implementation](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/sys/windows/tcp.rs#L425-L443) forcibly closing the socket, even if there are pending writes in flight. Probably just need to verify that Unix waits for pending writes to finish and then closes the socket, and mio should just do the same.

**Comment by sateffen** [comment]
[This](https://www.intervalzero.com/library/RTX64/HTML5/Content/PROJECTS/SDK%20Reference/WinsockRef/closesocket.htm) reads like it belongs here: *The connection is also reset if closesocket is called before all received data has been read by the application.*

Your test client sends data, but your server never reads them. I guess if you read the data in your server back in and drop the socket afterwards, it works fine.

**Comment by seanmonstar** [comment]
It seems that is true, that if I comment out writing to the socket in the client side of the test case, it doesn't abort.

However, I added in `| EventSet::readable()` to the register, and this before the `is_writable()` block:

```rust
if tok == STREAM && events.is_readable() {
    let mut stream = self.stream.as_mut().unwrap();
    loop {
        match stream.read(&mut [0; 4096]) {
            Ok(n) => println!("read {}", n),
            Err(e) => match e.kind() {
                io::ErrorKind::WouldBlock => {
                    println!("reading would block");
                    break;
                },
                _ => panic!("error: {}", e)
            }
        }
    }
}
```

The server shows that its reads 59 bytes, and then gets WouldBlock. Afterwards, it writes, and drops, and the connection is aborted.

**Comment by nathansizemore** [comment]
A successful write doesn't mean it went out the actual tx line, only that it went into kernel space. It may be of use to set `SO_LINGER` on each socket you care about for Windows. Check out options [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740476(v=vs.85).aspx).  

I believe these just got added to net2 and latest libc release.

**Comment by alexcrichton** [comment]
I believe I've fixed this in https://github.com/carllerche/mio/pull/444.

**Comment by carllerche** [comment]
This should be fixed on master. Closing
