### ISSUE TITLE
No longer compiles

### ISSUE THREAD

**Issue by MarkSwanson** [carllerche/mio#424]
Because net2 was updated and no longer compiles with the version of Rust I'm using, I can no longer build mio.

In my Cargo.toml I tried to force a specific SHA for net2 so an earlier version would be used:
net2 = { git = "https://github.com/rust-lang-nursery/net2-rs.git", rev = "b9d0c2d5dc187265e1d13130c3b1c4a69d01da6a" }

Since mio is relaxed about the net2 version, mio will still try to build against the latest/broken net2.

I could fork mio and force the dependency on mio to be something that will work.
But, I'd rather not do that. 
Does anyone know of an easier way? (upgrading rustc is not possible for me atm)

Thanks!

**Comment by posborne** [comment]
Hi @MarkSwanson I ran into this with my PR (https://github.com/carllerche/mio/pull/414) as well and things are left in a bit of a sticky place.  I think we need to upstream some changes to net2 to avoid the unnecessary breakage due to Cargo.toml updates.

**Comment by andrewjstone** [comment]
For now you can manually edit the Cargo.lock file to only reference that
sha. As long as you don't cargo update net2 it should work fine.

**Comment by alexcrichton** [comment]
I've pushed an updated net2 which I believe should be compatible, so I'm gonna close. Sorry for the breakage!
