### ISSUE TITLE
Same loop with different handlers

### ISSUE THREAD

**Issue by pijul** [carllerche/mio#428]
I'd like to be able to use a single loop with different handlers. My use case is thrussh, a crate implementing the SSH protocol.

I'd like to do the following, with the same socket:

- Connect/authenticate, which is a CPU-intensive operation (public key cryptography). Use a specific handler for that part of the protocol.

- Upload a file with scp, taking the file from an R:std::io::Read. This needs a specific handler.

- Download a file with scp, writing it in an W:std::io::Write. This also needs a specific handler.

A possible solution would be to have an enum with the three different handlers. Unfortunately, when creating the loop, we don't know what R and W will be. Also, we might want to upload different files from different instances of std::io::Read (i.e. change R).

The exact change I'm proposing (which fixes this use case) is shown in pull request #429.

**Comment by alexcrichton** [comment]
I believe this use case can be targeted with the recent addition of the `Poll` API. That allows separation of the `Handler` and the polling abstraction itself, allowing you to use the same "event loop" across multiple handlers by baking more of it yourself. Would that work for you use case?

**Comment by pijul** [comment]
It works! Thanks. I guess I just have to "pull request" a documentation example then.
