### ISSUE TITLE
Simple defaults for types

### ISSUE THREAD

**Issue by ustulation** [carllerche/mio#438]
I am not entirely sure how useful it will be in general, but during state-machine kind of implementation sometimes i required to hand over say `mio::tcp::TcpStream` (kept as a member variable of a state-struct) from one state to another, maybe in the `Drop::drop()` of the original state or some other function. I didn't want to do `try_clone()` so I had to wrap it in `Option<>` so that I could do `Option::take().unwrap()` to hand it over. Would it be nice if these types could be created as invalid defaults cheaply ? Then for instance in state transitions i could use `let socket = mem::replace(&mut self.socket, Default::default());` to transition and handover `self.socket` (from a function that borrows `self` like `Drop::drop()` or any other) to another state.

**Comment by sateffen** [comment]
If it's only me than I'm sorry, but I don't realy get, what you want to do.

Could you create a simple [gist](https://gist.github.com/) which tells some code (as minimalistic as needed)? At least for me this would help to get the basic problem, then maybe I could help as well.

**Comment by ustulation** [comment]
Sure (it's contrived but should demonstrate):
```
// Assume state_map is HashMap<Token, Rc<RefCell<SomeStateTrait>>>
struct State0 { socket: TcpStream, }
impl SomeStateTrait for State0 {
    fn check_transition(&mut self) {
        if some_condition {
            remove_from_state_map(self_token); // This state is done - handover to the next
            let socket = mem::replace(&mut self.socket, Default::default()); // <--- This is helpful
            insert_into_state_map(self_token, State1::new(socket));
        }
    }
}

struct State1 { socket: TcpStream, }
impl State1 {
    fn new(socket: TcpStream) -> Self { State1 { socket: socket, } }
}
impl SomeStateTrait for State1 { ... }
```

**Comment by alexcrichton** [comment]
Like the standard library, there's unfortunately not a *great* implementation of `Default` for I/O objects, so I'd expect mio to follow in the same footsteps and not implement `Default`

**Comment by ustulation** [comment]
:( ok - closing it then (it does restrict clean code in popular designs though).
