### ISSUE TITLE
mio 0.3.7 -> mio 0.5 (and master) latency regression

### ISSUE THREAD

**Issue by wrl** [carllerche/mio#442]
Hey, I have some mio code for handling input from a Linux `hidraw` device, which is latency-sensitive. After updating my code from mio 0.3.7 to mio 0.5, I notice an additional ~20ms (ballpark, as of yet unmeasured) of latency when responding to events received via the hidraw fd. I then updated to mio master and the issue persisted.

**Comment by arthurprs** [comment]
Could you try to provide more details?

This really smells like a naggle algorithm kicking in.

**Comment by carllerche** [comment]
hmmm that is a good point. I think we switched to net2 for building sockets. I don't think it sets `TCP_NODELAY`.

cc/ @alexcrichton

**Comment by carllerche** [comment]
Ok, there is a way to set nodelay. I'm going to track this issue under the documentation ticket. (#433)

**Comment by wrl** [comment]
Will test this. Of note is that I am seeing the issue with an event loop consisting of only a `hidraw` device and a UDP socket.

**Comment by daschl** [comment]
@wrl watched your talk that got published from rustfest, the ticket is closed but did it get resolved?
