### ISSUE TITLE
I can not set event_loop.register to EventSet::error() | EventSet::hup()

### ISSUE THREAD

**Issue by szagi3891** [carllerche/mio#443]
I get the error message: interest must include readable or writable.

This mode allows me to listen to disconnect a customer.

**Comment by rrichardson** [comment]
HUP and Error are on by default. No need to register for them.

**Comment by szagi3891** [comment]
mayby better remove from Enum EventSet this values? 

I when the not read or write, I invoke function event_loop.deregister. Whether I will get information about the HUP and Error?

**Comment by bluejekyll** [comment]
I tend to use `!EventSet::writable()` or `!EventSet::readable()` to basically switch between the two while I'm moving through a protocol. So I haven't run into this personally.

I actually didn't realize that HUP and Error were on by default though, better docs?

**Comment by alexcrichton** [comment]
I believe that this likely comes from the Windows implementation which now almost entirely uses the `poll::Registration` structure, and now [that validates](https://github.com/carllerche/mio/blob/4184a9d69be927e58ebf3fcc4ce2635c6ed9583e/src/poll.rs#L258-L268) that either readable/writable must be present.

**Comment by carllerche** [comment]
`Error` & `HUP` are hints of what `read` / `write` will return, as such they are a super set of asking for read / write interest. They also aren't guaranteed to be included in the `EventSet` on all supported platforms (only read & write are).

In general, I would not ask for error & hup interest unless you are sure you know the edge cases & know why you need to ask for them explicitly.

I'll track this as a documentation issue, but the value of adding extra interest ops besides read & write is TBD.
