### ISSUE TITLE
Setting socket options immediately after connecting may fail

### ISSUE THREAD

**Issue by danburkert** [carllerche/mio#446]
I'm seeing this issue on OS X, but I believe it could happen on Linux as well.  I'm creating a TCP socket through `mio::tcp::TcpStream::connect`, and then immediately calling `TcpStream::set_nodelay`.  About 20% of the time, the `set_nodelay` call fails with error 22 (`EINVAL`).  `dtruss` reveals that in these cases, the initial `connect` system call failed with error 36 (`EINPROGRESS`), but mio is [swallowing these erorrs](https://github.com/carllerche/mio/blob/dev/src/sys/unix/tcp.rs#L37).

I've worked around the issue for the moment by only setting socket options after the first non-error `ready` notification, but it would be nice if there were a way to set the option closer to the socket setup.  `net2::TcpBuilder` has no `set_nodelay` option.

**Comment by carllerche** [comment]
At the very least, this is a documentation issue. How to create a custom TCP socket & setting `nodelay` should be documented.

I am less sure about the `EINPROGRESS` situation. On one hand, it could be nice to return that info, on the other, the odds are very strong that the connection will be in progress and the way to wait for the connection to become established is to wait for a readiness notification. My guess is that this is also a documentation issue.

**Comment by carllerche** [comment]
Tracking this as a documentation issue.
