### ISSUE TITLE
Consider renaming EventSet -> Ready

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#452]
Currently `Event` is an `EventSet` + a `Token`. The naming is backwards. `EventSet` represents which operations are ready for a `Token`. I propose renaming `EventSet` -> `Ready`

**Comment by hjr3** [comment]
I am +0 on this. I think something like `ReadyOps` or even just `Ops` would be more clear. That being said, naming is hard and is probably not worth bike shedding over.

**Comment by carllerche** [comment]
Heh, you gotta at least be a +0.25 on it... Avoiding the `EventSet` / `Event` inversion seems like a win :)

**Comment by alexcrichton** [comment]
I believe the only source of an `Event` is the `Events` iterator (which in turn is filled in by `Poll`). If there's no plans to extend `Event` itself to contain more data, I wonder if we could sidestep this entirely? It may be possible for `Events::iter` to yield an iterator of `(Token, ???)` where `???` is `EventSet` today, but we could perhaps call it `Event` instead as the name would just be freed up?

If there's plans to extend `Event` though in the future to contain more data then it may be better to keep it opaque.

**Comment by carllerche** [comment]
The only other case is `Events::get(i) -> Option<Event>`... returning `(Token, ???)` in this case feels a bit weird... also, ??? Still has to be named.

`Ready::readable()`, `Ready::writable()`, `Ready::hup()` is OK w/ me, but I can can understand the hesitation.

`Op` doesn't sit well w/ me. In my mind that refers to an actual operation vs. a state of being ready to perform an operation.

**Comment by carllerche** [comment]
Unless there is another suggestion / objection, I'm going to make this change.

**Comment by carllerche** [comment]
(getting rid of `Event` can be done separately)

**Comment by carllerche** [comment]
Merged on `dev`
