### ISSUE TITLE
Update 'nix'

### ISSUE THREAD

**Issue by dariusc93** [carllerche/mio#456]
In a recent test, it looks like mio cant build on freebsd because nix and an issue at https://github.com/nix-rust/nix/issues/388 . This was fixed in https://github.com/nix-rust/nix/pull/389 but mio still uses nix-0.6.0 and not the latest. Should mio use something like whats below to fix the issues or will mio wait until nix 0.6.1[-dev] release?

```
nix = {git = "https://github.com/nix-rust/nix.git", rev = "fd4a510"} 
```

**Comment by posborne** [comment]
@dariusc93 Feel free to request a nix release as well.  We have done these a little infrequently in the past, but I think we are quite open to doing it more frequently, particularly if there is a request that we cut a release.

**Comment by dariusc93** [comment]
@posborne I could've requested a release as well, but I only assumed nix still in a state where it may not be ready to be released as 0.6.1[-dev].

**Comment by posborne** [comment]
Nah, we just put that on there between releases.

**Comment by dariusc93** [comment]
Is there a release cycle for nix?

**Comment by carllerche** [comment]
Hopefully soon then, I'm hoping to release Mio 0.6.0 this week :)

**Comment by dariusc93** [comment]
Cool! I'll just have used local versions for now.

**Comment by GrappigPanda** [comment]
Hey @dariusc93 This is kind-of strange, but I managed to build mio v0.5.1 on FreeBSD 10.3 today. Moreover, it looks like both of those issues are for NetBSD, not FreeBSD.

**Comment by dariusc93** [comment]
@GrappigPanda If it means anything, I am building for FreeBSD 11-RC2, not 10.3-Stable. I havent used NetBSD or OpenBSD when building mio either.

**Comment by beatgammit** [comment]
I just built mio 0.6 with the latest nix on FreeBSD 10.3 and it compiles for me, but using 0.6.0 from crates.io, it doesn't.

Personally, I'd appreciate a release with the update to libc. It's not urgent for me since I'm mostly using it for testing a WIP project, but it would make things a little simpler.

**Comment by beatgammit** [comment]
My PR #477 was merged, so this is effectively fixed. Can someone close this?

**Comment by alexcrichton** [comment]
sure!
