### ISSUE TITLE
Bug: Setting wrong readiness value in channel code to wake poller on pending messages

### ISSUE THREAD

**Issue by andrewjstone** [carllerche/mio#463]
I believe the line [here](https://github.com/carllerche/mio/blob/ce5d4fb5cde330c8486ddf3d91142ac03134c6d7/src/channel.rs#L242) should be `try!(set_readiness.set_readiness(Ready::readable()));` instead, or the poller won't wake up properly.

**Comment by carllerche** [comment]
Yep, you are correct... thanks 👍
