### ISSUE TITLE
Still got events after deregister a socket.

### ISSUE THREAD

**Issue by loggerhead** [carllerche/mio#464]
After deregister a socket, I can still got events from that socket. So I am confused what exactly does deregister do? When should I close a socket after deregister? 

My environment:

* OS X 10.10.5
* mio 0.5.1
* rustc 1.13.0-nightly (acd3f796d 2016-08-28)

**Comment by carllerche** [comment]
Would you be able to provide a small repro case?

**Comment by loggerhead** [comment]
Sorry, I changed a lot of my source code to bypass the problem, and I don't commit the original problematic source code. 

But I remember that I misused `register` as `reregister` to change events on already listened sockets. Is this a possible reason? Any way, I'll close this issue because of my misuse.

**Comment by loggerhead** [comment]
I am confused why need `reregister` instead add a flag in `register` to remember the socket is registered or not.
