### ISSUE TITLE
timer: Infinite readyness loop when timeout is cancelled

### ISSUE THREAD

**Issue by 17dec** [carllerche/mio#465]
Using mio 0.6.0 & rustc 1.13.0-nightly (497d67d70 2016-09-01) on Linux.

With the documentation on the timer being a bit scarce, I'm not sure if I am using the API correctly. By calling Timer::cancel_timeout() I can reliably get Poll::poll() to keep returning a timer event instantly, even when Timer::poll() does not report any ready timers. This is the minimal running code to demonstrate the issue:

```rust
use std::time::Duration;
use mio::{Poll,Events,Ready,PollOpt,Token};
use mio::timer::Timer;

fn main() {
    let mut timer: Timer<u32> = Default::default();
    let timeout = timer.set_timeout(Duration::from_secs(2), 1).unwrap();
    timer.cancel_timeout(&timeout);

    let poll = Poll::new().unwrap();
    poll.register(&timer, Token(0), Ready::readable(), PollOpt::edge()).unwrap();

    let mut events = Events::with_capacity(16);

    loop {
        poll.poll(&mut events, None).unwrap();
        println!("Poll returned {} events", events.len());
        while let Some(_) = timer.poll() {
            println!("  Timer event");
        }
    }
}
```

The above code will wait for 2 seconds and then print out an infinite number `Poll returned 1 events` lines. The `Timer event` line is (correctly) not being printed.

Removing the call to cancel_timeout() will print out a single `Poll returned 1 events` and `Timer event` and then go back to sleep, as expected.

Removing the call to timer.poll() will also print out a single `Poll returned 1 events` line and then go back to sleep.

**Comment by carllerche** [comment]
Thanks for the report. This is definitely a bug! Fixed on master.
