### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by sateffen** [carllerche/mio#467]
The changelog still tells that mio 0.6.0 is unreleased, but it's actually on crates.io

Is the changelog not up to date?

**Comment by carllerche** [comment]
Thanks for the report. This is fixed by 9b165879d15efe4c202de065465b12d6b587b02e

**Comment by KenanSulayman** [comment]
Also please update the docs, they are *really* incorrect. Mixed reference to EventLoop whereas only Poll exists now, et al. It took me hours to realize this.
