### ISSUE TITLE
Slab now that mio::util is gone

### ISSUE THREAD

**Issue by aaronst** [carllerche/mio#473]
I'm new to `mio` and rust in general, so this might be a stupid question.  I've been looking at examples for `mio`, and am running into the headache of trying to bridge the gap between these examples/documentation and the current version of `mio`.

I noticed in the change log for version `0.6` that `mio::util` has been removed, which included the slightly altered `Slab` type.  I couldn't find any issues discussing this change, so I'm not sure what the reasoning was.  Now that it's gone, is the idea that we implement this type ourselves?  Or is there something else we should be using instead?

Thanks

**Comment by hjr3** [comment]
It is now an optional dependency. I did the following in https://github.com/hjr3/mob/commit/ac4f314c7db2b717d92b1a6e1020e3d50bae11fd

Add `slab = "0.3.0"` to `Cargo.toml`. In `src/main.rs` (or equivalent):

```
extern crate slab;

use slab;

type Slab<T> = slab::Slab<T, Token>;
```

**Comment by hjr3** [comment]
@aaronst Feel free to hop into channel `#mio` on irc.mozilla.org if you have other questions!

**Comment by aaronst** [comment]
@hjr3 Thanks for the clarification 👍
