### ISSUE TITLE
There is no 'EventLoop' in 'mio'

### ISSUE THREAD

**Issue by AntoineLevesque** [carllerche/mio#475]
(this is probably me asking for help more than an actual issue)
-> just trying to follow : https://nbaksalyar.github.io/2015/07/10/writing-chat-in-rust.html
Has the api changed?

```
[dependencies]
mio = "0.6"
```

```
extern crate mio;
use mio::{EventLoop};
```

![image](https://cloud.githubusercontent.com/assets/5624970/18811067/541d249a-8274-11e6-8910-c931dbe0f38c.png)

**Comment by jwilm** [comment]
The API has been simplified to be an `epoll` abstraction. `EventLoop` and those other types are still available in the `deprecated` module if you want them. Check out [the docs for 0.6](https://docs.rs/mio/0.6.0/mio/)!

**Comment by hjr3** [comment]
@AntoineLevesque Change the dependency to `"0.5"` and you can continue to follow the example. See https://github.com/nbaksalyar/rust-chat/issues/8 for additional info.

**Comment by AntoineLevesque** [comment]
ok I switched to 0.5 for now. Would be nice to have a guide with side by side differences between the two version. Even the official 'Getting started' seems to be using 0.5... Quite confusing.

I'll try to implement the 0.6 on the guide i'm following when i'm done. 

Thx!

**Comment by carllerche** [comment]
Sorry for the confusion. I would be happy to take a conversion guide. Closing the issue for now.
