### ISSUE TITLE
I need modern MIO UDP Server Example

### ISSUE THREAD

**Issue by TrionProg** [carllerche/mio#481]
Hello. I am trying to develop UDP server, but where are problems:
UDP has no writeable event? And I can call socket.send_to every time?
Has UDP error event? Hup I think is TCP feature.
How I should register UDP socket? And should I reregister it?
I try this
Address=0.0.0.0.1975
`
let interest=Ready::readable();
 poll.register(
         &self.socket,
         self.token,
         interest,
         PollOpt::edge()
  )
`

Note, I have thread to process only UDP events and I reregister after each group of udp events(code like register)
But event is calling when only first packet has coming, next packets are "ignored" and they do not call event. I've tried to use PollOpt::oneshot, do not register, but the problem still remains, So I need example.

**Comment by TrionProg** [comment]
U.P.D.
It's works without registration as I wrote, but nowdays problem occurs with net(server and client are running at same computer and send_to address like 127.0.0.1/192.168.** works fine, but when I specify global address(I have router), all packets of size 22bytes excluding first lose. I am working with UDP first time.

**Comment by dpc** [comment]
"can not run server and client at the same computer with router (...) and use external ip as server ip in clientSocket.send_to method" 

That won't work due to how NAT works. There's no easy solution, and it's not mio related.

**Comment by carllerche** [comment]
Thanks for the report, as mentioned above it doesn't look like this is Mio specific, so I am going to close the issue. If you feel like this is an error, please open a new one.
