### ISSUE TITLE
Replacement for Deprecated::PipeWriter/Reader

### ISSUE THREAD

**Issue by NickeZ** [carllerche/mio#491]
Hi,

I'm very new to rust and I'm successfully using mio 0.6 with TcpListeners. But I would like to know what I should use instead of PipeWriter/Reader since they have been marked with deprecated?

The purpose is to communicate with a child process and network services in the same event loop.

Cheers

**Comment by carllerche** [comment]
Hey, I think I will hopefully document this better one day, but the main reason these types are deprecated is that there is nothing special about them. Something *like* them will exist in the future, but probably in another crate. I would probably just keep using them for now, or you can feel free to take on a mio-pipe crate. Mostly, I personally don't want to maintain anything but the core.

**Comment by NickeZ** [comment]
Alright, I guess `mio::util::slab` also is out?

**Comment by carllerche** [comment]
@NickeZ it was moved here: github.com/carllerche/slab

**Comment by NickeZ** [comment]
Thanks! Yeah I found it later, I didn't know it at the time, but I was looking for "type Slab<T> = ::slab::Slab<T, Token>;". Cheers!
