### ISSUE TITLE
BUG ? Poll reports Windows socket  as 'Readable' after reregister with mio 0.6.1, not with mio 0.6.0 

### ISSUE THREAD

**Issue by blabaere** [carllerche/mio#492]
Hello,

In [scaproust](https://github.com/blabaere/scaproust) each tcp stream goes through a handshake phase that look like this:

1. `register writable level`, when polled as writable, write handshake and move next 
2. `reregister readable level`, when polled as readable, read handshake and move next
3. `reregister all edge`, when readiness change, notify observers.

And with mio 0.6.0, everything was working fine, on both Linux and Windows. 
Starting with mio 0.6.1, the step 3 causes Poll to report the stream as both readable and writable, while the peer has no sent anything. With version 0.6.0 the stream was reported as writable only.

This caused the following issue blabaere/scaproust#1.
If this helps, here is an extract of the test logs in both version:

#### MIO 0.6.0
```
DEBUG:scaproust::reactor::dispatcher: process_io Token(4) Ready {Writable}
DEBUG:scaproust::reactor::dispatcher: process_io Token(4) Ready {Readable}
DEBUG:scaproust::reactor::dispatcher: process_io Token(4) Ready {Writable}
```

#### MIO 0.6.1
```
DEBUG:scaproust::reactor::dispatcher: process_io Token(4) Ready {Writable}
DEBUG:scaproust::reactor::dispatcher: process_io Token(4) Ready {Readable}
DEBUG:scaproust::reactor::dispatcher: process_io Token(4) Ready {Readable | Writable}
```

I don't have a simple isolated unit test to reproduce the problem but I will gladly accept a git revision and let appveyor run the whole scaproust test suite with it. Don't hesitate to get in touch with me for more details.

Regards,
Benoît

**Comment by alexcrichton** [comment]
Note that the precise semantics of what's readable/writable when change across platforms and don't tend to have strong guarantees. In that sense it's not immediately clear to me that this is a bug, but an isolated test case would be very helpful!

**Comment by blabaere** [comment]
I understand that it is not possible to get the same ordering, same timing, same number or even the same sequence of events on all OSes. I also think it is not a problem to have 'false negative' that get reported correctly later, 'false positive' on the other hand have more impact. In my use case (load balancing writes and fair queuing reads), the 'receiver' will choose a stream and start a receive operation based on that 'false positive'. Since that stream has not received anything from its peer the operation will timeout and report an error. That's why I think readable 'false positive' is a bug.

Anyway I will write an isolated test case for that and let you know.

**Comment by blabaere** [comment]
The test is written, [available here](https://github.com/blabaere/mio-win-inv). It is in `src/lib.rs`, the test is named `spurious_readable_with_mio_061_but_not_with_060`.
There is a passing [travis build](https://travis-ci.org/blabaere/mio-win-inv).
And a failing [appveyor build](https://ci.appveyor.com/project/blabaere/mio-win-inv).

**Comment by alexcrichton** [comment]
Hm unfortunately I don't have access to a windows machine right now, could you set `mio=trace` in the log environment variable?

**Comment by blabaere** [comment]
[Done](https://ci.appveyor.com/project/blabaere/mio-win-inv)

**Comment by alexcrichton** [comment]
Ok, looking at that specific trace, I believe there is no bug (nor false positive). On Windows there's an emulation layer of epoll with IOCP, and it's not perfect, but mirrors the "lossy" and/or "unpredictable" semantics one might expect with epoll itself.

What happened here was:

* A read of length 0 was scheduled, the socket is now blocked and not receiving events
* The read finished, so the socket transitioned to readable
* Data was read, but successfully. The socket is still readable

At that point you're expecting that because all the data was read the socket is no longer readable. On Linux this is discovered through the kernel which has knowledge of internally buffered data, but on Windows we discover "not readable" through an error returned from an attempted read, where in this case that's not happening. If you were to attempt to do a read (even 0-length) it'd return "would block" and the socket would transition to not readable.

This is unfortunately just how the semantics are different across platforms. In general you can't have particularly strict assertions about whether sockets are readable or writable and expect that to work everywhere.

**Comment by blabaere** [comment]
@alexcrichton So in my case, to get a more accurate readiness of the socket, I can call `TcpStream::read` and `TcpStream::write`, passing a 0 length slice and then only call `Poll::reregister`. Is that correct ?

I can try that in Scaproust and let you know about the result.

But that still does not explain why the provided test is [passing with mio 0.6.0](https://ci.appveyor.com/project/blabaere/mio-win-inv/build/1.0.17) and [failing with mio 0.6.1](https://ci.appveyor.com/project/blabaere/mio-win-inv/build/1.0.16), I kept the mio trace activated in case you're interested.

**Comment by blabaere** [comment]
@alexcrichton The proposed solution [did fix the Scaproust tests](https://ci.appveyor.com/project/blabaere/scaproust/build/1.0.409), so for the moment I'll keep it like that but that still feel a bit hacky.

Thanks a lot for your help !

**Comment by blabaere** [comment]
A quick search on msdn brought [this polling function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms741669(v=vs.85).aspx), supported starting Windows 8.1. So is there any hope that one day, when nobody remembers Windows XP, Windows 8.1 being so old that it is the minimum version supported by Rust, we could get mio Linux and Windows have a closer behavior regarding readiness ?

**Comment by carllerche** [comment]
`WSAPoll` is not scalable. If there are a million sockets, an array w/o all million has to be passed in / scanned.

**Comment by alexcrichton** [comment]
@blabaere the behavior of TCP reads changed on Windows between 0.6.0 and 0.6.1, so that's why the update ended up breaking your tests.

And yeah as @carllerche mentioned I don't think we'll be able to use a polling function here.

It looks like, though, that this has been solved, so closing.
