### ISSUE TITLE
`poll.poll()` and `EINTR`

### ISSUE THREAD

**Issue by jedisct1** [carllerche/mio#494]
`poll.poll()` can currently return `io::ErrorKind::Interrupted` when an inner system call is being interrupted. 

As all examples tend to ignore this, I was wondering whether this behavior was intentional, or if the function should silently retry when it happens. I'd be glad to submit a pull request for the later.

**Comment by carllerche** [comment]
It was intentional to not catch it.

There should definitely be a way to call `poll` that doesn't catch `EINTR`, however if that should be the default, I don't know... Also, handling `EINTR` in the examples would add a bunch of noise :P.

Maybe it could be included in the documentation?

**Comment by antrik** [comment]
@carllerche since almost all users need to handle it, and not doing so is a common source of subtle errors, I certainly wouldn't consider having it in the examples as noise. Examples should show good usage -- as a template for actual programs -- not something overly simplified that nobody should actually use as is.

(For the same reason, the examples probably shouldn't use a ridiculously large event buffer, which caused the performance problems in https://github.com/servo/ipc-channel/pull/94 ...)

**Comment by carllerche** [comment]
I would be open to having two fns. `Poll::poll` and maybe `Poll::interruptible_poll` that doesn't handle it.

Thoughts @alexcrichton

**Comment by alexcrichton** [comment]
I'm not currently aware of any concrete use case to actually handle EINTR, so I'd be fine changing the behavior to handle EINTR and just leave the door open to adding a second fn in the future which doesn't handle it.

**Comment by shuoli84** [comment]
@carllerche I noticed the change reverted in 0.7, but could not find any related issues or discussion. Could you pls add some links here?

**Comment by Thomasdezeeuw** [comment]
It was removed in #1056 to reduce the API surface, users can implement this functionally quite easily themselves. Furthermore `EINTR` should be properly handled by the user, e.g. process a signal, usually you shouldn't ignore this return value.

**Comment by shuoli84** [comment]
@Thomasdezeeuw thanks for reply. From other discussions, EINTR actually should be ignored by user in async code. Yes, it is quite easily to implement indeed.

**Comment by jedisct1** [comment]
Does `tokio` also require this?

**Comment by Thomasdezeeuw** [comment]
> Does `tokio` also require this?

What do you mean with this question?

**Comment by jedisct1** [comment]
Do applications using tokio also need to intercept EINTR?

**Comment by carllerche** [comment]
No. If EINTR is not handled it is a bug.
