### ISSUE TITLE
unix awakener writes silly string

### ISSUE THREAD

**Issue by sp3d** [carllerche/mio#495]
See: https://github.com/carllerche/mio/blob/56f8663510196fdca04bdf7c5f4d60b24297826f/src/sys/unix/awakener.rs#L31

As far as I'm aware mio is *trying* to write a single byte to a pipe as a cross-thread wakeup token (can't we use eventfd or such here, on Linux at least?), but actually seems to write the four-byte string "0x01". The contents don't seem important and as far as I'm aware there's no reason to send more than one byte to elicit a wakeup.

If I'm mistaken, it would be worth documenting what's going on here. Otherwise, it should be a trivial fix.

**Comment by alexcrichton** [comment]
Ah good catch! It only need to write one byte, and I think that's actually intended to be `b"\x01"` rather that `b"0x01"` to write a "1" byte into there. Want to send a PR for this?

**Comment by PlasmaPower** [comment]
Can this issue be closed?

**Comment by alexcrichton** [comment]
Indeed!

**Comment by carllerche** [comment]
Thanks for pointing this out.

@sp3d  eventfd can't be used by default because it isn't available on all platforms that mio wants to support (Linux 2.6.18 and up). The work to be able to conditionally detect features has not been implemented.
