### ISSUE TITLE
How to get TcpStream or RawFd in event?

### ISSUE THREAD

**Issue by hicqu** [carllerche/mio#499]
loop {
            poll.poll(&mut events, None).unwrap();
            for event in events.iter() {
                if event.token() == accept_token {
                    let (in_stream, _): (TcpStream, SocketAddr) = server.accept().unwrap();
                    poll.register(&in_stream, client_token, Ready::all(), PollOpt::edge()).unwrap();
                } else if event.token() == client_token {
                    
                    if event.kind().is_hup() {

                    }
                    println!("client token");
                } else {
                    unreachable!();
                }
            }
        }

in my loop, I receive some TcpStream from accept and register them back into poll. But when io event happends on those tcp stream, how to get their TcpStream or RawFd to read something?

I can use a HashMap to store token -> TcpStream. But I don't think that's graceful because I know epoll on Linux can store fd in Event struct. So is there some similar things in mio?
 
thanks a lot!

**Comment by carllerche** [comment]
Right now, the official answer is to use a HashMap or [Slab](https://github.com/carllerche/slab). That being said, `Token` is just a `usize`, so you could convert a `RawFd` -> `Token` and track it that way. This isn't portable and probably doesn't "scale" in terms of code complexity, so it isn't the official solution :) Hope this helps
