### ISSUE TITLE
Alternative to mio::deprecated::unix::UnixStream

### ISSUE THREAD

**Issue by Yamakaky** [carllerche/mio#500]
The doc doesn't indicate an alternative to `mio::deprecated::unix::UnixStream`. I need it to read from a Tun interface, using `FromRawFd`.

**Comment by Yamakaky** [comment]
More background: it's a fd configured with `ioctl` and used combined with `select`. http://backreference.org/2010/03/26/tuntap-interface-tutorial/

**Comment by Yamakaky** [comment]
It works if I use directly `io::Read`, so it's a problem with `mio`/`tokio`.

**Comment by gdf8gdn8** [comment]
Same issue other type of socket. I also missing mio socket interface from `FromRawSocket`

**Comment by carllerche** [comment]
I am hoping that someone else will provide a UDS implementation that is compatible with Mio :) I mostly am trying to limit the amount of code that I must maintain. Also, I plan on moving the deprecated module to a different crate (probably mio-more) but I haven't done so yet. So, it will never just vanish.

**Comment by alexcrichton** [comment]
Ah I've extracted UDS support to a [`mio-uds`](https://github.com/alexcrichton/mio-uds) crate, which I believe should replace the in-tree variants. Additionally there are tokio bindings through [`tokio-uds`](https://github.com/tokio-rs/tokio-uds).

**Comment by Yamakaky** [comment]
Cool!
