### ISSUE TITLE
Is there a real world benchmark for Libuv and MIO ?

### ISSUE THREAD

**Issue by tigranbs** [carllerche/mio#501]
One of my projects using `Libuv with Rust bindings`, and now I'm thinking of rewriting it with MIO, but before making about a month coding, I'm trying to find any caparison between them.
From basic `TCP Echo` on MIO and Libuv, I saw that MIO is eating more memory and CPU than Libuv on same load, but I know that it is unfair benchmark.

So I'm just curios is there any benchmarks for MIO and Libuv ?

Thanks

**Comment by carllerche** [comment]
There aren't any benchmarks currently. However, Mio on *linux* should have exactly the same performance characteristics as using epoll directly. So, if there are any comparisons between libuv and epoll, that should be equivalent to libuv and mio (if it isn't, then it is a bug).

Also, if you are willing to contribute benchmarks, that could work too :)

**Comment by tigranbs** [comment]
Ok, then I'll definitely prepare few benchmarks during the weekend !
It's quite interesting to see code style differences and resource usage differences.

**Comment by tigranbs** [comment]
Just made some very simple TCP Echo server using MIO, but I think I'm doing something wrong, because it is just eating a lot of memory.
https://github.com/tigranbs/libuv-vs-rustmio - code located here
I made also some simple tool for benchmarking with `Go`.

It seems my `TCP echo` server is adding Write Queue for connection but it doesn't have time to clear write buffer.
Take a look if you will have some time

Working on Libuv example

**Comment by adwhit** [comment]
No idea if this is related but a fix recently landed in tokio-core that should hugely reduce the memory consumption of starting a new event loop: tokio-rs/tokio-core#124

**Comment by hjr3** [comment]
@tigranbs I opened https://github.com/tigranbs/libuv-vs-rustmio/pull/1 to try and help with the memory usage.

**Comment by tigranbs** [comment]
Done both basic TCP echo server implementations, and it is super strange but MIO is about _8 times_ slower than Libuv implementation. Maybe we did some wrong implementations for MIO.
https://github.com/tigranbs/libuv-vs-rustmio

When I'm transferring `2MB file with 100 concurrent connections` Libuv implementation is able to handle about `~800MB/s - 1.2GB/s` but MIO implementation is handling only `~60-100MB/s`.

I'm on Macbook Pro i7 Quad core 2.2Ghz

**Comment by alexcrichton** [comment]
@tigranbs I didn't look too closely at the mio implementation you have specifically, but I'd be surprised if mio is 8 times slower than libuv as mio is just epoll, which libuv itself is built on. I saw some buggy behavior with the mio implementation, however, so I opted to do something a little different.

Using [this script](https://gist.github.com/alexcrichton/94841db4d2a8c9dc7bf8a51b0d99756e) to print out read/write speeds (this should be the same as `bc.go`) I benchmarks `tcp_uv` in that repo and got:

```
$ ./bc 127.0.0.1:8888 100 LICENSE
write: 2885532933/s   read: 1880936229/s
write: 1814786663/s   read: 1814639472/s
write: 1824485579/s   read: 1824786744/s
write: 1776131563/s   read: 1776416256/s
write: 1763445662/s   read: 1763556448/s
write: 1756487744/s   read: 1755897224/s
```

e.g. ~1.7GB transfer speed overall

I then benchmarked `tokio-core`'s [`echo` example server](https://github.com/tokio-rs/tokio-core/blob/master/examples/echo.rs). This server is built on top of the Tokio/futures stack, but at its heart is mio itself, so it's a good proxy for mio's performance. When benchmarking I got:

```
$ ./bc 127.0.0.1:8080 100 LICENSE                    
write: 2567858293/s   read: 1921725031/s
write: 2076446549/s   read: 2035820796/s
write: 2391274768/s   read: 2159096968/s
write: 2207487338/s   read: 2135928046/s
write: 2122481259/s   read: 2122494701/s
write: 2142195360/s   read: 2142184022/s
write: 2158360220/s   read: 2158493696/s
write: 2133058700/s   read: 2132553728/s
```

which was about 2.1GB/s

So at least from this test mio isn't 8x slower than libuv. Are you sure that your mio server was written correctly? I saw connections drop off quickly and didn't progress much as I'd expect.

Also, how were you measuring speeds? Did you have a different program monitoring the transfer rate?

**Comment by tigranbs** [comment]
@alexcrichton I'm monitoring from `bmon` which is displaying read writes per interface/process, but you are right based on `Libuv` design `MIO` is lower level than `Libuv`, so it seems I have a wrong example for MIO, will try to fix it for fare benchmarking ... But `tokio-core` results is impressive 👍 
will check it out ...

**Comment by carllerche** [comment]
I'm going to close this issue for now. If someone comes up with a benchmark, I would suggest opening a PR w/ the data.

Thanks for the work.
