### ISSUE TITLE
More ergonomic handling of file descriptor-based structures

### ISSUE THREAD

**Issue by Kixunil** [carllerche/mio#502]
I suggest creating a wrapper, let's call it `EventedAsFd` for now, for all types that impl `AsRawFd`.

The current situation is that if I want to use something outside mio (e.g. Unix socket) I need to write code like this:

```rust
let uds = try!(UnixStream::open(&path));
let raw_fd = uds.as_raw_fd();
let evented_fd = EventedFd(&raw_fd);
poller.register(&evented_fd, /*...*/)
```

I find this long and it may also be less obvious what is the goal of the code. On the other hand, with `EventedAsFd` it'd look like this:

```rust
let uds = EventedAsFd::new(try!(UnixStream::open(&path)));
poller.register(&*uds, /*...*/);
```

I already tried to make some basic implementation and it seems to work well. Anyway, I wanted to ask whether there is some good reason to *not* do this. What do you think?

In case this is considered useful, I'll create a PR.

**Comment by alexcrichton** [comment]
cc @carllerche

**Comment by ipetkov** [comment]
Interested in this as well.

I've got my own wrapper that implements `{As,Into}RawFd` which also handles cleanup. I have a use case where I'd like to pass ownership of the handle to the `EventedAsFd` (to potentially keep things `'static` going up the tower of abstractions), so it would be good that the wrapper **not require** a reference the way `EventedFd` does

**Comment by ipetkov** [comment]
Took a closer look at the source, seems like I can accomplish my needs today by just implementing `Evented` on my wrapper similar to [this](https://github.com/carllerche/mio/blob/0e21ae3e4090a32337eae22d52fa11b71b1f0b47/src/sys/unix/tcp.rs#L103-L117), but it would be nice for upstream crates to get a quick wrapper like `EventedAsFd`

**Comment by carllerche** [comment]
The friction is intended. This is now documented.

**Comment by Kixunil** [comment]
Where is it documented? I didn't find it in docs.

**Comment by carllerche** [comment]
https://docs.rs/mio/0.6.11/mio/unix/struct.EventedFd.html

> Note that EventedFd takes a &RawFd. This is because EventedFd does not take ownership of the FD. Specifically, it will not manage any lifecycle related operations, such as closing the FD on drop. It is expected that the EventedFd is constructed right before a call to Poll::register. See the examples for more detail.

**Comment by Kixunil** [comment]
Well, it's not clear to my *why* the friction is intended.

**Comment by carllerche** [comment]
So that people don't do EventedFd(RawFd) and leak sockets everywhere (aka, what happened before).

**Comment by Kixunil** [comment]
In that case you most probably misunderstood my proposal. I don't remember the details exactly, since this was a long time ago, but If I'm not mistaken, the idea was to do something like this:

```rust
struct EventedAsFd<T: AsRawFd> {
    inner: T,
}

impl<T: AsRawFd> Deref for EventedAsFd<T> {
    type Target = T;
    // obvious impl; sae with DerefMut
}

impl<T: AsRawFd> Evented for EventedAsFd<T> {
// Delegate everything to EventedFd(&self.inner.as_raw_fd())
}
```

This would simply wrap the type and not leak any socket anywhere.
