### ISSUE TITLE
Getting 'No such file or directory (os error 2)' error on Linux for reregister function call

### ISSUE THREAD

**Issue by tigranbs** [carllerche/mio#505]
I'm using `MIO 6.0` in multithreaded application, and seems all working super well on Mac, but today when I've tried to compile and run on `Ubuntu 16.04 server` on second time reregister for `Poll` I'm getting `No such file or directory (os error 2)` error.
Can't figure out what could be wrong. Code looks like something like this
```rust
......
......
// Thread1
poll.register(&socket, token, Ready::readable(), Pollopt::edge()).unwrap();
......
.....
// at some point moving TcpStream socket from Thread1 to Thread2 poll2
poll.deregister(&socket);
......

// Thread2
.......
// Error is here only on Linux
poll2.reregister(&socket, token, Ready::readable(), Pollopt::edge()).unwrap();
```
I found closed issue with the same error, but it wasn't something that could solve my problem.
Where should I look to find out what happening ?

**Comment by alexcrichton** [comment]
Is the socket here a standard `TcpStream` or the like from the mio crate? The standard mio types shouldn't be able to get registered with more than one event loop (even after deregistration).

**Comment by tigranbs** [comment]
It's a `Mio TcpStream`, is there something changed from version 0.4? Because I remember I've done something like this for that version. 

What can I do to move socket from one loop to another? is it possible to recreate mio TcpTream from existing one?

**Comment by tigranbs** [comment]
I solved problem by using [`TcpStream::try_clone()`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.try_clone) function, which is probably not wrong approach :)
So basically I'm cloning `Mio TcpStream` when I'm accepting it, then when I want to transfer TcpStream from one loop to another, I'm just deregistering 1st TcpStream and registering cloned stream to 2nd loop.
```rust
struct Conn {
    socket1: TcpStream,
    socket2: TcpStream
}

......
......
let (sock, _) = server.accept().unwrap();
let conn = Conn{
    socket2: sock.try_clone(),
    socket1: sock
};
.........
// Thread1
poll.register(&conn.socket1, token, Ready::readable(), Pollopt::edge()).unwrap();
......
.....
// at some point moving TcpStream socket from Thread1 to Thread2 poll2
poll.deregister(&conn.socket1);

// Thread2
.......
// Error is here only on Linux
poll2.register(&conn.socket2, token, Ready::readable(), Pollopt::edge()).unwrap();
```   

Closing this issue, because I'm actually solved my problem (but don't know is it a good approach or not).

**Comment by alexcrichton** [comment]
Ah ok I see, mio 0.4 didn't have the same restriction that mio 0.6 has today.

The restriction is currently in place because on Windows you can't move a socket between event loops, so to have a cross platform interface mio disallows this behavior on Unix as well. Note, though, that using `EventedFd` allows working around this restriction as it's unix-specific.
