### ISSUE TITLE
Cannot re-register channels 

### ISSUE THREAD

**Issue by ekr** [carllerche/mio#506]
Deregister doesn't seem to do what you want here:

```
    let (_, rxf) = channel::channel::<i32>();
    
    let poll = Poll::new().unwrap();
    poll.register(&rxf, mio::Token(0), Ready::readable(),
                  PollOpt::level()).unwrap();
    poll.deregister(&rxf).expect("Deregister failed");

    let poll2 = Poll::new().unwrap();
    poll2.register(&rxf, mio::Token(0), Ready::readable(),
                  PollOpt::level()).unwrap();
```

Produces:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("receiver already registered") }) }', ../src/libcore/result.rs:799
```

**Comment by alexcrichton** [comment]
This is currently intentional, channels can only ever be associated with one event loop. Note that channels are sort of being phased out in favor of external queues/channels built on top of SetReadiness and such.

**Comment by ekr** [comment]
This seems like a fairly undesirable feature. What you want is for all types of registerable objects to behave identically. What's the reasoning for why a socket should be reregisterable but a channel not to be?

**Comment by alexcrichton** [comment]
A socket isn't? Socket's can't cross event loops by default.

**Comment by ekr** [comment]
I have to admit, I hadn't tested that, just assumed it wasn't the case. That does not seem like an acceptable limitation for networking programs. Even select() lets you do that! Do you have some argument why this is a good design from the API consumer's perspective?

**Comment by alexcrichton** [comment]
Mio is a cross-platform library, including Windows. Sockets can't cross IOCP handles on Windows. To make mio cross-platform, sockets can't cross event loops by default.

**Comment by ekr** [comment]
I'm not that experienced with Windows network programming, so I can't speak
to how IOCP behaves. At least with Winsock and select() there is no such
restriction. In any case, the fix for this is to (on windows) add another
layer of indirection that owns the socket and then provides a portable
handle to the application programmer, rather than to important the lowest
common denominator onto every program.

**Comment by carllerche** [comment]
I'm going to close this for now, channels have been deprecated and will not be seeing any further changes. If you want to maintain a channel implementation in a separate crate that supports reregistering, please do so :) You can use the existing channel as a starting point.
