### ISSUE TITLE
Doc to upgarde from 0.5 to 0.6

### ISSUE THREAD

**Issue by neodc** [carllerche/mio#509]
Hello,

I used the version 0.5 of mio and now see that a new version is out, I'd like to upgrade but I do not see any guide to do so.

I tried to just look at the doc to see what is the new way of doing but it seems really different (for example I don't see clearly how is now implemented the old "timeout" and "notify" method of the handler).

Is there any guide/article on how to upgrade to 0.6 ?

**Comment by alexcrichton** [comment]
Currently there are no guides to upgrade to 0.6 that I'm aware of. The gist of the changes are:

* The `Handler` type was "removed" (just deprecated for now)
* Instead you should use `Poll` and `Events`
* You construct the "loop" manually by calling `Poll::poll` in a loop
* You dispatch events manually, essentially calling your own "ready callback"
* Queues are available in `mio::channel`, but these are being phased out in favor of `SetReadiness`
* Custom objects can be registered with a `Poll` through `SetReadiness` and `Registration`

**Comment by ehiggs** [comment]
The docs still refer to EventLoop with some dead links.

**Comment by carllerche** [comment]
I added this to the meta doc issue: #509.

I cleaned up a bunch of outdated docs. If there still are references to `EventLoop`, please open a separate issue for that.
