### ISSUE TITLE
"type alias is never used: `Tick`" compile error on nightly.

### ISSUE THREAD

**Issue by kkimdev** [carllerche/mio#511]
Compiler: rustc 1.16.0-nightly (6f1ae663e 2017-01-06)

> error: type alias is never used: `Tick`
>    --> /home/kkim/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.2/src/poll.rs:157:1
>     |
> 157 | type Tick = usize;
>     | ^^^^^^^^^^^^^^^^^^
>     |
> note: lint level defined here
>    --> /home/kkim/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.2/src/lib.rs:76:24
>     |
> 76  | #![cfg_attr(unix, deny(warnings))]
>     |                        ^^^^^^^^
> 
> error: aborting due to previous error
>

**Comment by kkimdev** [comment]
@alexcrichton It seems like this is due to `#![cfg_attr(unix, deny(warnings))]` in `lib.rs` that turns warnings inin errors.  I think this is good to have it, but since future compiler upgrade can introduce more warnings like this, maybe we should enable this attr only for testing infrastructure only?

**Comment by alexcrichton** [comment]
@kkimdev this attribute shouldn't regress any builds due to Cargo passing `--cap-lints`. That being said, PRs to fix the warning are of course always accepted!

**Comment by kkimdev** [comment]
Oh, I see.  Hmm it's weird, I also was using cargo to build mio (as a dependency of my project) at the time I filed this issue, but now it's gone :) .

**Comment by sanxiyn** [comment]
I already submitted PR: #510.

**Comment by alexcrichton** [comment]
Ok, #510 is merged
