### ISSUE TITLE
mio::io::MapNonBlock should be public?

### ISSUE THREAD

**Issue by SpamapS** [carllerche/mio#512]
With the deprecation of TryWrite, there's no replacement. The deprecated one just calls on the MapNonBlock trait. I'm left vendoring MapNonBlock into my program so I don't have to import deprecated mio's and don't have to maintain the implementation.

Perhaps this should be made public.

For example, the code used to be:
```
use mio::deprecated::TryWrite;

match socket.try_write(buf)? {
    None => break,
    Some(len) => // do stuff,
}
```

Now it would be

```
use std::io::Write;
use mio::io::MapNonBlock;

match socket.write(buf).map_non_block()? {
    None => break,
    Some(len) => // do stuff,
}
```

Thanks for your time.

**Comment by carllerche** [comment]
Thanks for the report. `TryRead` and `TryWrite can live in a separate crate. There will be something similar provided by Tokio soon. The goal for Mio is to slim it down as much as possible, so map_non_block will not be exposed.

I also moved as much as possible of the deprecated code to [mio-more](https://github.com/carllerche/mio-more)
