### ISSUE TITLE
How to read Unicode codepoints from an unbuffered file in a mio event loop?

### ISSUE THREAD

**Issue by vext01** [carllerche/mio#515]
Hi,

This isn't really a bug, but maybe it will result in a feature request. This PR is based upon:
http://stackoverflow.com/questions/41224854/how-to-read-unicode-codepoints-from-an-unbuffered-file-in-a-mio-event-loop

I'd like to use the mio crate to read keypresses as they arrive in an unbuffered fashion. I already have the code to unbuffer stdin, and I have scaffolded the event loop:

    extern crate mio;
    extern crate termios;
    
    use termios::{Termios, TCSANOW, ICANON, ECHO, tcsetattr};
    use mio::*;
    use mio::unix::EventedFd;
    
    fn unbuffer_stdin() {
        let termios = Termios::from_fd(0).unwrap();
        let mut new_termios = termios.clone();
        new_termios.c_lflag &= !(ICANON | ECHO);
        tcsetattr(0, TCSANOW, &mut new_termios).unwrap();
    }
    
    fn main() {
        let stdin = 0;
        unbuffer_stdin();
    
        let poll = Poll::new().unwrap();
    
        const STDIN: Token = Token(0);
        let ev_fd = EventedFd(&stdin);
        poll.register(&ev_fd, STDIN, Ready::readable(), PollOpt::edge()).unwrap();
    
        let mut events = Events::with_capacity(1024);
        loop {
            poll.poll(&mut events, None).unwrap();
    
            for event in events.iter() {
                match event.token() {
                    STDIN => {
                        println!("keypress");
                        // XXX read in ready codepoints to a buffer
                    }
                    _ => unreachable!(),
                }
            }
        }
    }

How do I implement the part marked `XXX`? There are a couple of challenges:

 * How do I know how many bytes to read? I'm not sure mio tells me this.
 * How do I deal with partial codepoints, where the read spans a multi-byte character.

One solution that might work is to use `oneshot` events instead of `edge` events, then read one byte per event into a temporary buffer. Each time the buffer makes sense as a complete codepoint, I could then convert it to a `char` and store it away, and clear the scratch buffer.

This seems a little inefficient though. Is there a better way? If not, should there be?

Thanks

**Comment by alexcrichton** [comment]
In general epoll doesn't know how much data you should read, that's up to you to figure out. You typically have to just read bytes using the `read` syscall until you get "would block" as an error.

With partial code points that's up to the underlying terminal, I'm not sure how those work but I don't believe it's related to mio specifically.

**Comment by hjr3** [comment]
@vext01 you need to implement a protocol, such as HTTP or MsgPack. If you want to keep things real simple, you can send a `u64` at the start of a message to specify how many bytes to read. I have an example of this in https://github.com/hjr3/mob/blob/master/src/connection.rs#L62

**Comment by vext01** [comment]
@alexcrichton Thanks. I was unaware of the `WouldBlock` error type. That certainly makes this tractable. I'll try it out when I find some time and let you know how it goes.

@hjr3 I think your comment relates to how to deal with partial codepoints? I'm more likely to simply "buffer up" bytes which are not yet a valid codepoint and deal with them on the next read. @alexcrichton's idea should solve the actual I/O element of my problem.

**Comment by vext01** [comment]
Alex,

So I think you mean I should use [read](https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/fn.read.html) from the `libc` crate until I get `-1` and `errno` is `EAGAIN`?

 Do I need to do anything special to mark the FD for non-blocking IO? If I were to use [fcntl](https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/fn.fcntl.html) from the same crate would that work?

**Comment by alexcrichton** [comment]
@vext01 yeah if you're working with stdin you likely want to use the raw syscalls yourself, setting it to nonblocking mode w/ fcntl and then calling `read`

**Comment by carllerche** [comment]
Hopefully you figured things out. Since there hasn't been any recent activity, I'm going to close this issue. Feel free to open a new one if you hit any other problems.
