### ISSUE TITLE
Impossible(?) to register more complicated kevents

### ISSUE THREAD

**Issue by nagisa** [carllerche/mio#524]
So, the `kqueue` is something more generic than `epoll` in a sense that it can do extra stuff such as getting notifications for signals, file changes, process status changes and can be even used to implement a message passing of some sort.

So here am I, trying to write a kqueue-specific `Evented` impl (to be used with tokio-core Core) which I could use to set up `kevent`s using these extra functionalities available. The problem is, that `mio` exposes nowhere near to enough to actually make these `kevent` calls happen:

* `mio::sys::unix::kqueue::Selector`, which is the wrapper over `kqueue` descriptor is private to the crate;
    * Just exporting it wouldn’t be enough as `mio::sys::unix::kqueue::Selector::ev_register` does not expose the full functionality of the `kevent`;
* The public interface of `Poll`, `Ready` and `PollOpt` only exposes (rightfully-so) very bare-bone functionality.
    * `Poll::selector` is private API, so getting a `Selector` out of `Poll` is impossible.

The only other idea I have currently is to maintain a separate kqueue and poll *its* descriptor for read-ability, but I would like to avoid that and am not even sure if it would work -- haven’t had an opportunity to test it yet.

**Comment by carllerche** [comment]
Could you elaborate more on what you are trying to do specifically w/ kqueue? It would be helpful input to help determine the appropriate changes.

**Comment by nagisa** [comment]
My specific goal is to have `kevent(kq_inside_poll, changelist, cl_n, NULL, 0, 0)` called where `kq_inside_poll` is the descriptor returned by `kqueue` and the changelist contains a list of:

```
kevent {
  ident: fd,
  filter: EVFILT_VNODE,
  flags: EV_ADD, // arbitrary flags, really, what PollOpt provides here is plenty for me
  fflags: any_combination_of(NOTE_DELETE, NOTE_WRITE, NOTE_EXTEND, ...),
  data: 0 // not needed,
  udata: 0 // not needed
},
kevent {
  ident: pid,
  filter: EVFILT_PROC,
  flags: EV_ADD, // arbitrary flags, really, what PollOpt provides here is plenty for me
  fflags: any_combination_of(NOTE_EXIT, NOTE_FORK, ...),
  data: 0 // not needed,
  udata: 0 // not needed
},
kevent {
  ident: any signal,
  filter: EVFILT_SIGNAL,
  flags: EV_ADD, // arbitrary flags, really, what PollOpt provides here is plenty for me
  fflags: 0, // not needed
  data: 0 // not needed,
  udata: 0 // not needed
},
```

I’ll be checking shortly if I one can setup a `kevent` for a `kqueue` descriptor – if so this will become much lesser in priority for me.

**Comment by nagisa** [comment]
Thinking about it now, I would also need to be able to inspect the raw `kevent`s in order to extract the useful information back. So, all in all, it seems like polling on a separate `kqueue` is all in all the approach to use, even if its not quite 0-cost.

**Comment by carllerche** [comment]
The PR you submitted a bit ago was merged. I'm going to close this assuming that your issue has fixed. If there is anything else, please open a new issue.
