### ISSUE TITLE
S3 creds in .travis.yml

### ISSUE THREAD

**Issue by oyiptong** [carllerche/mio#530]
Is this intentional?

https://github.com/carllerche/mio/blob/4337e9561d2f211588b21de649db383f61e68d05/.travis.yml

**Comment by carllerche** [comment]
Can you point out which specicislly concerns you? The secret key is
encrypted, so it shouldn't be usable by anyone?

**Comment by oyiptong** [comment]
nevermind, i thought it was in the clear and should've been put in travis environment variables
