### ISSUE TITLE
Determine custom readiness queue behavior

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#535]
## Edge behavior under reregister

* Register w/ `read` interest
* Become readable
* Don't consume read
* Reregister w/ `read` +`write`
* Should another `read` notification fire?

**Comment by carllerche** [comment]
I'm going to assume this is done. I don't remember what this issue was about.

**Comment by twmb** [comment]
Comment referencing this issue, for context: https://github.com/carllerche/mio/blob/master/src/poll.rs#L1963-L1970
