### ISSUE TITLE
Is `fn registered(&self) -> usize` for `Poll` necessary?

### ISSUE THREAD

**Issue by hicqu** [carllerche/mio#540]
I think this API is useful:
```rust
impl Poll {
    // something ...

    /// return how many `Evented` are registered into the poll.
    pub fn registered(&self) -> usize {
        // something ...
    }
}
```
so that we can know it's OK or not to break the loop like this,
```rust
loop {
    poll.poll(&mut events).unwrap();
    poll.deregister(&something as &EventedFd);
    if poll.registered() == 0 {
        break;
    }
}
```
What do you think?

**Comment by carllerche** [comment]
Thanks for submitting the issue. The high level rule of thumb for new APIs is whether or not it is possible to implement externally to Mio (aka, w/o having access to the system handles / internal details). We are trying to reduce the API surface as much as possible in favor of implementing more features in other crates. Tracking the number of registered handles could be implemented as part of a wrapper to Poll, so I would say that this functionality would be better suited in a different crate. Hopefully this makes sense.

**Comment by hicqu** [comment]
Ok, thank you!
