### ISSUE TITLE
the timer thread never exits and can not deconstruct the pipe in poll.

### ISSUE THREAD

**Issue by hicqu** [carllerche/mio#541]
Here is a snippet of code:
```rust
extern crate mio;
use std::{thread, time};
use mio::*;
use mio::timer::*;

fn func() {
    let poll = Poll::new().unwrap();
    let mut timer = Timer::default();
    timer.set_timeout(time::Duration::new(2, 0), 0);
    poll.register(&timer, Token(0), Ready::readable(), PollOpt::edge()).unwrap();

    let mut events = Events::with_capacity(3);
    loop {
        poll.poll(&mut events, None).unwrap();
        for event in events.iter() {
            println!("event: {:?}", event);
        }
        timer.poll();
        poll.deregister(&timer);
        break;
    }
}

fn main() {
    loop {
        func();
        thread::sleep(time::Duration::new(10, 0));
    }
}
```

After launch that up, we can see there are 2, 4, 8, ... file descriptors opened as pipe:
```bash
$ ps aux|grep mio_learn
qupeng    9850  0.0  0.1  25144  9768 pts/3    Sl+  15:55   0:00 ./target/release/mio_learn

# qupeng@arch-dev: ~ [15:55:09]
$ lsof -p 9850|grep pipe
mio_learn 9850 qupeng    4r  FIFO   0,10      0t0   24211 pipe
mio_learn 9850 qupeng    5w  FIFO   0,10      0t0   24211 pipe
mio_learn 9850 qupeng    6r  FIFO   0,10      0t0   24215 pipe
mio_learn 9850 qupeng    7w  FIFO   0,10      0t0   24215 pipe
```

And the number of pipes is still growing up.

**Comment by hicqu** [comment]
I have tryed to resolve this problem but I failed. Anyone could help me on this?

**Comment by hicqu** [comment]
@carllerche ，could you help me on this?
I don't know it is a bug or just because I use timer in a wrong way.

**Comment by przygienda** [comment]
I don't think you use the stuff correctly, here are some code snippets 

`
let timerbuilder: Builder = Builder::default()
			.num_slots(5) // 5 timers per slot
			.capacity(10) // 10 timers, we don't run anything much
			.tick_duration(*RES);

		let mut tic = timerbuilder.build();

self.poll
			.register(&tic,
					  Token(tic_token_val as usize),
					  Ready::readable(),
					  PollOpt::edge())
			.unwrap();

for event in events.iter() {
				 match usize::from(event.token()) {
					v if v == tic_token_val as usize => {
						// cancel done tic
						if let Some(ref t) = self.shorttimer {
							tic.cancel_timeout(t);
						}
						// add event to the FSM
						self.shorttimer = None;
						match self.fsm
							.process_shorttic() {
							Ok(_) => Ok(()),
							Err(e) => {
								crit!(&self.log, "{:?}",e);
								...
							}
						}
					},

---

                                           Message::StartShortTimer(duration) => {
										// tic timer
										tic.set_timeout(duration, SHORTTOKEN)
											.map_err(SubSystemError::TimerError)
											.and_then(|t| {
												self.shorttimer = Some(t);
												Ok(())
											})
									},
						Message::StopShortTimer => {
										if let Some(ref t) = self.shorttimer {
											tic.cancel_timeout(t);
										}
										self.shorttimer = None;
										Ok(())
									},
`

if you have multiple timers created and set with set_timeout ( ... TOKEN ) you have poll on an edge via ... 

`
while let Some(timer_number) = timers.poll() {
									// error!(log,"tic poll gave {}", timer_number);

									try!(if timer_number == tic_timer {
...
`

**Comment by zonyitoo** [comment]
@przygienda I think you have misunderstood @hicqu 's issue. What he pointed out is the wake up thread that is created by [`spawn_wakeup_thread`](https://github.com/carllerche/mio/blob/master/src/timer.rs#L421) will never exit even you have destroyed the `Timer` instance.

In the body of this thread, it will [`park`](https://github.com/carllerche/mio/blob/master/src/timer.rs#L448) forever if no one calls [`unpark`](https://github.com/carllerche/mio/blob/master/src/timer.rs#L336).

One simple solution is to `impl` `Drop` for `Inner`, set `self. wakeup_state` to `TERMINATE_THREAD` and `unpark` the wakeup thread.

I think this issue should be reopen @hicqu .

cc @carllerche

**Comment by carllerche** [comment]
I'll reopen it for now, but the given that the timer is deprecated and it is a relatively minor issue, I will personally not be attempting to fix it. If somebody wants to take a shot at a PR though, I could merge it.

**Comment by zonyitoo** [comment]
This issue has been fixed in the latest commit. So this could be closed. @carllerche 
cc @hicqu
