### ISSUE TITLE
reusing socket causes "socket already registered" error.

### ISSUE THREAD

**Issue by chamaken** [carllerche/mio#542]
Hi,

I'm trying to implement [libmnl example send_batch()](http://git.netfilter.org/libmnl/tree/examples/netfilter/nfct-create-batch.c) by mio, but reusing socket causes "socket already registered" error. Its test might be represented by 0343997c1e946f28e6f31cb78b7799e94ddec01e and seems to be fixed 991019ecfbd3dee2c6232c04c0ef5ff4c8463d01 only for TCP. I'm new to rust and mio, so that I hope someone fix it in a right way.

Thanks,

**Comment by alexcrichton** [comment]
I believe this is currently exercising functionality which isn't supported by mio, namely registering an I/O object on multiple event loops (even if an explicit deregister is used).

If you need to support this use case, though, you can use `EventedFd` which should do the trick on Unix (note that this is unfortunately fundamentally incompatible with Windows).

**Comment by chamaken** [comment]
Thanks for telling me using `EventedFd`, it solved the issue.
