### ISSUE TITLE
deprecation points at non-existent crate

### ISSUE THREAD

**Issue by dimbleby** [carllerche/mio#573]
>  warning: use of deprecated item: use mio-more instead

But `mio-more` is not published so I can't use it.  Please either publish `mio-more`, or change the warning to say something that more accurately reflects what I ought to do.

I considered raising this issue at the `mio-more` repository rather than here, but since that repository says that it is "not actively maintained" that doesn't seem to make a lot of sense.  

Also, this doesn't sound very encouraging - should I really be using unmaintained code dumped into `mio-more`, or is there some better alternative?

(It's the `mio::channel` that I currently use - and I would like to be able to keep using it, or something equivalent).

**Comment by carllerche** [comment]
Sorry about the confusion. I didn't get around to pushing mio-more. It exists in a git repository though.

The goal w/ mio is to reduce it down to the core set of features needed to implement things like channels. Given that channels could be implemented out of crate, I opted to move them out. Reality is that my time is already pretty thin, so unless somebody else steps up (perhaps you?) to maintain tokio-more it won't get much attention. The deprecation notice points to mio-more as this repository contains the exact same code. I'm not trying to make false promises, so people can see the readme and decide if they wish to continue using it or not.

**Comment by dimbleby** [comment]
You wrote 'tokio-more' above, but that doesn't exist either does it?!  Did you mean 'mio-more' again, or 'tokio-core', or ... ?

However, that did lead me to notice that `tokio-core` also depends on the `mio::channel`.  What's the plan over there for dealing with this deprecation, do you know?  Perhaps I'll just wait and do whatever they do...

Appreciate that your time is thin and I'm nothing but grateful for all the hard work.

**Comment by alexcrichton** [comment]
Ah yeah the tokio-core channel based on mio::channel is *also* deprecated! The non-deprecated channel is actually `futures::sync::mpsc` (intended for use with the `futures` crate).

The general trend is that some of the "goodies" in the mio crate have migrated to the futures/tokio ecosystem with more efficient, ergonomic, robust, and flexible implementations. As a result there's not much desire to maintain separate copies in mio itself as mio is largely targeted at the foundation for tokio-core nowdays (and the rest of the Tokio stack)

**Comment by dimbleby** [comment]
Yes, I see. 

Well, an `Evented` channel is exactly what I want: I have an event loop that's using a `mio::Poll` to poll file descriptors, and I want to be able to send instructions to that event loop.

(I understand that tokio is likely the primary user of mio, and surely the driver for recent changes.  But I hope that mio also aims to be useful for other users - and the situation I describe doesn't sound as though it ought to be very unusual).

So back to plan A: can you please publish `mio-more`?

As for maintenance of that code: I'm reluctant to volunteer to own something that I don't honestly understand.  I expect I'll be willing to submit simple updates as necessary eg to match simple mio API changes, but I don't think I should promise more than that.

So long as it's not broken, though, I guess there's no problem...

**Comment by carllerche** [comment]
I'll definitely push out a `mio-more` release before deleting any code, but it is low priority for me right now since nothing is broken yet.

**Comment by dimbleby** [comment]
Super, thanks!

**Comment by thejpster** [comment]
I just wanted to chime in here and say I have the same use case - I'm using a task running mio to poll a bunch of sockets, but I use a channel to tell the task to add/remove sockets to the list.

**Comment by carllerche** [comment]
Released: https://crates.io/crates/mio-more
