### ISSUE TITLE
mio's TcpStream::write() SIGPIPEs

### ISSUE THREAD

**Issue by SalmonProject** [carllerche/mio#577]
I have been getting SIGPIPE crashes once in a great while (when our system is under significant load) from TcpStream::write(). I'm not really sure what's going on; all I can say for sure is that these SIGPIPEs only happen in TcpStream::write(), and that when they do happen, the offending TcpStream had a `None` `peer` field.

This is with mio 0.6.5 on Linux. Let me know if there's any other information that would be useful, or specific things we can test for that might help you out (I'm guessing this might be hard for you or anyone else to reproduce).

**Comment by alexcrichton** [comment]
This seems quite odd! Are you running a pure rust program? Or perhaps a rust program embedded in a different environment? Rust [ignores SIGPIPE by default](https://github.com/rust-lang/rust/blob/ccce2c6eb914a66571f60fa0afe8a46faa9fb3bd/src/libstd/sys/unix/mod.rs#L93-L98) when you start a Rust program, but if you're embedded in a different runtime then you may be responsible for taking care of that.

If it's a rust program then it seems quite odd why that may be showing up!

**Comment by SalmonProject** [comment]
Thanks, I wasn't aware that there was that difference between a Rust program and a Rust library called from something else. As you guessed, this is a Rust library called from a C program that uses a named pipe to talk to another process. Looks like just ignoring them is the way to go, then. It's always good when the (correct and clean) solution is that easy!

**Comment by alexcrichton** [comment]
Ok cool, if you need any help with an implementation just let me know!
