### ISSUE TITLE
how to reuse TcpStream code from src/sys/windows/tcp.rs ?

### ISSUE THREAD

**Issue by Dushistov** [carllerche/mio#578]
cc @alexcrichton @carllerche 

I want to work with `AF_BTH` socket on windows OS,
to demonstrate what I am talking about here some code (blocking variant):

```rust
//create
let bt_socket: SOCKET = unsafe { socket(AF_BTH, SOCK_STREAM, BTHPROTO_RFCOMM) };
//skip error handling
let mut sock_addr = SOCKADDR_BTH {
      addressFamily: AF_BTH as USHORT,
      btAddr: bt_addr.into(),
      serviceClassId: RFCOMM_PROTOCOL_UUID,
      port: BT_PORT_ANY,
};
let sock_addr_ptr: *mut SOCKADDR_BTH = &mut sock_addr;
let err = unsafe { connect(socket, sock_addr_ptr as *mut SOCKADDR, mem::size_of_val(sock_addr) };
```
As I understand comments from [lib.rs](https://github.com/carllerche/mio/blob/master/src/lib.rs) and [windows mod.rs](https://github.com/carllerche/mio/blob/master/src/sys/windows/mod.rs) I basically need not only use `windows::Binding` to imlement `mio::Eventd`, but also starts `I/O` with overlapped structures on readiness request, so basicaly copy/paste code from [windows/tcp.rs](https://github.com/carllerche/mio/blob/master/src/sys/windows/tcp.rs) and modify for my need, am I right?

If so, do you accept PR that generalize [windows/tcp.rs](https://github.com/carllerche/mio/blob/master/src/sys/windows/tcp.rs) to any `SOCK_STREAM` and allow some kind of user defined connect and socket creation functions?

**Comment by alexcrichton** [comment]
I'd recommend taking a look at [mio-named-pipes](https://github.com/alexcrichton/mio-named-pipes) which are named pipes for mio, which you'll also likely want to mirror. In general though yes, you'll want to copy code from tcp.rs and adapt it as appropriate, it won't ever be publicly exposed from mio itself.

**Comment by Dushistov** [comment]
@alexcrichton I looked at mio-named-pipes, looks a lot of code duplication
with mio/sys/windows, do you have plans refactoring?

For example, why not just call in `Binding::register_socket/register_handle`
approapriate schedule functions?

**Comment by carllerche** [comment]
I don't think we are going to extract that as an official mio API. The main
reason is that it creates additional API surface to support and resources
are thin.

However. Feel free to extract those bits to another crate.

**Comment by alexcrichton** [comment]
Currently no I don't plan on deduplicating, I'd personally prefer the freedom to change TCP bindings in mio itself and then at my leisure update other bindings. Exposing an API as a public interface would require everything to change all at once (and would make it very difficult to change)
