### ISSUE TITLE
WAMP server stops responding after a while

### ISSUE THREAD

**Issue by Boscop** [carllerche/mio#579]
Maybe this issue is related to this crate too?
https://github.com/dyule/wamp-rs/issues/5
Not sure if the cause is in mio or ws-rs or wamp-rs but I'm trying to figure it out..

**Comment by carllerche** [comment]
I'm not sure what the relevant action is here, so I'm going to close the issue. If you have a minimal failing test case illustrating a bug w/ Mio, please create a new issue and include the test case.
