### ISSUE TITLE
channel::SyncSender causes a deadlock

### ISSUE THREAD

**Issue by agalakhov** [carllerche/mio#588]
Yes, it is deprecated, but...

If the queue size is 0 (rendevouz mode), any attempt to use the SyncSender with evented Receiver causes a deadlock. This is because the event is signaled only after send() is finished. Since the event was not yet signaled, the event handler on the receiving side is not called, and send() never finishes.

The same error is copy-pasted into mio_more.

**Comment by carllerche** [comment]
Interesting. Do you have a fix suggestion?

**Comment by agalakhov** [comment]
Right now I'm trying to invent one. There is a chicken-and-egg problem: we can't signal an event before we send, and after send() it's too late. One possible solution is to use a non-blocking mpsc::channel for SyncChannel and implement blocking using our own semaphore over the event counter.

**Comment by agalakhov** [comment]
The workaround I'm currently using: I send a Barrier together with the message using a simple Sender and then wait for them on both sides.

**Comment by carllerche** [comment]
The channel is deprecated and will be deleted from the code base soon, so I'm going to close the issue.
