### ISSUE TITLE
Windows: support regular files

### ISSUE THREAD

**Issue by DemiMarie** [carllerche/mio#589]
Unlike Linux, Windows supports regular files with asynchronous IO.  Furthermore, Windows lacks the ability that Linux and *BSD have to scale to tens of thousands of OS threads, so using worker threads for file IO on Windows is not scalable.  This is compounded by the fact that NTFS is slow.

This is a feature request to use IOCP for regular files on Windows.

**Comment by carllerche** [comment]
Thanks for the feature request. In general, the goal of Mio is to stay small. The library should provide all the necessary hooks to implement windows file support in a separate library. Here is an example of how to implement windows specific features that integrate with Mio in a third party crate: https://github.com/alexcrichton/mio-named-pipes

**Comment by Ralith** [comment]
> using worker threads for file IO on Windows is not scalable

The usual approach to the worker thread solution is to have a small, fixed-size threadpool, which should work (albeit suboptimally) on any major platform.

**Comment by agalakhov** [comment]
Looks like this approach does not work for window messages (WM_***), does it?

**Comment by carllerche** [comment]
@agalakhov Why would it not work for window messages?

**Comment by agalakhov** [comment]
But how? Windows messages seem to be very special, they aren't file handles. I'm aware only of two waiting functions for them: `GetMessage()` and `MsgWaitForMultipleObjects()`.

**Comment by carllerche** [comment]
@agalakhov if windows messages are IOCP compatible, you should be able to make them work w/ mio using the same strategy as named pipes: https://github.com/alexcrichton/mio-named-pipes

**Comment by agalakhov** [comment]
@carllerche Looks like they aren't. I hope I'm wrong.

**Comment by carllerche** [comment]
I don't think that there is any further action to take for this issue, so I am closing it.
