### ISSUE TITLE
Doesn't compile with target aarch64-linux-android

### ISSUE THREAD

**Issue by chshawkn** [carllerche/mio#598]
On MacOS 10.12.4
rustup 1.2.0 (70faf07 2017-04-08)
rustc 1.17.0 (56124baa9 2017-04-24)

when `cargo build --target=aarch64-linux-android` got error:

```bash
error[E0308]: mismatched types
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.7/src/sys/unix/uds.rs:130:33
    |
130 |                                 len)));
    |                                 ^^^ expected i32, found u32

error: aborting due to previous error

error: Could not compile `mio`.
```

**Comment by dangcheng** [comment]
Is libc bug? https://doc.rust-lang.org/libc/arm-linux-androideabi/src/libc/unix/notbsd/android/b32/mod.rs.html#9

**Comment by Nercury** [comment]
Android has some interesting Linux modifications.

**Comment by angel-manuel** [comment]
The issue here is that Android linux headers don't have some epoll flags(namely EPOLLRDHUP and EPOLLONESHOT).

Two versions ago I changed the code and got it running on Android. I may port the changes, clean them up and make a pull request.

**Comment by chshawkn** [comment]
https://github.com/carllerche/mio/pull/601 merged, close.
