### ISSUE TITLE
Outdated html_root_url

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#613]
The html_root_url of version 0.6.8 [here](https://github.com/carllerche/mio/blob/v0.6.8/src/lib.rs#L78) points to the documentation for version 0.6.1.

I would recommend adding a reminder in Cargo.toml like https://github.com/serde-rs/serde/commit/dc7ab2696a14fe5ca219ac09f8496bdc613ff602.

**Comment by carllerche** [comment]
Seems like a very manual step. Given that docs.rs is "official", why doesn't the tooling assume a docs.rs URL by default?

**Comment by dtolnay** [comment]
I agree. I filed https://github.com/rust-lang/rust/issues/42300 and https://github.com/rust-lang/rust/issues/42301 to follow up.
