### ISSUE TITLE
Tests fail to compile with --no-default-features

### ISSUE THREAD

**Issue by tones111** [carllerche/mio#615]
Many (most?) of the tests depend on deprecated functionality which causes compilation failures when trying to run them without deprecation support.  Should they be re-written or guarded with #![cfg(feature = "with-deprecated")]?

**Comment by carllerche** [comment]
They should be rewritten... unfortunately, that is a low priority for me personally.

**Comment by ahmedcharles** [comment]
This works now, on master and should be tested for soon.

**Comment by alexcrichton** [comment]
Thanks @ahmedcharles!
