### ISSUE TITLE
Expose `Ready` with a Into/From `usize`

### ISSUE THREAD

**Issue by valarauca** [carllerche/mio#622]
I'm trying to do atomic updates of events across threads. This is 1 thread handles events while ~3 threads actually read data, parse packets, handle DB transactions. Using a single thread for event + io handling is becoming a bottleneck.

Rust exposes `AtomicUsize` while I can unsafely convert `Ready` to a `Usize` this seems unnecessarily hacky as the library _could_ expose this functionality. 

I'll happily submit the patch set for this if its okay with the maintainers.

**Comment by alexcrichton** [comment]
The intention here is to not expose this as it would effectively stabilize the bit-value representation for `Ready` while it's intended to remain flexible to other implementations. Multithreaded updates of a `Ready` though is something that other applications, like Tokio, want though! Does [seeing how Tokio does this](https://github.com/tokio-rs/tokio-core/blob/d85f54dffbbbd418843d2af2bf04cfc4bd97c411/src/reactor/mod.rs#L780-L876) help?

**Comment by valarauca** [comment]
I have it working with unsafe, I was just trying remove that as the
transmute step is wholly unnecessary.

I do understand stabilization and platforms concerns. It was short sited of
me to want this as my only supported platform is x64 Linux.

The tokio solution misunderstands my issue.
