### ISSUE TITLE
move deprecated EventLoop to another crate?

### ISSUE THREAD

**Issue by guanqun** [carllerche/mio#625]
`channels` and `timers` are now in `mio-more` crate. As `EventLoop` is marked as deprecated, can we do the same? Moving to another crate, so dependent packages can simply pick up the new crate and there'll be very few changes.

**Comment by carllerche** [comment]
This could work, but I personally don't have time to do it. It could be added to mio-more probably.

**Comment by guanqun** [comment]
OK. I'll see if I've time for this.

**Comment by carllerche** [comment]
I'm going to close this as this issue belongs on the other crate that will maintain this.
