### ISSUE TITLE
WouldBlock on readable event (Windows)

### ISSUE THREAD

**Issue by rom1v** [carllerche/mio#632]
On Windows (only), calling `stream.read()` on a _readable_ poll event may fail with `WouldBlock`.

I wrote a sample to explain and reproduce the issue: https://github.com/rom1v/mio-sample

What is the expected behavior and the correct way to use **mio** on Windows?

**Comment by alexcrichton** [comment]
Thanks for the report! This behavior falls under the category of ["spurious events"](https://docs.rs/mio/0.6.9/mio/struct.Poll.html#spurious-events) and is expected, you'll basically just want to ignore `WouldBlock` in the example you've got.

**Comment by rom1v** [comment]
OK, thank you for your quick answer!

**Comment by rom1v** [comment]
Is it also expected that `poll.poll()` sometimes returns with 0 events on Windows (while there is no timeout)?

On the very same sample, just print `events.len()` immediately after the call to `poll()`.

**Comment by alexcrichton** [comment]
It is indeed expected!

**Comment by rom1v** [comment]
> It is indeed expected!

For `poll()`, it should be possible not to expose spurious events: just making it retry before returning if `events.is_empty()`. Is there a reason not to do this?

**Comment by alexcrichton** [comment]
Yes, spurious events need to be handled by the caller, these can happen on other platforms as well.

**Comment by rom1v** [comment]
> Yes, spurious events need to be handled by the caller, these can happen on other platforms as well.

I understand that, but `poll()` returning with 0 events may be avoided easily directly in the `mio` implementation. Is there a reason for keeping the current behavior (returning with 0 events)?

**Comment by alexcrichton** [comment]
It's also just as easily avoided in callers? The reason to keep the current behavior is to reflect the actual semantics of what's happening, the blocking call woke up and is returning.
