### ISSUE TITLE
Loosing connections? Surely I am the problem.

### ISSUE THREAD

**Issue by siscia** [carllerche/mio#634]
Hi :)

I have this very small snippet:

```
extern crate mio;

use mio::tcp::TcpListener;
use mio::Token;
use mio::Poll;
use mio::Ready;
use mio::PollOpt;
use mio::Events;

use std::io::{Read, Write};
use std::str;
use std::io::ErrorKind;

const SERVER: Token = Token(0);

fn main() {
    println!("Hello, world!");

    let addr = "0.0.0.0:1883".parse().unwrap();
    let server = TcpListener::bind(&addr).unwrap();

    let poll = Poll::new().unwrap();

    poll.register(&server, SERVER, Ready::readable(), PollOpt::level()).unwrap();

    let mut events = Events::with_capacity(1024);

    let mut buffer: [u8; 1024] = [0; 1024];

    loop {

        poll.poll(&mut events, None).unwrap();

        for event in events.iter() {
            if event.readiness().is_readable() {
                match server.accept() {
                    Ok((mut tcp_stream, socketAddr)) => {
                        match tcp_stream.read(&mut buffer) {
                            Ok(n) => {
                                println!("Read {} bytes", n);
                                println!("Value: {}", str::from_utf8(&buffer).unwrap());
                                tcp_stream.write(&buffer);
                                buffer = [0; 1024];
                            }
                            Err(e) => {
                                if e.kind() == std::io::ErrorKind::WouldBlock {
                                    println!("Would Block");
                                }
                                println!("Error: {:?}", e);
                            }
                        }
                    }
                    Err(e) => {
                        println!("Error: {:?}", e);
                    }
                }
            }
        }
    }
}
```

The idea is a basic echo server.

However sometimes it doesn't work.
I send a TCP stream with nc and I would expect the same bytes back. Sometimes it work some other times it doesn't.

```
$ echo -e "foobar" | sudo nc localhost 1883 -D #OK
foobar
$ echo -e "foobar" | sudo nc localhost 1883 -D #OK
foobar
$ echo -e "foobar" | sudo nc localhost 1883 -D #OK
foobar
$ echo -e "foobar" | sudo nc localhost 1883 -D # <- ERROR
$ echo -e "foobar" | sudo nc localhost 1883 -D # <- ERROR
$ echo -e "foobar" | sudo nc localhost 1883 -D #OK
foobar
```

And what I see in the log is something like:

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/mett`
Hello, world!
Read 7 bytes
Value: foobar

Read 7 bytes
Value: foobar

Read 7 bytes
Value: foobar

Would Block
Error: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }
Would Block
Error: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }
Read 7 bytes
Value: foobar
```

The issues are not those two EAGAIN that I receive, the issues is that I never see the answer to those two request.

What is happening here?

It is me not understanding some basic concept ?

**Comment by alexcrichton** [comment]
Thanks for the report! This issue has to do with the fact that mio uses non-blocking I/O. The error you're seeing, "temporarily unavailable", means that the bytes haven't arrived yet and you'd have to block waiting for a "readable" notification from the OS before attempting to read the bytes again. Whether or not it's immediately ready for being read is nondeterministic and not guaranteed, which is why it works sometimes but not others.

**Comment by siscia** [comment]
Hi Alex :)

still I am not sure I understand why I send 6 messages but I receive only 4.

I am completely ok with poll that sometimes wakeup without messaging ready to be read. However, next time poll wake up I would be expecting to see all the previous messages.

Is this expectation correct?

**Comment by alexcrichton** [comment]
The two messages "dropped" are in transit and it's just nondeterministic that you received 4/6, it could have been possible that you received 0/6. To receive all messages you'd need to keep the socket alive until the mesage has been read.

**Comment by siscia** [comment]
Wait a second.

Each time I re-run nc, I am expecting that each run of nc open a new connection (3-way handshake and everything), and also I am expecting that every time that TCPStream goes out of scope the connection just created is closed.

Maybe I am starting to get it...

What I am doing wrong is that I do not poll on the TCPStream but only on the TCPListener.

The poll on the TCPListener tells me when a new connection is ready.
From there I create the TCPStream.
Then I poll the TCPStream to know when a new message is actually in the stream; at this point I am assured that there is an actual message to read.

Am I correct?

**Comment by alexcrichton** [comment]
Yeah you'll want to register the accepted TCP stream with the `Poll` and then use that to wait for the stream to be readable, and that should do it!
