### ISSUE TITLE
Unable to build when targeting wasm32-unknown-emscripten platform

### ISSUE THREAD

**Issue by Kvikal** [carllerche/mio#642]
I am currently unable to build mio when targeting wasm32-unknown-emscripten platform.

I am using current Rust nightly.

I receive following errors:

```
error[E0432]: unresolved import `self::unix::Events`
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.10/src/sys/mod.rs:5:5
  |
5 |     Events,
  |     ^^^^^^ no `Events` in `sys::unix`

error[E0432]: unresolved import `self::unix::Selector`
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.10/src/sys/mod.rs:7:5
  |
7 |     Selector,
  |     ^^^^^^^^ no `Selector` in `sys::unix`
```

I have not delved too much into WASM/Rust yet, so I am not sure if this should even work or if this is the right place to report this.

**Comment by carllerche** [comment]
In theory it could work, but Mio doesn't currently support wasm. 

I'm going to close the issue as there are no current plans to support it, though if someone provides an impl I'd be happy to include it.
