### ISSUE TITLE
Drop the with-deprecated cfg and everything behind it

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#655]
As I understand it, the only thing blocking this is reimplementing the test cases that currently rely on deprecated functionality.

The best way to approach this would be running `cargo test --no-default-features` to see what breaks:

```
...

error: aborting due to 180 previous errors
```

then reworking small self-contained pieces to use the new APIs. I imagine this will be split across lots of PRs. It also sounds like a great way to learn the ins and outs of mio in general!

Once `cargo test --no-default-features` passes, we can rip out all the deprecated functionality.

**Comment by ahmedcharles** [comment]
I'm working on this, (perhaps slowly).
