### ISSUE TITLE
Remove the implementations of std::ops::Not

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#656]
From what I can tell, the only reason these exists is to be used in the implementation of Sub and SubAssign.

```rust
impl<T: Into<Ready>> ops::Sub<T> for Ready {
    type Output = Ready;

    fn sub(self, other: T) -> Ready {
        Ready(self.0 & !other.into().0)
    }
}

impl<T: Into<Ready>> ops::SubAssign<T> for Ready {
    fn sub_assign(&mut self, other: T) {
        self.0 &= !other.into().0;
    }
}
```

Other than in Sub, it never makes sense to apply Not to a Ready. You would never call Poll::register and pass the Not of a Ready, for example. Let's reimplement Sub in a different way and remove the semantically meaningless Not operation.

Applies to Ready, UnixReady, FuchsiaReady, and PollOpt.

**Comment by carllerche** [comment]
Before doing this, the git history should be checked for any potential info on why it was originally added.

**Comment by ahmedcharles** [comment]
The impl for PollOpt was added in: https://github.com/carllerche/mio/commit/012291476402eb218c47e847009d528853d13c70

It doesn't seem to explain why.
