### ISSUE TITLE
Upgrade to a stable version of iovec

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#660]
The iovec crate is critical to the public API of mio. It is how we coordinate vector reads/writes. As such, we cannot call mio stable until it is using a stable iovec.

**Comment by tamird** [comment]
This probably shouldn't have [help wanted]. iovec is also owned by @carllerche and looks to have [significant unreleased changes](https://github.com/carllerche/iovec/compare/v0.1.2...master). It's not clear what external contributors can do to help, here.

**Comment by carllerche** [comment]
@tamird this is a good point. There are no immediate plans to stabilize iovec. I'm going to close this issue.
