### ISSUE TITLE
Consider using associated constants for the bitflag-like types

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#661]
The various Ready constructors currently work like this:

```rust
impl Ready {
    pub fn readable() -> Ready { /* ... */ }
    pub fn writable() -> Ready { /* ... */ }
}
```

With the associated constants feature of Rust 1.20, it could work like this:

```rust
impl Ready {
    pub const READABLE: Ready = /* ... */;
    pub const WRITABLE: Ready = /* ... */;
}
```

The constructors never do any work so they shouldn't need to be functions.

One advantage of constants is that they can be used in the pattern of a match statement.

**Comment by AndyGauge** [comment]
I want to learn the associated constraints feature, so I'm going to give this a shot.

**Comment by dtolnay** [comment]
Great! Go for it. When it is done we will need to evaluate whether it is really an improvement over the current way.

**Comment by AndyGauge** [comment]
So one problem with using Associated Constraints is that it breaks previous builds of Rust.  Currently, Travis tests version 1.13 which will fail with the implementation of the feature.  I also wanted to capture @carllerche comment about now that rustc 1.20 has dropped, the feature can be implemented in 12 weeks (12/24ish).

**Comment by dethoter** [comment]
I'm wondering why do you use struct(usize) and a number of associated constants instead of a plain enum?

**Comment by carllerche** [comment]
Mio will move away from bitflag style APIs in 0.7. This issue is no longer relevant.
