### ISSUE TITLE
Single Evented on more than on Poll

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#674]
Question from [i.r-l.o](https://internals.rust-lang.org/t/crate-evaluation-for-2017-08-15-mio/5709/2):

> Can a single Evented be registered on more than one Poll? What happens? The documentation doesn’t seem to clearly say anything.

**Comment by cramertj** [comment]
This [comment in the Unix implementation](https://github.com/carllerche/mio/blob/master/src/sys/unix/epoll.rs#L27) says that only one poll registration per `Evented` is supported:

```
/// Each Selector has a globally unique(ish) ID associated with it. This ID
/// gets tracked by `TcpStream`, `TcpListener`, etc... when they are first
/// registered with the `Selector`. If a type that is previously associated with
/// a `Selector` attempts to register itself with a different `Selector`, the
/// operation will return with an error. This matches windows behavior.
```

**Comment by carllerche** [comment]
Yes, `Evented` values can only be registered with a single `Poll` instance ever (even if the value is deregistered). There are non-portable work arounds (like using a FD directly).
