### ISSUE TITLE
Clarify BSD support

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#678]
Feedback from [i.r-l.o](https://internals.rust-lang.org/t/crate-evaluation-for-2017-08-15-mio/5709/2):

> The git readme says that NetBSD is supported, but doesn’t mention FreeBSD, while the documentation mentions that kqueue is used on FreeBSD but doesn’t mention NetBSD.

**Comment by asomers** [comment]
FreeBSD is fully supported and has been for some time.  I just submitted PR #737 to fix the README.

**Comment by carllerche** [comment]
Thanks. I merged #737.
