### ISSUE TITLE
Error and Hup triggered even when not registered

### ISSUE THREAD

**Issue by rom1v** [carllerche/mio#680]
On linux, if I register a socket without [error](https://docs.rs/mio/0.6.10/mio/unix/struct.UnixReady.html#method.error) or [hup](https://docs.rs/mio/0.6.10/mio/unix/struct.UnixReady.html#method.hup) interests, e.g.:

```rust
poll.register(&socket, Token(0), Ready::readable(), PollOpt::level());
```

Then I still receive events with _error_ and _hup_ set.

I sometimes receive `Error` and `Hup` set in addition to `Readable`:

    Event { kind: Ready {Readable | Error | Hup}, token: Token(42) }

But sometimes, I also receive `Error` alone:

    Event { kind: Ready {Error}, token: Token(29) }

This is annoying especially in _level_ mode, because if we handle the events like this:

```rust
let ready = event.readiness();
if (event.is_readable()) {
    // …
}
if (event.is_writable()) {
    // ...
}
// Error or Hup not handled because not registered, but still triggered
```

Then the event is not handled, and is triggered again and again in a live loop.

Is it expected?

**Comment by alexcrichton** [comment]
I believe this is something we just need to document, this is how epoll works

**Comment by rom1v** [comment]
OK, thank you.

But then, what's the benefit of registering `Error` or `Hup`, as documented in [`UnixReady`](https://docs.rs/mio/0.6.10/mio/unix/struct.UnixReady.html):

```
poll.register(&socket,
              Token(0),
              Ready::readable() | UnixReady::error(),
              PollOpt::edge()).unwrap();
```

**Comment by alexcrichton** [comment]
That can probably be removed as well.

**Comment by carllerche** [comment]
Mio is permitted to fire off error / hup if not requested, but there is no guarantee to receive error / hup if **not** requested.

i.e, if you **want** to receive error or hup, you should request it.

**Comment by carllerche** [comment]
This should be handled by #908
