### ISSUE TITLE
Help Needed 

### ISSUE THREAD

**Issue by janus** [carllerche/mio#730]
I want to build neighbor discovery , I would like to use mio but I have issue understanding its different shapes. I have seen where Handler trait was used with notify and ready methods. I have also see where direct method call using event_loop struct. 

My question is which one is the proper way. And could one point to me an example of such?

**Comment by carllerche** [comment]
I would say that the API docs are the most up to date. Also, you might consider using Tokio, which is a higher level library. There is a gitter channel for support there (https://gitter.im/tokio-rs/tokio).
