### ISSUE TITLE
CI for FreeBSD

### ISSUE THREAD

**Issue by asomers** [carllerche/mio#738]
Would you be interested in running CI tests on FreeBSD?  I volunteer to host it.  I'm already hosting CI for the [nix](https://github.com/nix-rust/nix) and [mio-aio](https://github.com/asomers/mio-aio) crates, and it would be no trouble to add this one.  If you agree, all that you'll need to do will be to add the GitHub commit hooks.

**Comment by carllerche** [comment]
Yes, I think we'd be happy to add freebsd CI to the run.

**Comment by asomers** [comment]
Ok, I'll set it up in polling mode.  I don't think I need any special access to the mio repository in order to post status reports.  Once it's working, I'll ask you to enable commit hooks.

**Comment by asomers** [comment]
Here's an example pull request: https://github.com/nix-rust/nix/pull/663 .  And if you look at https://github.com/nix-rust/nix/commits/master you can see the status posted for each commit.  Nix uses bors, but otherwise it's similar to mio.  BuildBot will post its own status notification alongside Travis and Appveyor.
