### ISSUE TITLE
Android build failing in CI

### ISSUE THREAD

**Issue by KodrAus** [carllerche/mio#744]
Looks like a bunch of PRs are blocked on getting the android build sorted, which looks like [an infrastructure fail rather than a `mio` fail](https://travis-ci.org/carllerche/mio/jobs/283553150#L1824-L1825).

@carllerche is this something anyone could fix by building [the image](https://github.com/carllerche/mio/tree/master/ci/docker/arm-linux-androideabi) locally and having a poke around?

**Comment by carllerche** [comment]
I don't know... maybe (I hardly know what I am doing)? I really just hacked until it seemed to work. I would really appreciate someone trying to fix it :)

**Comment by malbarbo** [comment]
libc had the same issue, here is the fix: https://github.com/rust-lang/libc/pull/791
