### ISSUE TITLE
Iovec API change causing panics

### ISSUE THREAD

**Issue by jolhoeft** [carllerche/mio#746]
The iovec crate recently made an api change in 0.1.1 that is causing panics (see https://github.com/carllerche/iovec/commit/007031f4b4f7f518ea6b1888b0bc189604430dbd). Using the deprecated methods panics when a zero length buffer is passed.

**Comment by jolhoeft** [comment]
Here is some backtrace of the panic:

thread '<unnamed>' panicked at 'this crate accidentally accepted
0-sized slices originally but this was since discovered as a soundness
hole, it's recommended to use the `from_bytes` function instead',
src\libcore\option.rs:819:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: <core::option::Option<T>>::expect
             at C:\projects\rust\src\libcore/option.rs:302
  10: <&'a iovec::IoVec as core::convert::From<&'a [u8]>>::from
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\iovec-0.1.1\src/lib.rs:109
  11: <T as core::convert::Into<U>>::into
             at C:\projects\rust\src\libcore/convert.rs:398
  12: mio::sys::windows::tcp::TcpStream::write
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.6.10\src\sys\windows/tcp.rs:329
  13: <mio::net::tcp::TcpStream as std::io::Write>::write
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.6.10\src\net/tcp.rs:398
  14: <ws::stream::Stream as std::io::Write>::write
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/stream.rs:191
  15: ws::stream::TryWriteBuf::try_write_buf
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/stream.rs:52
  16: <ws::connection::Connection<H>>::write
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/connection.rs:833
  17: <ws::io::Handler<F>>::handle_event
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/io.rs:583
  18: <ws::io::Handler<F>>::event_loop
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/io.rs:429
  19: <ws::io::Handler<F>>::run
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/io.rs:396
  20: <ws::WebSocket<F>>::run
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/lib.rs:331
  21: <ws::WebSocket<F>>::listen::{{closure}}
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/lib.rs:316
  22: <core::result::Result<T, E>>::and_then
             at C:\projects\rust\src\libcore/result.rs:621
  23: <ws::WebSocket<F>>::listen
             at C:\Users\Jeffrey\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0.7.3\src/lib.rs:316
  24: virtua_rasa::main::{{closure}}
             at src/main.rs:201

**Comment by alexcrichton** [comment]
I've sent a PR to fix this in https://github.com/carllerche/mio/pull/747

**Comment by jolhoeft** [comment]
Is this purely a windows issue? I haven't been able to check under Linux yet, but will later today.

**Comment by jolhoeft** [comment]
I don't see this under Linux, although it is not obvious to me why.

**Comment by alexcrichton** [comment]
This isn't just a Windows issue, the panic affects both Linux and Windows. There's different behavior in mio on Linux/Windows, however, which would explain this discrepancy.
