### ISSUE TITLE
Extremely high CPU usage in websocket/mio thread

### ISSUE THREAD

**Issue by Boscop** [carllerche/mio#755]
I'm using ws-rs for the webui of my application and lately I've been getting very high (15%) CPU usage (without me changing the code since when it was using low CPU usage (3%)).
So I investigated with the "Very Sleepy" Profiler, and it showed that the websocket/mio thread uses all that CPU. The lion share (top two entries) are websocket/mio functions:
![](https://i.imgur.com/CoC5kcR.png)
![](https://i.imgur.com/FJteTxr.png)
Here is the CSV export of "Very Sleepy": http://dpaste.com/177BVN7

More info here: https://github.com/housleyjk/ws-rs/issues/178

The thing is, my websocket thread isn't even doing much (officially). 
And I haven't changed the code since when it was only using 3% CPU.

I'd appreciate any insight into what is causing this and how to get the CPU usage down again.

**Comment by carllerche** [comment]
Hey there. I do not believe that this is a mio related issue. You also already have an issue open on `ws-rs`, so I'm going to close this one. If you discover that this is indeed a mio bug, please open a new with a mio only repro.

Thanks!
