### ISSUE TITLE
Moving Poll Objects to Subordinate Threads?

### ISSUE THREAD

**Issue by pulltab** [carllerche/mio#756]
Hi, folks. 

Disclaimer - I am only a couple weeks into using Rust.

I am attempting to use Mio as an IPC mechanism between my main thread and subordinate threads which are polling a so-called system "channel" (Token(0)).  For the moment, there is only one system event, shutdown, so I am looking to treat readiness as a signal to terminate.

The following example fails to work as expected.  Namely, the subordinate child fails to observe the readiness of the system channel:

```
extern crate mio;

use std::collections::HashMap;

fn main(){
    let mut threads : HashMap<String, (std::thread::JoinHandle<bool>, mio::SetReadiness)> = HashMap::new();

    for i in 1..2 {
        let poll = mio::Poll::new().unwrap();
        let (registration, set_readiness) = mio::Registration::new2();
    
        poll.register(&registration,
        mio::Token(0),
        mio::Ready::readable(),
        mio::PollOpt::edge()).unwrap();
    
         let thread = std::thread::spawn(move || {
            loop {
                let mut events = mio::Events::with_capacity(1024);
                poll.poll(&mut events, None).unwrap();
                for event in &events {
                    println!("Got event {:?}!", event);
                    if event.readiness().is_readable() {
                        return false;
                    }
                }
                std::thread::sleep(std::time::Duration::from_millis(10));
            }
        });
        
        threads.insert("foo".to_string(), (thread, set_readiness.clone()));
   }
    
    std::thread::sleep(std::time::Duration::from_millis(1000));
    
    for (id, (handle, set_readiness)) in threads {
        println!("Shutting down {:?}", id);
        set_readiness.set_readiness(mio::Ready::readable()).unwrap();
        handle.join().unwrap();
        set_readiness.set_readiness(mio::Ready::empty()).unwrap();
    }
} 
```

Can someone point out what I doing wrong?

**Comment by kamyuentse** [comment]
I think to move the following code inside the closure will work.
```
let poll = mio::Poll::new().unwrap();
poll.register(&registration,
        mio::Token(0),
        mio::Ready::readable(),
        mio::PollOpt::edge()).unwrap();
```

**Comment by pulltab** [comment]
Thanks, @kamyuentse. 

That indeed do the trick.

What difference does that make at runtime?

**Comment by kamyuentse** [comment]
I'm not exactly clear about it, jut an experimental science? But the `strace` output shows the following difference:
```
==================== one ==================== 
0x7ffc040c3ce0) = 0
write(14, "\1", 1)                      = 1
write(8, "\1", 1)                       = 1
write(5, "\1", 1)                       = 1
write(11, "\1", 1)                      = 1
futex(0x7f8cabdff9d0, FUTEX_WAIT, 15903, NULL
================== another ================== 
0x7ffdca907690) = 0
futex(0x7fd3693fe9d0, FUTEX_WAIT, 15511, NULL
```

Which indicates that the `set_readiness` failed?

**Comment by kamyuentse** [comment]
umm, shot that.

``` rust
for i in 1..2 {
        let poll = mio::Poll::new().unwrap();
        let (registration, set_readiness) = mio::Registration::new2();
    
        poll.register(&registration,
        mio::Token(0),
        mio::Ready::readable(),
        mio::PollOpt::edge()).unwrap();
    
         let thread = std::thread::spawn(move || {
            loop {
                let mut events = mio::Events::with_capacity(1024);
                poll.poll(&mut events, None).unwrap();
                for event in &events {
                    println!("Got event {:?}!", event);
                    if event.readiness().is_readable() {
                        return false;
                    }
                }
                std::thread::sleep(std::time::Duration::from_millis(10));
            }
        });
        
        threads.insert("foo".to_string(), (thread, set_readiness.clone()));
   } // registration dropped here
```

Indeed, just make the  `registration` live inside closure will do the trick.

(PS: This issue can be closed?)

**Comment by pulltab** [comment]
I can close the issue, yes.

I was hoping to get clarity as to what is happening in register to make it this way.   However, perhaps when I am more skilled in Rust I can read the source and answer that question for myself.

Thanks again.

**Comment by twmb** [comment]
@pulltab the issue was that, in your version, the `registration` is dropped at the end of each for loop iteration. Dropping the `Registration` half of `new2` un-registers the `Registration`: https://github.com/carllerche/mio/blob/92ac500e5d2b18960deb41103018b981d04a663f/src/poll.rs#L1636-L1638

In terms of the `enqueue_with_wakeup`, the wakeup does not happen because the `poll` is not in a sleeping state. So, `enqueue_node` enqueues the registration so that it can be dropped as soon as `poll` is called. The later `set_readiness` is a no-op if the registration is dropped: https://github.com/carllerche/mio/blob/92ac500e5d2b18960deb41103018b981d04a663f/src/poll.rs#L1795-L1797.
