### ISSUE TITLE
some questions about `Registration` and `SetReadiness`

### ISSUE THREAD

**Issue by nooberfsh** [carllerche/mio#761]
there is a [Portability](https://docs.rs/mio/0.6.11/mio/struct.Poll.html#portability) section in the doc, I wonder `Spurious events` and `Draining readiness` are applicable to `Registration`. 
May `Spurious events` happen on `Registration`? 
If an `Registration` is registed with  edge-triggered mode, may `Draining readiness` happen on it.

below is some code from [set_readiness](https://docs.rs/mio/0.6.11/mio/struct.SetReadiness.html#method.set_readiness)
```rust
use mio::{Events, Registration, Ready, Poll, PollOpt, Token};

let poll = Poll::new()?;
let (registration, set_readiness) = Registration::new2();

poll.register(&registration,
              Token(0),
              Ready::readable(),
              PollOpt::edge())?;

// Set the readiness, then immediately poll to try to get the readiness
// event
set_readiness.set_readiness(Ready::readable())?;

let mut events = Events::with_capacity(1024);
poll.poll(&mut events, None)?;

// There is NO guarantee that the following will work. It is possible
// that the readiness event will be delivered at a later time.
let event = events.get(0).unwrap();
assert_eq!(event.token(), Token(0));
assert!(event.readiness().is_readable());
```
For what reasons  `There is NO guarantee that the following will work`
here are my guesses:
-  `poll.poll(&mut events, None)` may block ?
- event returned from `events.get(0).unwrap()` is for another `Evented` instead of the `Registration`

**Comment by carllerche** [comment]
The short answer, there are concurrency related optimizations in the implementation that can cause the example to break.

**Comment by nooberfsh** [comment]
1: what if i register it with edge-triggered mode, would it cause the example to break too?
2: is it possible that `Poll::poll`  return readiness event even if the associated `Registration` handle is not actually ready.

thanks for replay.

**Comment by carllerche** [comment]
1. probably? But I haven't thought it through.
2. `Poll::poll` is permitted to return spurious events for any token that is currently registered. So, the answer is yes.

**Comment by fdubois1** [comment]
How can I know if it is a spurious event or not ?  I'm using Registration to implement a cancel_event. I give the set_readiness to another thread and it can stop the loop. But from what I just red, it could happen that the event happens even if nobody call set_readiness.set_readiness, is it true ?

**Comment by carllerche** [comment]
You need some other variable to track the state. Registration is only to notify of a potential change to that variable, not to signal a state change.
