### ISSUE TITLE
Method Events.clear(&mut self) missing

### ISSUE THREAD

**Issue by frehberg** [carllerche/mio#783]
In poll.rs the 'impl Events' lacks a method to clear the container of Event values. 
Currently the container is being reset within the platform specific implementation of elector:select(events) only. 

It would be useful to expose the "clear/reset" feature of Events-container, so developers would be able to use a pattern like clear/re-use and check in their code. Also it would be possible to move the clearing from function context Selector::select() into outer function-context of Poll::poll()

The following patch is moving the corresponding, platform specific code-lines into a generic Events::clear()

https://github.com/carllerche/mio/pull/782

**Comment by Thomasdezeeuw** [comment]
I need this as well.

**Comment by carllerche** [comment]
Closed by #782
