### ISSUE TITLE
Idea for Timers

### ISSUE THREAD

**Issue by Thomasdezeeuw** [carllerche/mio#790]
I know timers where a part of mio and have since been removed, but I have somewhat simple idea that might be good for inclusion in the crate again.

This would add a new struct called `Timer`, e.g:
```rust
struct Timer {
    deadline: Instant,
}

impl Timer {
    fn new(deadline: Instant) -> Timer {
        Timer { deadline }
    }
    fn timeout(timeout: Duration) -> timer {
        Timer { deadline: Instant::now() + timeout }
    }
}
```

For implementing `Evented` for it `Poll` would need an ordered collection, e.g. a linked list, of deadlines. Then when `Poll.poll` is called rather then using the user provided `timeout` we would use the first deadline as a timeout (or the provided timeout if is earlier). Something like this:`

```rust
struct Poll {
    deadlines: LinkedList<Instant>,
}
impl Poll {
    fn poll(&self, events: &mut Events, timeout: Option<Duration>) {
        let first_deadline = self.deadlines.first();
        let timeout = match timeout {
            Some(timeout) => ::std::cmp::min(Instant::now() + timeout, first_deadline),
            None => first_deadline.duration_since(Instant::now()), // TODO: check deadline < now().
        };

        // Continue like normal.

        // After everything is just, just before returning.
        // loop over all deadlines and create an Event for each one of which the deadline has passed.
    }
}
```

**Comment by asomers** [comment]
You should take a look at [tokio-timer](https://crates.io/crates/tokio-timer), which uses mio underneath.  Or, on a BSD-based system, you can simply use kqueue with `EVFILT_TIMER` and let the kernel worry about maintaining the list of timeouts.

**Comment by Thomasdezeeuw** [comment]
@asomers That could work, but I'm not using tokio.

**Comment by carllerche** [comment]
Thanks for the suggestion.

I opted to remove timers as they can be implemented entirely in "user land". So, you could add this capability in another crate :).

Not having it in this crate reduces the amount of code I have to maintain :)

**Comment by Thomasdezeeuw** [comment]
Fair enough. I might crate such a crate in the future then.
