### ISSUE TITLE
TCPStream is Returning No Data on read_exact

### ISSUE THREAD

**Issue by pulltab** [carllerche/mio#795]
I am attempting to send some snappy encoded avro blobs to a Rust daemon and experiencing some odd issues with TCPStream.

Critical section is as follows:

``` 
fn handle_avro_payload(
        &mut self,
        mut chans: util::Channel,
        _tags: &sync::Arc<metric::TagMap>,
        reader: &mut io::BufReader<mio::net::TcpStream>,
    ) -> Result<Option<u64>, String>{
        let header_size_in_bytes = mem::size_of::<Header>();
        let payload_size_in_bytes = match reader.read_u32::<BigEndian>() {
            Ok(i) => i as usize,
            Err(_) => return Err(format!("Failed to parse payload length from the wire!"))
        };

        if payload_size_in_bytes <= header_size_in_bytes {
            return Err(format!("Received payload is too small!"))
        }

        let mut buf = Vec::with_capacity(payload_size_in_bytes);
        if reader.read_exact(&mut buf).is_err() {
            return Err(format!("Failed to read payload from the wire!"))
        }

        match Cursor::new(buf).into() {
             // Omitted as it is not relevant.
        }
    }
```

After adding a few trace statements, I discovered that `reader.read_exact(&mut buf)` is returning with `Ok`, however, no data has been populated in `buf`.  This is despite `payload_size_in_bytes` being the expected, non-zero usize.  This then results in downstream issues when I attempt to parse the data into types in the match statement.

Am I doing something unexpected here by coupling a BufReader and a mio TCPStream?  Has anyone experienced similar issues before?

**Comment by pulltab** [comment]
Adding some more debug statements and it seems that the bytes I want are actually in the BufReader:

```
[cernan::source::avro][181][2018-01-05T03:06:25.084550+00:00][TRACE] Before reading payload_size_in_bytes: BufReader { reader: TcpStream { sys: TcpStream { inner: TcpStream { addr: V4(127.0.0.1:2002), peer: V4(127.0.0.1:58759), fd: 28 } }, selector_id: SelectorId { id: AtomicUsize(6) } }, buffer: 0/8192 }
[cernan::source::avro][189][2018-01-05T03:06:25.084684+00:00][TRACE] After reading payload_size_in_bytes: BufReader { reader: TcpStream { sys: TcpStream { inner: TcpStream { addr: V4(127.0.0.1:2002), peer: V4(127.0.0.1:58759), fd: 28 } }, selector_id: SelectorId { id: AtomicUsize(6) } }, buffer: 342/8192 }
[cernan::source::avro][194][2018-01-05T03:06:25.084725+00:00][TRACE] Reading 342 bytes off the wire
[cernan::source::avro][202][2018-01-05T03:06:25.084766+00:00][TRACE] After read_exact: BufReader { reader: TcpStream { sys: TcpStream { inner: TcpStream { addr: V4(127.0.0.1:2002), peer: V4(127.0.0.1:58759), fd: 28 } }, selector_id: SelectorId { id: AtomicUsize(6) } }, buffer: 342/8192 }
```

**Comment by pulltab** [comment]
I modified the above function to call read_exact on the mio TCPStream directly and I am seeing the same behavior:

``` fn handle_avro_payload(
        &mut self,
        mut chans: util::Channel,
        _tags: &sync::Arc<metric::TagMap>,
        stream: &mut mio::net::TcpStream,
    ) -> Result<Option<u64>, String>{
        let header_size_in_bytes = mem::size_of::<Header>();
        let mut payload_size_buf = Vec::with_capacity(4);
        let payload_size_in_bytes = match stream.read_exact(&mut payload_size_buf) {
            Ok(_) => Cursor::new(payload_size_buf).read_u32::<BigEndian>().expect("Failed to read length!") as usize,
            Err(_) => return Err(format!("Failed to parse payload length from the wire!"))
        };```

**Comment by pulltab** [comment]
Interestingly `read_exact` seems to only work if you manually resize the destination buffer.  `with_capacity` is not enough.  

The following works as intended:

```
fn handle_avro_payload(
        &mut self,
        mut chans: util::Channel,
        _tags: &sync::Arc<metric::TagMap>,
        stream: &mut mio::net::TcpStream,
    ) -> Result<Option<u64>, String>{
        let header_size_in_bytes = mem::size_of::<Header>();
        let mut payload_size_buf = Vec::with_capacity(4);
        let payload_size_in_bytes = match stream.read_exact(&mut payload_size_buf) {
            Ok(_) => Cursor::new(payload_size_buf).read_u32::<BigEndian>().expect("Failed to read length!") as usize,
            Err(_) => return Err(format!("Failed to parse payload length from the wire!"))
        };
        if payload_size_in_bytes <= header_size_in_bytes {
            return Err(format!("Received payload is too small!"))
        }

        trace!("Reading {:?} bytes off the wire", payload_size_in_bytes);
        let mut buf : Vec<u8> = Vec::new();
        buf.resize(payload_size_in_bytes, 0);

        let reader_res = stream.read_exact(&mut buf[..]);
        if reader_res.is_err() {
            return Err(format!("Failed to read payload from the wire!"))
        }
...
```

**Comment by carllerche** [comment]
read_exact works on slices, not on the vec: https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact

Hope this makes sense. Feel free to ask further questions here.

**Comment by pulltab** [comment]
@carllerche Yes, that documentation is what led me to trying to manually resize the vector.  The type system accepts a `&mut Vec` to `read_exact` so there is some magic happening on my behalf.

What isn't clear to me just now is why `Vec::with_capacity` isn't equivalent to the manual resize.  

From https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity:
```
Constructs a new, empty Vec<T> with the specified capacity.

The vector will be able to hold exactly capacity elements without reallocating. If capacity is 0, the vector will not allocate.

It is important to note that this function does not specify the length of the returned vector, but only the capacity. For an explanation of the difference between length and capacity, see Capacity and reallocation.
```


From https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation -

```
The capacity of a vector is the amount of space allocated for any future elements that will be added onto the vector. This is not to be confused with the length of a vector, which specifies the number of actual elements within the vector. If a vector's length exceeds its capacity, its capacity will automatically be increased, but its elements will have to be reallocated.

For example, a vector with capacity 10 and length 0 would be an empty vector with space for 10 more elements. Pushing 10 or fewer elements onto the vector will not change its capacity or cause reallocation to occur. However, if the vector's length is increased to 11, it will have to reallocate, which can be slow. For this reason, it is recommended to use Vec::with_capacity whenever possible to specify how big the vector is expected to get.
```

I took all this to mean that `with_capacity` was reallocating, but perhaps what is actually happening is that the first byte written to the Vec results in a single allocation of the underlying slice to the given size?

**Comment by pulltab** [comment]
Closing the loop after morning source reading.

The issue stems here from the conversion of the `Vec`, constructed via `with_capacity`, into a slice.  After the call to with_capacity `len` of the `Vec` is 0, though `capacity` is properly allocated to the expected size (in bytes).  

When the Vec is Deref'd into a slice we run into trouble here: https://doc.rust-lang.org/src/alloc/vec.rs.html#1693.

**Comment by magniff** [comment]
> Interestingly `read_exact` seems to only work if you manually resize the destination buffer. `with_capacity` is not enough.
> 
> The following works as intended:
> 
> ```
> fn handle_avro_payload(
>         &mut self,
>         mut chans: util::Channel,
>         _tags: &sync::Arc<metric::TagMap>,
>         stream: &mut mio::net::TcpStream,
>     ) -> Result<Option<u64>, String>{
>         let header_size_in_bytes = mem::size_of::<Header>();
>         let mut payload_size_buf = Vec::with_capacity(4);
>         let payload_size_in_bytes = match stream.read_exact(&mut payload_size_buf) {
>             Ok(_) => Cursor::new(payload_size_buf).read_u32::<BigEndian>().expect("Failed to read length!") as usize,
>             Err(_) => return Err(format!("Failed to parse payload length from the wire!"))
>         };
> 
>         if payload_size_in_bytes <= header_size_in_bytes {
>             return Err(format!("Received payload is too small!"))
>         }
> 
>         trace!("Reading {:?} bytes off the wire", payload_size_in_bytes);
>         let mut buf : Vec<u8> = Vec::new();
>         buf.resize(payload_size_in_bytes, 0);
> 
>         let reader_res = stream.read_exact(&mut buf);
>         if reader_res.is_err() {
>             return Err(format!("Failed to read payload from the wire!"))
>         }
> ...
> ```
> 
> I am still at a loss as to why `with_capacity` isn't sufficient for `read_exact` to function.

Thanks for pointing out the workaround!
