### ISSUE TITLE
TcpStream lacks close-method

### ISSUE THREAD

**Issue by frehberg** [carllerche/mio#801]
TcpStream is exposing method shutdown, but it lacks method close, which would allow to release all resources within  current scope. It is important to be able to close a stream and release underlying socket resources for address-reuse for example.Otherwise the OS might refuse to create a new socket with identical address and port.

So far the closing of a TcpStream is performed implicitly when leaving a scope and Drop is invoked.
But there is no explicit method which could be invoked to release the underlying socket staying within a scope. 

The following workarounds might be possible to overcome this limitation:
-  Overwrighting the  mutable TcpStream instance in question, but there is no Default TcpStream instance as dummy,and therefor it would be required to create a new TcpStream object and underlying socket.
- Box-ing TcpStream instances and removing from container, which would invoke Drop and implicitly method close.

**Edit**
- Maybe the following function might be called to close/release and invalidate TcpStream instances within a scope  std::mem::drop(t)  (?) This solution might  work for instances embedded into  the current lexical scope.

**Comment by carllerche** [comment]
> But there is no explicit method which could be invoked to release the underlying socket staying within a scope.

Could you explain why you need this?

Generally, the goal is for `TcpStream` to mirror the version in std as much as possible. I would suggest that if you want an explicit close fn, you file an issue on the Rust repo asking for it there.

**Comment by frehberg** [comment]
Sure :) The C-API shutdown does not release system resources, ports may keep  blocked.  But implementing tests (or HA services) it is important to close resources at a specific point in program flow. Otherwise resources might leak/cumulate or block later operations/tests. 

The implicit Drop/close as promoted by std/TcpStream is not obvious and not easy to review; 

In early days of Java it seemed fancy to null-out the file/socket handles and leave it to GC, but soon the explicit close-operation had a revival. 

IMHO the name of the release-operation does not matter, but maybe  the findings should be documented somewhere for other old-fashioned developers ;)

AFAICS: A TcpStream and other system resources are released by the impl of the  Drop trait.
- when getting out of scope (implicitly call)
- moving ownership out of scope explicitly by std::mem::drop(stream); // no experience so far
- or using the following Option pattern // no experience so far
```
let mut sock: Option<TcpStream> = ...;
...
sock = Option::None; // null-out 
```
(Thanks for your comment at  https://github.com/carllerche/mio/issues/802)
