### ISSUE TITLE
No array of TcpStream instances

### ISSUE THREAD

**Issue by frehberg** [carllerche/mio#802]
AFAICS, it is not possible to declare an array of type TcpStream, such as 
```
let mut streams : [TcpStream; N] = [TcpStream::default(); N];
``` 

TcpStream lacks the  "Default" implementation.

There should be a default instance (AKA "invalid") of TcpStream which could be used as default, and also representing a "closed" instance.

**Comment by carllerche** [comment]
If you want this feature, I would suggest that you implement your own type with this behavior.

There is no infallible way to get a socket handle, so I'm not sure why you wouldn't want to make a `[Option<TcpStream; N>]` array instead? This would be the same.

**Comment by frehberg** [comment]
good point, the Option-solution did not come into my mind
