### ISSUE TITLE
Expected performance characteristics of sharing a mio::Poll across threads

### ISSUE THREAD

**Issue by jonhoo** [carllerche/mio#809]
In [`mio-pool`](https://github.com/jonhoo/mio-pool), I'm trying out a design that lets many threads collectively handle a set of client requests by sharing a single epoll (well, `mio::Poll`) selector and using `oneshot`. This has some nice load balancing benefits over statically distributing connections between the pool, and also avoids the extra thread indirection of a dispatch model. However, I have been observing some pretty puzzling performance results when benchmarking a larger system on top of that design that I don't *think* should be happening with just the system epoll. Specifically, I observe very irregular performance as I move to higher thread counts.

Without getting into the specifics of this problem (it could totally be an error in my code at this point), what are the expected performance characteristics of `Poll::poll` when issued for the *same* `Poll` instance across many threads? I notice there is at least some [internal synchronization](https://github.com/carllerche/mio/blob/4a716d0b687592368d9e283a6ea63aedb5877fc8/src/poll.rs#L1038) there that may (?) become a scalability bottleneck at some point? I'm asking mostly out of curiosity, and to see whether this is documented somewhere that I missed. It would be useful to write this up somewhere for performance-oriented users, even if the recommendation is even to just use `epoll` directly in those cases where you don't also need cross-platform support and integration with e.g., user registrations.

**Comment by jonhoo** [comment]
I wrote up a simple load testing tool for `mio-pool`: https://github.com/jonhoo/mio-pool/blob/master/src/bin/loadtest.rs
Running it with `loadtest 1000 4 10` on a machine with plenty of cores gives the following flamegraph:
![`mio::Poll::poll` flamegraph](https://jon.tsp.io/share/mio-poll.svg)
Notice in particular that much of the time is spent in `mio::Poll::poll` (which is expected), but most of that time is spent in `pthread_cond_signal` and `Condvar::wait_timeout`. There's also a second (smaller) stack for `mio::Poll::poll` on the right with additional calls to futex lock/unlock. This seems wrong for a program that should essentially reduce to just calls to `epoll` (i.e., there are no new connections being established, new tokens being registered, user `Registrations`, etc.)

This also helps explain why I see a *slowdown* for the load test as the number of workers increases. The highest throughput is achieved by having a *single* worker (i.e., `loadtest 1000 1 10`)!

**Comment by carllerche** [comment]
I'm not entirely following how you are structuring your concurrency w/ Mio. However, I can provide a bit of context:

* `Poll::poll` adds internal synchronization in order to allow `Poll` to be `Sync` compatible. Specifically, to allow registering `Evented` handles concurrently. It isn't really advisable to call `Poll::poll` concurrently.
* All this is going to change in 0.7. `Poll` is being split into `Poll` and `Register` [PR](https://github.com/carllerche/mio/pull/764). `Poll` will still be `Sync`, but `poll` will take `&mut self` which will prevent concurrently calling that function. As such, the internal synchronization is removed.
* IMO, calling `Poll::poll` concurrently from multiple threads is generally a bad idea. The reason being is that you want to keep the logic that processes an `Evented` on the same thread as much as possible. If you call `Poll::poll` concurrently, then any arbitrary thread can receive notifications for an `Evented` handle that usually means you will end up migrating the state across threads fairly often. There could be ways to take advantage of multi threads concurrently polling a single `Poll` handle, but this is going to be very platform specific.

Hope this helps!

**Comment by jonhoo** [comment]
@carllerche and I discussed this some on IRC; I'll try to summarize the discussion here and paraphrase from the conversation.

The design I'm after is one where many threads collectively handle requests to a pool of connections (including accepting new ones). I don't want to statically partition the pool, because that can yield very poor load balancing if some connections are more busy than others. The design I want is essentially edge-triggered `epoll_wait` + `EPOLLONESHOT` (see also https://idea.popcount.org/2017-02-20-epoll-is-fundamentally-broken-12/). As a tangential point here, `EPOLLEXCLUSIVE` does *not* work for this purpose, as multiple threads can be woken up for the same connection!

> @carllerche: Yes... that is a popular blog post
> @carllerche: that also doesn't talk at all about optimizing for CPU architectures
> @jonhoo: I guess maybe mio is at a higher abstraction layer where taking advantage of the specific design for one OS isn't an intended use-case
> @carllerche at some point, it might
> @jonhoo: how would you suggest doing this with taking CPU architectures into account?
> @jonhoo: and specifically without static partitioning
> @jonhoo: [since] I have a large number of clients issuing fairly short-lived requests, and some clients may issue many more requests than others

Paraphrasing @carllerche:
> It entirely depends on the *actual* workload patterns. A good general purpose / portable setup is to run all your logic on a work stealing pool, and have a single dedicated thread running `Poll` + notifying tasks running on the pool.

> @jonhoo: That is the design I used previously, but the extra thread indirection added a decent amount of latency.

More @carllerche:
> The right solution also entirely depends on the CPU architecture you are targeting: on NUMA based system, you will penalized *very* hard for moving data across regions, whereas on non-NUMA based systems, it doesn't really matter at all (because at that point, it's just the cache that is per core). Also, you are probably going to want to re-benchmark everything post all the patches to handle the Intel & co security vulnerabilities.

> @carllerche: anyway, the only platforms that will support concurrent polling "well" will be windows w/ iocp and linux w/ epoll exclusive.
> @jonhoo: right; and taking advantage of that is not something that is really supported by mio at the moment?
> @carllerche : not really, it's been low priority for me given the lack of portability

Seems fair enough to me. When #798 is released and `Poll::poll` takes `&mut self`, this will also be made abundantly clear, as you *can't* then even call poll from many threads at the same time.

As for the future, more @carllerche paraphrasing:
> At some point in the future, the strategy for concurrency will be to clone the poll handle. Though it will probably be `Poll::try_clone` or something like that given that there are additional complexities (like windows & iocp have a concurrency limit, and it is platform specific).

With that, I think I'll close this as `wontfix` for now. It's on the radar for the future, but not generally a supported use-case. I've transitioned `mio-pool` to using `epoll` directly in jonhoo/mio-pool@97380a6cc2b5d1d930e8f0f2b068dedb807f6088 for now, which makes it less `mio` and just `epoll-pool`, but meh.
