### ISSUE TITLE
Strange deprecation warning

### ISSUE THREAD

**Issue by guillaumefont** [carllerche/mio#817]
Hi,

I'm getting a deprecation warning from code directly inspired from the docs :

```
struct Connection {
    registration: Registration,
    readiness: SetReadiness,
}

impl Evented for Connection {
    fn register(&self, poll: &Poll, token: Token, interest: Ready, opts: PollOpt)
         -> Result<()>  {
        self.registration.register(poll, token, interest, opts)
    }

    fn reregister(&self, poll: &Poll, token: Token, interest: Ready, opts: PollOpt)
         -> Result<()> {
        self.registration.reregister(poll, token, interest, opts)
    }

    fn deregister(&self, poll: &Poll) -> Result<()> {
        self.registration.deregister(poll)
    }
}
```
Strangely I'm getting a warning only for the last method :
```
warning: use of deprecated item: use `Evented` impl
  --> src\server.rs:49:27
   |
   |         self.registration.deregister(poll)
   |                           ^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default
```
Am I doing something wrong ?

mio 0.6.13
rustc 1.22.1 (05e2e1c41 2017-11-22)
cargo 0.23.0 (61fa02415 2017-11-22)
Windows 10

**Comment by Thomasdezeeuw** [comment]
You should call `deregister` on `Poll`: https://docs.rs/mio/0.6.13/mio/struct.Poll.html#method.deregister.

**Comment by carllerche** [comment]
Yes, what @Thomasdezeeuw wrote above is correct. I think the deprecation warning message is poor in this case.

There probably is also a shadowing issue between the inherent fn and the trait fn.

**Comment by tiras-j** [comment]
@carllerche Just came across this myself, specifically the confusion arises since this [Deadline example](https://docs.rs/mio/0.6.14/mio/struct.Registration.html#examples) where `deregister` is called directly on the `Registration` object.

**Comment by carllerche** [comment]
Could someone remove the deprecation warning in a PR? That probably would be sufficient in this case.

**Comment by tiras-j** [comment]
Would it be possible to simply remove the `deregister` impl on `Registration` since it's shadowed by the `Evented` impl? Or would that cause some weird edge-case behavior that could be breaking?

**Comment by carllerche** [comment]
It would probably be a breaking change.

**Comment by dvtomas** [comment]
Ok, so can you at least improve the deprecation message and update the example at https://docs.rs/mio/0.6.16/mio/struct.Registration.html, please? I was hit by this just now, if I didn't search the issues I would have a hard time figuring out what to do..
