### ISSUE TITLE
Missing way to specify EPOLLPRI with UnixReady

### ISSUE THREAD

**Issue by hetmankp** [carllerche/mio#835]
There doesn't currently appear to be any way to specify EPOLLPRI with UnixReady when registering for an event. This flag is necessary in order to be able to poll for GPIO events for the Linux GPIO files found under /sys/class/gpio

Documentation: https://www.kernel.org/doc/Documentation/gpio/sysfs.txt

**Comment by carllerche** [comment]
It should be fine to add this scoped to unix following the strategy used for other platform dependent flags.

**Comment by hawkw** [comment]
Currently, epoll events with EPOLLPRI set are treated as `Ready::readable()`:

https://github.com/carllerche/mio/blob/82066e545c3bf4ad9a0a6e270c4688d156b5a582/src/sys/unix/epoll.rs#L209-L211

If we changed `UnixReady` to have separate notions of `readable` and `priority`, I think this would need to be changed as well, which seems like a potentially breaking change to me --- @carllerche, what do you think?

**Comment by carllerche** [comment]
It could always set both readable & priority w/ epoll
