### ISSUE TITLE
poll: multiple returns with user space registration

### ISSUE THREAD

**Issue by attdona** [carllerche/mio#836]
I'm learning mio and I'm not able to understand why `poll.poll` double fires each time it is triggered by a `set_readiness` event.

    extern crate mio;
    
    use mio::event::Evented;
    use mio::{Events, Poll, PollOpt, Ready, Registration, Token};
    use std::thread::{sleep, spawn, JoinHandle};
    use std::time::{Duration, Instant};
    
    #[derive(Debug)]
    struct Output(u32, Duration);
    
    pub struct MioThread {
        registration: Registration,
        handle: JoinHandle<Output>,
    }
    
    impl MioThread {
        pub fn new(i: u32) -> MioThread {
            let now = Instant::now();
    
            let (registration, set_readiness) = Registration::new2();
    
            let handle = spawn(move || {
                sleep(Duration::from_millis((1000 - (100 * i)) as u64));
    
                set_readiness.set_readiness(Ready::readable()).unwrap();
    
                Output(i, now.elapsed())
            });
    
            MioThread {
                registration: registration,
                handle: handle,
            }
        }
    
        // manage the thread result
        fn eval_result(self) {
            let out = self.handle.join();
            println!("do whathever you want with: {:?}", out.unwrap());
        }
    }
    
    fn main() {
        let poll = Poll::new().unwrap();
    
        let mut events = Events::with_capacity(16);
    
        let mut tasks = Vec::new();
        for i in 0..5 {
            let mio_thread = MioThread::new(i);
    
            mio_thread
                .registration
                .register(&poll, Token(i as usize), Ready::readable(), PollOpt::edge())
                .unwrap();
    
            tasks.push(Some(mio_thread));
        }
    
        loop {
            let num_events = poll.poll(&mut events, None).unwrap();
            println!("poll fired: {} events", num_events);
            for event in &events {
                if event.readiness().is_readable() {
                    let Token(thread_id) = event.token();
                    
                    if let Some(t) = tasks.remove(thread_id) {
                        t.eval_result();
                    }
                    
                }
            }
        }
    }
    
    poll fired: 1 events
    do whathever you want with: Output(4, Duration { secs: 0, nanos: 600967623 })
    poll fired: 0 events
    poll fired: 1 events
    do whathever you want with: Output(3, Duration { secs: 0, nanos: 701035026 })
    poll fired: 0 events
    poll fired: 1 events
    do whathever you want with: Output(2, Duration { secs: 0, nanos: 801089370 })
    poll fired: 0 events
    poll fired: 1 events
    do whathever you want with: Output(1, Duration { secs: 0, nanos: 900890190 })
    poll fired: 0 events
    poll fired: 1 events
    do whathever you want with: Output(0, Duration { secs: 1, nanos: 600076 })
    poll fired: 0 events

What is the explanation?
Greetings
Attilio

**Comment by angelrain1** [comment]
impl MioThread {
    pub fn new(i: u32) -> MioThread {
        let handle = spawn(move || {
            sleep(Duration::from_millis((1000 - (100 * i)) as u64));

            // **readable 1**
            set_readiness.set_readiness(Ready::readable()).unwrap();

            Output(i, now.elapsed())
        });
    }

fn main() {
    for i in 0..5 {
        let mio_thread = MioThread::new(i);

        mio_thread
            .registration
            //  **readable 2**
            .register(&poll, Token(i as usize), Ready::readable(), PollOpt::edge())
            .unwrap();

        tasks.push(Some(mio_thread));
    }
}

**Comment by stbuehler** [comment]
Also see https://stackoverflow.com/questions/50147956/why-is-mios-poll-triggered-twice-for-user-generated-events where a comment already suggests that dropping a `Registration` might wake up the loop (which it indeed does, the same as a registration) without actually triggering an event.

An inner loop (in [`Poll::poll2`](https://github.com/carllerche/mio/blob/4fcc05a707da529b4bb5ccf930970268bcd4f01c/src/poll.rs#L1152..L1201)) continuing to look for events until at least one is found (or the timeout is reached) wouldn't need to go through unlocking/locking again (not sure whether `prepare_for_sleep` needs to be called again).  Unclear whether it's worth the effort...

**Comment by attdona** [comment]
Thanks for the explanation!

So this is the expected behavior when dropping a Registration, not a wrong usage pattern of Mio.
I've also tried to `deregister` the Registration before dropping but without success.

**Comment by carllerche** [comment]
@stbuehler Thanks for explaining it.

I don't think changing this is worth it. The custom locking is going to be removed in 0.7.
