### ISSUE TITLE
Consider making platform specific interfaces public

### ISSUE THREAD

**Issue by rozaliev** [carllerche/mio#837]
There some cases where `Poll` is not ideal for an application, some people want platform specific calls, other what to get rid of all synchronization. I've forked `mio` a couple of times and I know people who either did the same or rolled their own epoll implementation.

Having forks or multiple half baked syscall wrappers are not great for ecosystem in general. What do you think about making `sys` module public?

**Comment by asomers** [comment]
What part of mio do you want to replace?  Can you give an example?

**Comment by rozaliev** [comment]
I can only describe my own requirements, that is remove all synchronization. [poll1](https://github.com/carllerche/mio/blob/master/src/poll.rs#L1050) for example is just unacceptable for my use cases, can't afford any locks or atomics especially on the hot path.

**Comment by asomers** [comment]
Are you sure it's really a problem?  I think atomics are quite fast if there's no cache contention.

**Comment by carllerche** [comment]
Compared to the syscall, the atomic is virtually insignificant.

That said, the synchronization will be removed in 0.7 (see #757).
