### ISSUE TITLE
cannot accept all connections from client 

### ISSUE THREAD

**Issue by cen5bin** [carllerche/mio#845]
I write a server using mio, the code is as follows:
```
let poll = Poll::new().unwrap();
let server = TcpListener::bind(&"0.0.0.0:11233".parse().unwrap()).unwrap();
poll.register(&server, Token(0), Ready::readable(), PollOpt::edge()).unwrap();

let mut events = Events::with_capacity(1024);
loop {
    poll.poll(&mut events, None).unwrap();
    for event in events.iter() {
        let (socket, addr) = server.accept().unwrap();
        println!("{:?} connected", addr);
    }
    events.clear();
}
```
The server only accepts the connections and print the address.
And then I write a java client, as follows:
```
int count = 20;
ExecutorService service = Executors.newFixedThreadPool(count);
for (int i = 0; i < count; i++) {
    service.execute(() -> {
        try {
            System.out.println("start connecting");
            Socket socket = new Socket("127.0.0.1", 11233);
            System.out.println("finish connecting");
            Thread.sleep(10000);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    });
}
service.shutdown();
service.awaitTermination(10000000, TimeUnit.SECONDS);
```
But the server cannot accept all the 20 connections. It's strange. I suspect there may be something wrong with my environment, like `somaxconn`. But I think the default value is enough for the 20 connections. Then I rewrite the server with std::net::TcpListener, as follows:
```
let server = TcpListener::bind("0.0.0.0:11233").unwrap();
let mut t = Vec::new();
loop {
    let (socket, addr) = server.accept().unwrap();
    println!("{:?}", addr);
    t.push(socket);
}
```
This can accept all. So I think the environment is nothing wrong.  And I also write a java server, it can also accept all.

May I use mio in a wrong way?

**Comment by Thomasdezeeuw** [comment]
You should call `server.accept` until you hit a [`WouldBlock`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.WouldBlock) error when using `edge` for `PollOpt`. See https://docs.rs/mio/0.6.14/mio/struct.Poll.html#edge-triggered-and-level-triggered for proper usage of `PollOpt`.

**Comment by carllerche** [comment]
Thanks @Thomasdezeeuw for the help.

I'm going to close this issue as I do not believe that there is any further action to take.
