### ISSUE TITLE
`os` should be public, so that other libraries using mio can implement new mio-compatible IoHandle's

### ISSUE THREAD

**Issue by reem** [carllerche/mio#85]
The bindings and utility functions are valuable to those writing other extensions, like support for reading/writing from files.

**Comment by carllerche** [comment]
What are your plans for reading / writing from files? These ops are fundamentally sync?

**Comment by reem** [comment]
Libuv (and as a result node and friends) offers non-blocking file IO for reading/writing, I figure we will want something similar.

**Comment by reem** [comment]
Some stuff on libuv filesystem operations: http://nikhilm.github.io/uvbook/filesystem.html

**Comment by reem** [comment]
Actually, by reading a bit more I've learned that libuv just uses a thread pool to simulate asynchronicity for these operations...

Regardless, I'd still like os to be public so downstream libraries can build their own versions of primitives.

**Comment by ayosec** [comment]
> libuv just uses a thread pool to simulate asynchronicity for these operations...

MS Windows has [native support](http://msdn.microsoft.com/en-us/library/kztecsys%28v=vs.110%29.aspx) for async IO in files. POSIX has the [AIO interface](http://man7.org/linux/man-pages/man7/aio.7.html), but you have to rely on signals, and the support in most operating systems (IIRC) is not pretty good.

**Comment by carllerche** [comment]
I don't know if I want to expose all of `os`. What specifically do we need besides `IoDesc`?

**Comment by reem** [comment]
I'm not sure yet actually. I've been chugging along with my own local modifications to mio for rust-aio and I'll make a PR with the changes that are actually needed once aio is in an actually usable state.

**Comment by carllerche** [comment]
I'm going to close this for now since `IoDesc` is already exposed.
