### ISSUE TITLE
Enable webhooks for FreeBSD buildbot

### ISSUE THREAD

**Issue by asomers** [carllerche/mio#855]
Currently the FreeBSD buildbot is polling github for changes to mio.  Builds will be faster if you enable webhooks.  To do that, go into Settings->Webhooks.  Click "Add Webhook".  For the payload url, use "https://alan.ci/buildbot/change_hook/github?project=carllerche/mio".  For events, select "Let me select individual events", and check "Pushes" and "Pull Requests".  Finally, check "Active" at the bottom.  You'll also need a secret key for the "Secret" field.  Send me a private message on Gitter for the key.

**Comment by carllerche** [comment]
I added it but got the following error:

## Headers

```
Connection: keep-alive
Content-Length: 33
Content-Type: text/html
Date: Tue, 03 Jul 2018 23:19:59 GMT
Server: nginx/1.12.1
Transfer-Encoding: chunked
```
Body

```
Request has no required signature
```

**Comment by asomers** [comment]
Is that error from GitHub or buildbot?  I wonder if "no required signature" is because the secret key was missing.

**Comment by carllerche** [comment]
I did not put in a secret key. It looks like that is the HTTP response returned from your server.

**Comment by Thomasdezeeuw** [comment]
Since Cirrus CI is now enabled is this still relevant @asomers?

**Comment by asomers** [comment]
Nope.
