### ISSUE TITLE
What is the advised way to read?

### ISSUE THREAD

**Issue by mtharrison** [carllerche/mio#873]
This is a very basic question, I'm a Rust newbie but I found it hard to get an answer by looking through existing examples, tests or docs.

When my socket is ready how should I read from it? Almost all of the examples I saw are using `try_read_buf()` or `try_read()` but these not seem to be public methods. It looks like 0.5 had a TryRead trait but that isn't available in 0.6. Was it replaced with something else?

The `TcPStream` struct docs tells me that `TcPStream` implements `std::io::Read`. Based on that I considered just looping over `read()` to consume all available data (as I'm in edge triggered mode) how you might do when dealing `epoll()` in C

```rust
if event.readiness().contains(Ready::readable()) {

    let mut buff = [0; 1024];

    loop {
        match tcp_stream.read(&mut buff) {
            Ok(n) if n > 0 => {
                println!("DEBUG: {:?} Read {} bytes", event.token(), n);
            }
            _ => break,
        }
    }
}
```

This seems to work fine but is there some more Rusty or mio blessed way to do this? Also is it worth documenting it (maybe it is but I couldn't find it). I'm happy to open a PR on the docs if so.

**Comment by carllerche** [comment]
That is the correct way 👍
