### ISSUE TITLE
Switch FreeBSD CI to Cirrus

### ISSUE THREAD

**Issue by asomers** [carllerche/mio#895]
cirrus-ci.com recently added a FreeBSD build option.  It integrates with Github, it's free for FOSS, and seems to work ok.  Switching from buildbot to cirrus-ci.com would increase mio's bus factor and save @asomers $$$.  Do you agree @carllerche ?

**Comment by asomers** [comment]
ping @carllerche .  Only the repository owner has the permission to activate Cirrus-ci.

**Comment by carllerche** [comment]
Sounds good to me 👍 I'll look into it.

**Comment by carllerche** [comment]
Are there steps for me to follow?

**Comment by asomers** [comment]
Follow the instructions at https://cirrus-ci.org/guide/quick-start/ and stop at "Post Installation".  Then I'll do the rest.

**Comment by carllerche** [comment]
I think it is done?

**Comment by asomers** [comment]
Cool.  I just shut down the VM.  But I didn't delete it, so we can fire it back up to pull old build logs if necessary.

**Comment by carllerche** [comment]
Should I remove the webhook?

**Comment by asomers** [comment]
Go ahead.
