### ISSUE TITLE
Eventloop is not longuer Send

### ISSUE THREAD

**Issue by vberger** [carllerche/mio#90]
Following last rust changes, EventLoop is not longer considered `Send` by the compiler. It effectively prevents initialising an EventLoop and then spawing a new thread to make it run.

The fix might be as simple as adding
```
unsafe impl<T: 'static, M: Send> Send for EventLoop<T, M> {}
```
but it can probably be handled better on the various subtypes of the library.

**Comment by carllerche** [comment]
Yeah, there is probably a single subtype that has an unsafe pointer that needs to be marked `Send`. It might even be the vendored mpmc queue.

**Comment by vberger** [comment]
The exact error I have, on rust alpha is:
```
error: the trait `core::marker::Send` is not implemented for the type `*mut mio::util::slab::Entry<mio::timer::Entry<()>>`
```
