### ISSUE TITLE
why not support async io?

### ISSUE THREAD

**Issue by ChinaXing** [carllerche/mio#900]
noBlocking io in file io, is general useful. why don't include aio or other no-blocking file io in ?

**Comment by asomers** [comment]
In fact, mio does support AIO, with extra crates.  See https://github.com/asomers/mio-aio for POSIX aio bindings (currently FreeBSD only, but could be made to work on Linux and OSX with worse performance).  And if you're using Tokio, then you can use https://github.com/asomers/tokio-file for POSIX aio, https://github.com/hmwill/tokio-linux-aio for Linux's libaio, or https://github.com/tokio-rs/tokio/tree/master/tokio-fs (portable, but it implemented with a pool of blocking threads).

**Comment by carllerche** [comment]
Yep :-) Mio only provides tcp / udp because of how common it is. It should be possible to add other functionality in third party crates.
