### ISSUE TITLE
check if poll is empty

### ISSUE THREAD

**Issue by devsnek** [carllerche/mio#918]
I'd like to be able to check if anything is scheduled before i poll so I can exit my program gracefully.

```rust
loop {
  if poll.is_empty() { break; }
  poll.poll(...);
  ...
}
```

**Comment by Thomasdezeeuw** [comment]
I don't think it possible to do this in a cross platform way, but I could be wrong.

In my own project I usually have to kind of data structure that maps `Token`s to something can be run (e.g. a `Future`), those runnable objects can mark themselves as done and then I simply check if that data structure empty and stop the event loop.

**Comment by devsnek** [comment]
yeah as my app has gotten more complex I ended up with such a map as well
